MTRand_int32
const int MTRand_int32::n
const int MTRand_int32::m
unsigned long MTRand_int32::state[n]
int MTRand_int32::p
bool MTRand_int32::init
MTRand_int32::MTRand_int32()
References seed.
MTRand_int32::MTRand_int32(unsigned long s)
References seed.
MTRand_int32::MTRand_int32(const unsigned long *array, int size)
References seed.
void MTRand_int32::seed(unsigned long)
References i.
Referenced by main, seed, MTRand_int32.
void MTRand_int32::seed(const unsigned long *, int size)
References seed, j, k, i, size.
unsigned long MTRand_int32::operator()()
References rand_int32.
virtual MTRand_int32::~MTRand_int32()
unsigned long MTRand_int32::rand_int32()
References x.
Referenced by operator(), MTRand::operator(), MTRand_closed::operator(), MTRand_open::operator(), MTRand53::operator().
unsigned long MTRand_int32::twiddle(unsigned long, unsigned long)
void MTRand_int32::gen_state()
MTRand_int32::MTRand_int32(const MTRand_int32 &)
void MTRand_int32::operator=(const MTRand_int32 &)