environment
acs_int environment::nSIM
acs_int environment::nGEN
acs_double environment::actualTime
acs_double environment::nSeconds
acs_int environment::nReactions
acs_double environment::nHours
acs_int environment::nAttempts
acs_int environment::Currentattempts
acs_double environment::timeStructuresSavingInterval
acs_double environment::fileTimesSaveInterval
acs_double environment::newSpeciesProbMinThreshold
acs_int environment::lastFiringDiskSpeciesID
acs_double environment::overallConcentration
acs_double environment::ECConcentration
acs_int environment::nonCatalyticMaxLength
acs_longInt environment::nonCatalyticLastID
acs_double environment::reactionProbability
acs_double environment::cleavageProbability
bool environment::main_rev_rct_allowed
bool environment::reverseReactions
acs_double environment::revRctRatio
acs_double environment::spontRct
species environment::nrgCarrier
acs_longInt environment::numberOfMolecules
acs_longInt environment::numberOfNewMolecules
acs_longInt environment::numberOfSpecies
acs_longInt environment::numberOfNewSpecies
acs_longInt environment::numberOfCpx
acs_longInt environment::numberOfCpxMols
acs_longInt environment::cleavageCounter
acs_longInt environment::endoCleavageCounter
acs_longInt environment::condensationCounter
acs_longInt environment::endoCondensationCounter
acs_longInt environment::cpxFormCounter
acs_longInt environment::cpxDissCounter
acs_longInt environment::spontDissCounter
acs_longInt environment::spontAssCounter
int environment::overallLoadedMolsCounter
acs_double environment::internalTimesStoredCounter
acs_int environment::lastEvaluatedSpeceisForNewReactions
acs_double environment::K_ass
acs_double environment::K_diss
acs_double environment::K_cpx
acs_double environment::K_cpxDiss
acs_double environment::K_nrg
acs_double environment::K_nrg_decay
acs_double environment::K_spont_diss
acs_double environment::K_spont_ass
acs_int environment::maxLOut
acs_double environment::cleavage_KineticConstant
acs_double environment::complex_KineticConstant
acs_double environment::condensation_KineticConstant
acs_double environment::complexDeg_KineticConstant
acs_double environment::moleculeDecay_KineticConstant
acs_double environment::currentTotalTime
acs_int environment::energy
acs_double environment::ratioSpeciesEnergizable
acs_int environment::nrgBoolFlag
acs_int environment::solubility_threshold
acs_double environment::diffusion_contribute
acs_double environment::influx_rate
acs_double environment::timeSinceTheLastInFlux
string environment::alphabet
acs_double environment::volume
bool environment::volumeGrowth
bool environment::stochDivision
acs_double environment::randomSeed
vector<species> environment::allSpecies
vector<species> environment::firingDisk
vector<acs_int> environment::nutrientsForInflux
vector<acs_double> environment::nutrientsProb2BeSelected
vector<reactions> environment::allReactions
vector<catalysis> environment::allCatalysis
vector<species> environment::initialAllSpecies
vector<reactions> environment::initiaAllReactions
vector<catalysis> environment::initialAllCatalysis
vector<gillespie> environment::allGillespieScores
vector<gillespie> environment::COPYOFallGillespieScores
vector<acs_double> environment::gillespieCumulativeStepScoreList
vector<acs_double> environment::allTimes
int environment::debugLevel
vector<acs_int> environment::livingSpeciesIDsList
vector<acs_double> environment::cumLivingAmountsList
vector<acs_int> environment::unchargedIDlist
vector<acs_double> environment::cumUnchargedAmountList
vector<acs_int> environment::chargedIDlist
vector<acs_double> environment::cumChargedAmountList
vector<acs_int> environment::nrgBooleanFunctions
vector<acs_double> environment::nrgBoolFncsProb2BeSelected
acs_double environment::decimalMoleculesToEfflux
acs_double environment::decimalMoleculesToLoad
acs_double environment::decimalMoleculesToUNLOAD
acs_double environment::decimalComplexesToDissociate
acs_longInt environment::gillespieReactionSelected
acs_double environment::gillespieMean
acs_double environment::gillespieSD
acs_double environment::gillespieEntropy
acs_double environment::gillespieTotalScore
acs_double environment::gillespieNewSpeciesScore
acs_double environment::ratioBetweenNewGillTotGill
acs_double environment::reverseReactionsGillScore
acs_double environment::ratioBetweenReverseAndTotalScore
acs_double environment::gillespieTime
acs_double environment::performReactionTime
acs_double environment::remainingProcessesTime
clock_t environment::gillespiePartialTimer
clock_t environment::performReactionPartialTimer
clock_t environment::remainingProcessesPartialTimer
environment::environment(string tmpInitialPath)
TEMPLATE DEACLARATION AND DEFINITION Test environment costructor 2.4 2010-06-27 tmpRndDoubleGen randomGenerator reference Environment Constructor 1.0 tmpInitialPath 2013/07/04
References FINDERRORDURINGRUNTIME, split, fromStrToBool, ExitWithError, RUNNING_VERSION, showGlobalParameter, ENERGYBASED, ENERGYFREE, resetReactionsCounter.
environment::~environment()
acs_int environment::getNgen() const
Referenced by main.
acs_int environment::getNsim() const
Referenced by main.
acs_double environment::getActualTime() const
Referenced by performReaction, main.
acs_double environment::getNseconds() const
Referenced by main.
acs_int environment::getNreactions() const
acs_double environment::getMAXhours() const
Referenced by main.
acs_int environment::getMAXattempts() const
Referenced by main.
acs_int environment::getCurrentAttempts() const
Referenced by main.
acs_double environment::getTimeStructuresSavingInterval() const
Referenced by main.
acs_double environment::getFileTimesSavingInterval() const
Referenced by performReaction, main.
acs_int environment::getLastFiringDiskSpeciesID() const
Referenced by createInitialMoleculesPopulationFromFileSTD, createInitialMoleculesPopulationFromSpecificFileSTD.
acs_double environment::getOverallConcentration() const
acs_int environment::getMaxNonCatalyticLength() const
acs_double environment::getRctProb() const
acs_double environment::getCleavProb() const
bool environment::getReverseReactions() const
acs_int environment::getEnergy() const
Referenced by main, saveInitialConditionsToFile.
acs_double environment::getRatioSpeciesEnergizable() const
acs_int environment::getADP() const
References species::getNOTchargeMols.
acs_int environment::getATP() const
References species::getChargeMols.
acs_longInt environment::getMols() const
Referenced by main.
acs_longInt environment::getNewMols() const
Referenced by main.
acs_longInt environment::getNspecies() const
Referenced by main.
acs_longInt environment::getNnewSpecies() const
Referenced by main.
acs_longInt environment::getNcpx() const
Referenced by main.
acs_longInt environment::getNcpxMols() const
Referenced by main.
acs_double environment::getGillespieMean() const
Referenced by main.
acs_double environment::getgillespieSD() const
Referenced by main.
acs_double environment::getgillespieEntropy() const
Referenced by main.
acs_double environment::getRatioBetweenNewGillTotGill() const
Referenced by main.
acs_double environment::getRatioBetweenBackandForw() const
Referenced by main.
bool environment::getSystemExpFlag() const
acs_double environment::getKdiss() const
acs_double environment::getKass() const
acs_double environment::getKcpx() const
acs_double environment::getKcpxDiss() const
acs_double environment::getKnrg() const
acs_double environment::getKirrad() const
acs_double environment::getK_spont_diss() const
acs_double environment::getK_spont_ass() const
acs_double environment::getCleavageKC() const
acs_double environment::getComplexKC() const
acs_double environment::getCondensationKC() const
acs_double environment::getComplexDegKC() const
acs_double environment::getMoleculeDecayKC() const
acs_int environment::getMaxLOut() const
acs_int environment::getSolubilityThreshold() const
acs_double environment::getDiffusionContribute() const
acs_double environment::getInflux() const
Referenced by main, saveInitialConditionsToFile.
acs_double environment::getRefillInterval() const
string environment::getAlphabet() const
acs_double environment::getVolume() const
Referenced by main.
acs_double environment::getRandomSeed() const
Referenced by main.
vector<species> environment::getMoleculesPopulation() const
acs_longInt environment::getTotalNumberOfSpecies()
This Function returns the total amount of MOLECULES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command vector<species>* tmpSpeciesvector pointer to tmpSpeciesvector
References FINDERRORDURINGRUNTIME, SOLUBLE.
Referenced by clearAllStructures, resetConcentrationToInitialConditions, saveTimesSTD.
acs_longInt environment::getTotalNumberOfPossibleCatalysts()
This Function returns the total amount of MOLECULES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command vector<species>* tmpSpeciesvector pointer to tmpSpeciesvector
References FINDERRORDURINGRUNTIME, SOLUBLE.
Referenced by main.
acs_longInt environment::getTotalNumberOfMolecules()
This Function returns the total amount of MOLECULES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command vector<species>* tmpSpeciesvector pointer to tmpSpeciesvector
References FINDERRORDURINGRUNTIME, SOLUBLE.
Referenced by performRefill, performMoleculesEfflux, clearAllStructures, resetConcentrationToInitialConditions, saveTimesSTD.
acs_longInt environment::getTotalNumberOfComplexSpecies()
This Function returns the total amount of COMPLEX SPECIES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command vector<species>* tmpSpeciesvector pointer to tmpSpeciesvector
References FINDERRORDURINGRUNTIME.
Referenced by clearAllStructures, resetConcentrationToInitialConditions, saveTimesSTD.
acs_longInt environment::getTotalNumberOfComplexes()
This Function returns the total amount of MOLECULES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command vector<species>* tmpSpeciesvector pointer to tmpSpeciesvector
References FINDERRORDURINGRUNTIME.
Referenced by clearAllStructures, resetConcentrationToInitialConditions, saveTimesSTD.
acs_longInt environment::getTotalNumberOfMonomers()
This Function returns the total amount of MONOMERS in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command vector<species>* tmpSpeciesvector pointer to tmpSpeciesvector
References FINDERRORDURINGRUNTIME, SOLUBLE.
Referenced by saveTimesSTD, main.
vector<reactions> environment::getReactionsLayer() const
int environment::getDebugLevel() const
Referenced by main.
acs_longInt environment::getNumberOfTheoreticalSpecies() const
Referenced by returnPosSpeciesAlreadyPresent, structureCoherenceCheckUp, printInitialCondition.
acs_longInt environment::getNumberOfReactions() const
Referenced by createReactionsForThisSpecies, updateReactions, returnPosReactionAlreadyPresent, structureCoherenceCheckUp, printInitialCondition.
acs_longInt environment::getNumberOfCatalysis() const
Referenced by createReactionsForThisSpecies, updateReactions, checkIfTheReactionIsAlreadyCatalyzedByThisSpecies, checkIfOnlyMutualCatalysis, structureCoherenceCheckUp, printInitialCondition, main.
acs_longInt environment::getNumberOfGillespieCOPYpossibleRcts() const
Referenced by main.
acs_longInt environment::getNumberOfGillespiePossibleRcts() const
void environment::setLivingSpeciesIDsAndAmounts()
This function populates to lists, the first containing all the living species ID and the second one containing the cumulative number of living species 2.5.2 2010-11-11
References FINDERRORDURINGRUNTIME, SOLUBLE.
Referenced by performMoleculesEfflux.
void environment::setNotChargedAndChargedSpeciesIDsAndAmounts()
This function populates to lists, the first one contains the IDs of the uncharged mols and the second one contains the cumulative amount of uncharged molecules 2.5.3 2011-02-22
References FINDERRORDURINGRUNTIME, SOLUBLE, ENERGYBASED.
Referenced by performDETMoleculesCharging.
acs_longInt environment::getCleavageCounter() const
Referenced by main.
acs_longInt environment::getEndoCleavageCounter() const
Referenced by main.
acs_longInt environment::getCondensationCounter() const
Referenced by main.
acs_longInt environment::getEndoCondensationCounter() const
Referenced by main.
acs_longInt environment::getCpxFormCounter() const
Referenced by main.
acs_longInt environment::getCpxDissCounter() const
Referenced by main.
acs_longInt environment::getOverallLoadedMolsCounter() const
Referenced by main.
acs_longInt environment::getSpontDissCounter() const
Referenced by main.
acs_longInt environment::getSpontAssCounter() const
Referenced by main.
acs_int environment::getTotNumberOfChargedMols()
Get the total number of charged molecules
References FINDERRORDURINGRUNTIME.
Referenced by main.
void environment::showGlobalParameter()
Shows all parameters uploaded from the configuration file 1.0
References FINDERRORDURINGRUNTIME, RUNNING_VERSION, __SOFTVERSION__, NEP, AVO.
Referenced by environment.
void environment::printInitialCondition()
Show all initial species in table format 1.0
References FINDERRORDURINGRUNTIME, getNumberOfTheoreticalSpecies, i, getNumberOfReactions, ExitWithError, getNumberOfCatalysis.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation, main.
void environment::printAllSpeciesIdAndSequence()
Show all the species with their ID 1.0
References FINDERRORDURINGRUNTIME, i.
Referenced by newSpeciesEvaluationIII.
void environment::printGillespieStructure()
Show all the Gillespie Structure 1.0
References FINDERRORDURINGRUNTIME, i.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation, performSingleGilleSpieIntroduction, performReaction.
void environment::printNutrientsAndProbability()
This Function populates two vectors containing all the nutrients and all the probabilities for the influx selected species from the firing disk according to the max length of the influx This function print to monitor the content of the vectors nutrientsForInflux and nutrientsProb2BeSelected 1.0 2010-05-17
References FINDERRORDURINGRUNTIME.
void environment::printAllChargeMols()
Print all the energized molecules 1.0 2010-11-14
References ExitWithError.
bool environment::createInitialMoleculesPopulationFromFileSTD(string tmpSpeciesFilePath)
Initial molecule population creation from file using standard C++ libraries 1.0 string tmpSpeciesFilePath file path 20130702
References FINDERRORDURINGRUNTIME, ExitWithError, species, incNumberOfNewSpecies, incNumberOfCpx, getLastFiringDiskSpeciesID, SMALL_DEBUG.
Referenced by main.
bool environment::createInitialReactionsLayerFromFileSTD(string tmpSpeciesFilePath)
Reactions from file using standard C++ libraries 1.0 string tmpSpeciesFilePath file path 20130702
References FINDERRORDURINGRUNTIME.
Referenced by main.
bool environment::createInitialCatalysisLayerFromFileSTD(string tmpCatalysisFilePath)
Catalysis from file using standard C++ libraries 1.0 string tmpSpeciesFilePath file path 20130702
References FINDERRORDURINGRUNTIME, inserSubListInSpecies.
Referenced by main.
bool environment::createInfluxLayersFromFileSTD(string tmpInfluxFilePath)
Create influx layer from file C++ libraries 1.0 string tmpInfluxFilePath file path 20130702
References FINDERRORDURINGRUNTIME.
Referenced by main.
bool environment::createNrgBooleanFunctionsFromFileSTD(string tmpBoolNrgFilePath)
load energy boolean function (in decimal format) - Standard C++ 1.0 string tmpBoolNrgFilePath file path 20130702
References FINDERRORDURINGRUNTIME.
Referenced by main.
bool environment::createInitialMoleculesPopulationFromSpecificFileSTD(string tmpSpeciesFilePath, acs_int tmpActGEN, acs_int tmpActSIM)
Initial molecule population creation from file 1.0 QString tmpSpeciesFilePath file path Initial molecule population creation. Species are uploaed from a SPECIFIC file created using actual generation and simuation 1.0 QString tmpSpeciesFilePath file path Initial molecule population creation. Species are uploaed from a SPECIFIC file created using actual generation and simuation (standard C++ libraries) 1.0 QString tmpSpeciesFilePath file path
References FINDERRORDURINGRUNTIME, zeroBeforeStringNumberSTD, species, incNumberOfNewSpecies, incNumberOfCpx, ExitWithError, getLastFiringDiskSpeciesID.
bool environment::createInitialReactionsLayerFromSpecificFileSTD(string tmpReactionsFilePath, acs_int tmpActGEN, acs_int tmpActSIM)
Reactions from file using standard C++ libraries 1.0 string tmpSpeciesFilePath file path 20130702
References FINDERRORDURINGRUNTIME, zeroBeforeStringNumberSTD.
bool environment::createInitialCatalysisLayerFromSpecificFileSTD(string tmpCatalysisFilePath, acs_int tmpActGEN, acs_int tmpActSIM)
catalysis from file using standard C++ libraries 1.0 string tmpSpeciesFilePath file path 20130702
References FINDERRORDURINGRUNTIME, zeroBeforeStringNumberSTD, inserSubListInSpecies.
void environment::nutrientsAmountsFixing()
Nutrients amount fixing process. The amount of nutrients has to be fixed according to the initial theoretical distribution 1.0
References FINDERRORDURINGRUNTIME.
acs_int environment::computeSngSpeciesRctsNumber(acs_longInt tmpTotalNumberOfReactions, MTRand &tmpRndDoubleGen)
Initial molecule population creation. If the number of species stored in the configuration file is grater than the possible number of species according to the alphabet and maximum length all species up to the MAX length will be created 1.0 MTRand& tmpRndDoubleGen initial layer initialization 1.0 MTRand& tmpRndDoubleGen Compute number of reaction catalysd by a catalyst according to the total number of reactions and reactions probabilities 1.0 acs_int tmpTotalNumberOfReactions Total number of conceivable reactions acs_double tmpRctsProb reaction probability
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, random_binomial.
Referenced by newSpeciesEvaluationIII.
acs_int environment::selectWhetherCleavageOrCond(MTRand &tmp__RndDoubleGen)
Select reaction type (cleavage or condensation) according to the cleavage probability 1.0 acs_int tmpTotalNumberOfReactions Total number of conceivable reactions acs_double tmpRctsProb reaction probability
References FINDERRORDURINGRUNTIME, CONDENSATION, CLEAVAGE.
Referenced by createReactionsForThisSpecies.
bool environment::createReactionsForThisSpecies(acs_longInt tmpsID, acs_int tmpReactionsForThisSpecies, MTRand &tmp_RndDoubleGen, vector< acs_longInt > &tmpIDOfCandidateSpecies, acs_int tmpRctCreationType)
Creation of all the reactions related to one specific species 1.1 2011/07/07 acs_longInt tmpsID species vector ID acs_int tmpReactionsForThisSpecies number of reactions to create for this species MTRand& tmp_RndDoubleGen random number generator vector<acs_longInt>& tmpIDOfCandidateSpecies ID of the species avalaible for the reaction acs_int tmpRctCreationType NEWREACTION or UPGRADEREACTIONS
References FINDERRORDURINGRUNTIME, ESOERGONIC, NOTENERGIZABLE, i, NEWREACTIONS, ExitWithError, SMALL_DEBUG, selectWhetherCleavageOrCond, CLEAVAGE, returnUniformSelection_LONG_IdFromVector, getIntRandom, MEDIUM_DEBUG, returnPosSpeciesAlreadyPresent, notInverseReactionAlreadyCatalyzed, ENERGIZABLE, species, CONDENSATION, getNumberOfReactions, returnPosReactionAlreadyPresent, ENERGYBASED, returnSelectionIdFromAWeightProbVectorAlreadyNormalized, NOSPONTANEOUS, ENDO_CONDENSATION, getNumberOfCatalysis, checkIfTheReactionIsAlreadyCatalyzedByThisSpecies.
Referenced by newSpeciesEvaluationIII.
bool environment::updateReactions(acs_longInt tmpIDtoUpdate, acs_longInt tmpNewSpecies, acs_int tmpRctType, vector< acs_longInt > &tmp_AlreadyEvaluatedSpeciesVector, MTRand &tmp_RndDoubleGen)
Old Species Reactions and Catalysis update process 1.0 2013/07/30 acs_longInt tmpIDtoUpdate ID of the species to update acs_longInt ID of the new species involved in the reactions to update acs_int tmpRctType Reaction type, namely cleavage or condensation MTRand& tmp____RndDoubleGen Random number generator
References FINDERRORDURINGRUNTIME, ESOERGONIC, NOTENERGIZABLE, CLEAVAGE, getIntRandom, ExitWithError, returnPosSpeciesAlreadyPresent, notInverseReactionAlreadyCatalyzed, ENERGIZABLE, species, returnUniformSelection_LONG_IdFromVector, SMALL_DEBUG, CONDENSATION, getNumberOfReactions, returnPosReactionAlreadyPresent, ENERGYBASED, returnSelectionIdFromAWeightProbVectorAlreadyNormalized, NOSPONTANEOUS, ENDO_CONDENSATION, getNumberOfCatalysis, checkIfTheReactionIsAlreadyCatalyzedByThisSpecies.
Referenced by newSpeciesEvaluationIII.
acs_double environment::createDiffusionRenforcement(acs_double tmpDiffEnh, acs_int tmpNewSpeciesLength)
Create the diffusion constant renforcement according to the species length 1.0 tmpDiffEnh diffusion enhancement from parameters MTRand& tmp_RndDoubleGen random number generator tmpNewSpeciesLength Lenght of the species
References FINDERRORDURINGRUNTIME.
Referenced by newSpeciesEvaluationIII, complexEvaluation.
bool environment::setSolubility(acs_int tmpNewSpeciesLength, MTRand &tmpRndDoubleGen)
Create the precipitation constant renforcement according to the species length 2.5.1 tmpPreEnh precipitation enhancement from parameters MTRand& tmp_RndDoubleGen random number generator tmpNewSpeciesLength Lenght of the species
References FINDERRORDURINGRUNTIME.
Referenced by newSpeciesEvaluationIII.
acs_longInt environment::returnPosSpeciesAlreadyPresent(string tmpNewSequence)
This functions returns the ID of the species whether this one is already present, otherwise the new ID is created as the number of elements in the species vector 1.0 tmpNewSequence New sequence to evaluate MTRand& tmp_RndDoubleGen random number generator tmpNewSpeciesLength Lenght of the species
References FINDERRORDURINGRUNTIME, i, getNumberOfTheoreticalSpecies.
Referenced by createReactionsForThisSpecies, updateReactions.
acs_longInt environment::returnPosReactionAlreadyPresent(acs_int tmpReactionType, acs_longInt tmpIds_I, acs_longInt tmpIds_II, acs_longInt tmpIds_III)
Return the reaction ID if the reaction is already present, otherwise it returns the new reaction ID 1.0 acs_int tmpReactionType rection type (cleavage or condensation) acs_longInt tmpIds_I species I ID acs_longInt tmpIds_II species II ID acs_longInt tmpIds_III species III ID
References FINDERRORDURINGRUNTIME, i, getNumberOfReactions.
Referenced by createReactionsForThisSpecies, updateReactions.
bool environment::checkIfTheReactionIsAlreadyCatalyzedByThisSpecies(acs_longInt tmpSPeciesID, acs_longInt tmpIdReaction)
If the reaction is not new this function checks if the reactions has been already catalysed by this species 1.0 acs_int tmpSPeciesID catalyst ID tmpIdReaction reaction ID
References FINDERRORDURINGRUNTIME, i, getNumberOfCatalysis.
Referenced by createReactionsForThisSpecies, updateReactions.
bool environment::performOPTGillespieComputation(MTRand &tmpRndDoubleGen, clock_t &tmpTimeElapsed, acs_int tmpActGEN, acs_int tmpActSIM, acs_int tmpActSTEP, string tmpStoringPath)
Perform all the gillespie algorithm procedure (OPTIMIZED VERSION) 1.0 2013.09.17 tmpRndDoubleGen random numbers generator tmpTimeElapsed Computation time elapsed from the T0 tmpActGEN actual generation tmpActSIM actual simulation tmpActSTEP actual step (reaction) tmpStoringPath path where results are stored
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, ExitWithError, SOLUBLE, CONDENSATION, COMPLEXSTUFF, ENERGYBASED, TRUENRG, performSingleGilleSpieIntroduction, ENDO_CONDENSATION, COMPLEXLOAD, SUBSTRATELOAD, BOTHLOAD, NOTHINGLOAD, dec2bin, CLEAVAGE, checkAvailability, ENDO_CLEAVAGE, CATALYSTLOAD, ENDO_COMPLEXFORMATION, COMPLEXFORMATION, MEDIUM_DEBUG, SPONTANEOUS_CLEAVAGE, SPONTANEOUS_CONDENSATION, printGillespieStructure, AVO, returnSelectionIdFromAWeightProbVector, GILLESPIESTUFF, printInitialCondition, MINIMALRCTTIMEMULTI, setActualTime, devStd, entropy, performReaction, changeVolume, RUNNING_VERSION, performRefill, performMoleculesEfflux, performDETMoleculesCharging, performDETComplexDissociation.
Referenced by main.
bool environment::perform_FIXED_GillespieComputation(MTRand &tmpRndDoubleGen, clock_t &tmpTimeElapsed, acs_int tmpActGEN, acs_int tmpActSIM, acs_int tmpActSTEP, string tmpStoringPath)
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, ExitWithError, SOLUBLE, CONDENSATION, COMPLEXSTUFF, ENERGYBASED, TRUENRG, performSingleGilleSpieIntroduction, ENDO_CONDENSATION, COMPLEXLOAD, SUBSTRATELOAD, BOTHLOAD, NOTHINGLOAD, dec2bin, CLEAVAGE, checkAvailability, ENDO_CLEAVAGE, CATALYSTLOAD, ENDO_COMPLEXFORMATION, COMPLEXFORMATION, MEDIUM_DEBUG, SPONTANEOUS_CLEAVAGE, SPONTANEOUS_CONDENSATION, printGillespieStructure, AVO, returnSelectionIdFromAWeightProbVector, GILLESPIESTUFF, printInitialCondition, MINIMALRCTTIMEMULTI, setActualTime, devStd, entropy, performReaction, changeVolume, RUNNING_VERSION, performRefill, performMoleculesEfflux, performDETMoleculesCharging, performDETComplexDissociation.
bool environment::performReaction(acs_longInt reaction_u, MTRand &tmp_RndDoubleGen, acs_int tmp_ActGEN, acs_int tmp_ActSIM, acs_int tmp_ActSTEP, string tmp_StoringPath)
Perform the reaction after the Gillespie computation 1.1 2013-10-29 acs_longInt reaction_u reaction ID in Gillespie structure MTRand& tmp_RndDoubleGen Random number generator acs_int tmp_ActGEN Current generation acs_int tmp_ActSIM Current generation acs_int tmp_ActSTEP Current step (reaction) string Storing directory
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, printGillespieStructure, ExitWithError, CONDENSATION, performCondensation, RUNNING_VERSION, getActualTime, getFileTimesSavingInterval, saveReactionsParametersSTD, saveLivingSpeciesIDSTD, saveLivingSpeciesAmountSTD, saveLivingSpeciesConcentrationSTD, ENDO_CONDENSATION, perform_endo_Condensation, CLEAVAGE, performCleavage, ENDO_CLEAVAGE, perform_endo_Cleavage, COMPLEXFORMATION, performComplexFormation, ENDO_COMPLEXFORMATION, perform_endo_ComplexFormation, COMPLEXDEGRADATION, performComplexDissociation, SPECIESDECAY, performMoleculeEfflux, SPONTANEOUS_CLEAVAGE, performSpontaneousCleavage, SPONTANEOUS_CONDENSATION, performSpontaneousCondensation, ENERGYEFFLUX, performEnergyEfflux.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
bool environment::newSpeciesEvaluationIII(acs_longInt tmpNewSpecies, MTRand &tmp___RndDoubleGen)
Evaluate new species (Optimized function with new species reactions update process) 3.0 acs_int tmpNewSpecies New species ID to evaluate MTRand& tmp___RndDoubleGen random number generator
References FINDERRORDURINGRUNTIME, GILLESPIESTUFF, incMolSpeciesProcedure, createDiffusionRenforcement, setSolubility, ExitWithError, HIGH_DEBUG, printAllSpeciesIdAndSequence, RUNNING_VERSION, computeSngSpeciesRctsNumber, SOLUBLE, createReactionsForThisSpecies, NEWREACTIONS, SMALL_DEBUG, acsBufferedFluxes.rctType, getIntRandom, returnSelectionIdFromAWeightProbVector, updateReactions.
Referenced by performCondensation, perform_endo_Condensation, performCleavage, perform_endo_Cleavage, performSpontaneousCleavage, performSpontaneousCondensation.
bool environment::complexEvaluation(string tmpComplex, MTRand &tmp___RndDoubleGen, acs_int tmpCuttingPnt, acs_longInt tmpCatalyst_ID, acs_longInt tmpCatID, acs_longInt tmpSubstrate_ID, acs_longInt tmpSecSub_ID, bool tmpCpxType)
Complex evaluation 1.1 2010-06-04 string tmpNewSpecies New species sequence to evaluate MTRand& tmp___RndDoubleGen random number generator tmpCuttingPnt Complex cutting point tmpCatalyst_ID catalyst ID tmpSubstrate_ID substrate ID tmp_catalysisID catalysis ID tmpCpxType ENDOERGONIC or ESOERGONIC
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, i, incNumberOfCpx, incNumberOfCpxMols, ESOERGONIC, incOverallLoadedMolsCounter, createDiffusionRenforcement, species, SOLUBLE, NOTENERGIZABLE, COMPLEXSTUFF, ExitWithError.
Referenced by performComplexFormation, perform_endo_ComplexFormation.
acs_double environment::computeSinglGilScore(acs_longInt tmpAmountI, acs_double tmpDifI, acs_int tmpSolI, acs_longInt tmpAmountII, acs_double tmpDifII, acs_int tmpSolII, acs_double tmpK, bool tmpSameMol)
Compute a single gillespie score according to the amount and properties of the species involved 1.0 20110214
References FINDERRORDURINGRUNTIME, AVO.
Referenced by performSingleGilleSpieIntroduction.
void environment::performSingleGilleSpieIntroduction(acs_longInt tmpAmountI, acs_longInt tmpAmountII, acs_longInt tmpIDI, acs_longInt tmpIDII, acs_longInt tmpIDCatalysis, acs_int tmp__rctType, acs_longInt tmpMol_I, acs_longInt tmpMol_II, acs_longInt tmpMol_III, acs_longInt tmpMol_IV, acs_int tmpNRGDirection, acs_longInt tmpRctID, bool tmpSameSpeciesControl)
Compute and introduct a single Gillespie entry within the Gillespie Structure 1.0 20110222
References FINDERRORDURINGRUNTIME, CONDENSATION, ENDO_CONDENSATION, CLEAVAGE, ENDO_CLEAVAGE, COMPLEXFORMATION, ENDO_COMPLEXFORMATION, SPONTANEOUS_CONDENSATION, SPONTANEOUS_CLEAVAGE, ExitWithError, computeSinglGilScore, SMALL_DEBUG, printGillespieStructure.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
void environment::changeVolume(acs_int tmpTimeSinceLastReaction)
Change volume function 1.0 2013/07/17 Alessandro Filisetti
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
void environment::incNumberOfSpecies(acs_int tmpID)
Referenced by incMolSpeciesProcedure.
void environment::decNumberOfSpecies(acs_int tmpID)
Referenced by decMolSpeciesProcedure.
void environment::incNumberOfMols()
Referenced by incMolSpeciesProcedure, incMolProcedure.
void environment::decNumberOfMols()
Referenced by decMolSpeciesProcedure.
void environment::incNumberOfCpx()
Referenced by createInitialMoleculesPopulationFromFileSTD, createInitialMoleculesPopulationFromSpecificFileSTD, complexEvaluation.
void environment::decNumberOfCpx(acs_int tmpID)
Referenced by decCpxProcedure.
void environment::incNumberOfCpxMols()
Referenced by complexEvaluation.
void environment::decNumberOfCpxMols()
Referenced by decCpxProcedure.
void environment::incNumberOfNewSpecies(acs_int tmpID)
Referenced by createInitialMoleculesPopulationFromFileSTD, createInitialMoleculesPopulationFromSpecificFileSTD, incMolSpeciesProcedure.
void environment::decNumberOfNewSpecies(acs_int tmpID)
Referenced by decMolSpeciesProcedure.
void environment::incNumberOfNewMols(acs_int tmpID)
Referenced by incMolSpeciesProcedure, incMolProcedure.
void environment::decNumberOfNewMols(acs_int tmpID)
Referenced by decMolSpeciesProcedure.
void environment::decMolSpeciesProcedure(acs_int tmp_ID)
References decNumberOfSpecies, decNumberOfMols, decNumberOfNewSpecies, decNumberOfNewMols.
Referenced by performMoleculeEfflux, performCondensation, perform_endo_Condensation, performCleavage, perform_endo_Cleavage, performComplexFormation, perform_endo_ComplexFormation, performSpontaneousCleavage, performSpontaneousCondensation.
void environment::incMolSpeciesProcedure(acs_int tmp_ID)
References incNumberOfSpecies, incNumberOfMols, incNumberOfNewSpecies, incNumberOfNewMols.
Referenced by performRefill, performCondensation, perform_endo_Condensation, performComplexDissociation, newSpeciesEvaluationIII.
void environment::decCpxProcedure(acs_int tmp_ID)
References decNumberOfCpx, decNumberOfCpxMols.
Referenced by performMoleculeEfflux, performCondensation, perform_endo_Condensation, performComplexDissociation, performSpontaneousCondensation.
void environment::incMolProcedure(acs_int tmp_ID)
References incNumberOfMols, incNumberOfNewMols.
void environment::unchargeMolProcess(acs_int tmp_ID)
References decOverallLoadedMolsCounter.
Referenced by performMoleculeEfflux, perform_endo_Condensation, perform_endo_Cleavage, perform_endo_ComplexFormation, performComplexDissociation.
void environment::incCleavageCounter()
Referenced by performCleavage.
void environment::incEndoCleavageCounter()
Referenced by perform_endo_Cleavage.
void environment::incCondensationCounter()
Referenced by performCondensation.
void environment::incEndoCondensationCounter()
Referenced by perform_endo_Condensation.
void environment::incCpxFormCounter()
Referenced by performComplexFormation, perform_endo_ComplexFormation.
void environment::incCpxDissCounter()
Referenced by performComplexDissociation.
void environment::incOverallLoadedMolsCounter()
Referenced by performDETMoleculesCharging, complexEvaluation.
void environment::decOverallLoadedMolsCounter()
Referenced by performDETMoleculesCharging, unchargeMolProcess.
void environment::incSpontDissCounter()
Referenced by performSpontaneousCleavage.
void environment::incSpontAssCounter()
Referenced by performSpontaneousCondensation.
void environment::resetCleavageCounter()
Referenced by resetReactionsCounter.
void environment::resetEndoCleavageCounter()
Referenced by resetReactionsCounter.
void environment::resetCondensationCounter()
Referenced by resetReactionsCounter.
void environment::resetEndoCondensationCounter()
Referenced by resetReactionsCounter.
void environment::resetOverallLoadedMolsCounter()
Referenced by resetReactionsCounter.
void environment::resetCpxFormCounter()
Referenced by resetReactionsCounter.
void environment::resetCpxDissCounter()
Referenced by resetReactionsCounter.
void environment::resetSpontDissCounter()
Referenced by resetReactionsCounter.
void environment::resetSpontAssCounter()
Referenced by resetReactionsCounter.
void environment::resetReactionsCounter()
References resetCleavageCounter, resetEndoCleavageCounter, resetCondensationCounter, resetEndoCondensationCounter, resetOverallLoadedMolsCounter, resetCpxFormCounter, resetCpxDissCounter, resetSpontDissCounter, resetSpontAssCounter.
Referenced by environment, clearAllStructures, resetConcentrationToInitialConditions.
bool environment::addChargeMolToList(acs_int tmpSpeciesID)
Perform vector unchargedIDlist update adding a new charge molecule vector unchargedIDlist and cumUnchargedAmountList are involved 1.0 2010-10-10 acs_int tmpSpeciesID Specie to charge
References FINDERRORDURINGRUNTIME, ExitWithError.
bool environment::removeChargeMolFromList(acs_int tmpSpeciesID)
Perform vector unchargedIDlist update removing a new charge molecule vectors unchargedIDlist and cumUnchargedAmountList are involved 1.0 2010-10-10 acs_int tmpSpeciesID Specie to uncharge
References FINDERRORDURINGRUNTIME, ExitWithError.
void environment::clearAllStructures()
Clear all structures after each simulation 1.0
References SMALL_DEBUG, getTotalNumberOfSpecies, getTotalNumberOfMolecules, getTotalNumberOfComplexSpecies, getTotalNumberOfComplexes, setActualTime, resetReactionsCounter.
Referenced by main.
void environment::resetConcentrationToInitialConditions()
set the concentrations to the initial values and reset internal statistics and counter 1.0
References RUNNING_VERSION, structureCoherenceCheckUp, ExitWithError, storeInitialStructures, getTotalNumberOfSpecies, getTotalNumberOfMolecules, getTotalNumberOfComplexSpecies, getTotalNumberOfComplexes, setActualTime, resetReactionsCounter.
Referenced by main.
void environment::storeInitialStructures()
Store initial structures into storing variables 1.0
Referenced by resetConcentrationToInitialConditions, main.
bool environment::performRefill(acs_double tmpTimeSinceTheLastInFlux, acs_double tmpMinimalTimeForOneMols, MTRand &tmp__RndDoubleGen)
Perform Refill according to the time interval and the total amount of refill 2.4 2010.06.10 tmpTimeSinceTheLastInFlux time elapsed since the last influx of at least one molcolule tmpMinimalTimeForOneMols time necessary to feed to the system one molecule tmp__RndDoubleGen random number generator
References FINDERRORDURINGRUNTIME, acsround, SMALL_DEBUG, returnSelectionIdFromAWeightProbVectorAlreadyNormalized, HIGH_DEBUG, getTotalNumberOfMolecules, incMolSpeciesProcedure.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
bool environment::performMoleculesEfflux(acs_double tmpTimeInterval, MTRand &tmp_RndDoubleGen)
This function perform the deterministic molecules efflux process 2.5 2010-06-25 tmpTimeInterval time elapsed since the last reaction MTrand &tmp_RndDoubleGen random number generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, getTotalNumberOfMolecules, setLivingSpeciesIDsAndAmounts, ENERGYBASED, i, returnSelectionIdFromAWeightProbVector, performMoleculeEfflux, ExitWithError.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
bool environment::performDETMoleculesCharging(acs_double tmpTimeInterval, MTRand &tmp_RndDoubleGen)
This function perform the pseudo-deterministic molecules charging process 2.6 2011-02-24 tmpTimeInterval time elapsed since the last reaction MTrand &tmp_RndDoubleGen random number generator
References FINDERRORDURINGRUNTIME, ENERGYBASED, setNotChargedAndChargedSpeciesIDsAndAmounts, AVO, j, returnSelectionIdFromAWeightProbVector, ExitWithError, incOverallLoadedMolsCounter, z, decOverallLoadedMolsCounter.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
bool environment::performDETComplexDissociation(acs_double tmpTimeInterval, MTRand &tmp_RndDoubleGen)
This function perform the deterministic dissociation of the complex 1.0 2013-09-18 tmpTimeInterval time elapsed since the last reaction MTrand &tmp_RndDoubleGen random number generator
References FINDERRORDURINGRUNTIME, COMPLEXSTUFF, i, returnSelectionIdFromAWeightProbVector, performComplexDissociation, ExitWithError, z.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
void environment::setActualTime(acs_double tmpActualTime)
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation, clearAllStructures, resetConcentrationToInitialConditions.
void environment::updateSpeciesAges()
Update the species age 1.0
References ExitWithError.
Referenced by main.
void environment::increaseAttempts()
Referenced by main.
bool environment::performCondensation(acs_longInt tmpCatalyst, acs_longInt tmpSubstrate, acs_longInt tmpProduct, acs_longInt tmpComplex, acs_longInt tmpIdReaction, acs_longInt tmpIdCatalysis, MTRand &tmp__RndDoubleGen)
Perform CONDENSATION reaction 1.2 2011-02-12 acs_longInt tmpComplex Complex ID acs_longInt tmpSubstrate Substrate ID acs_longInt tmpProduct Product ID MTRand& tmp__RndDoubleGen random generator
References FINDERRORDURINGRUNTIME, ENERGYBASED, ExitWithError, SMALL_DEBUG, incMolSpeciesProcedure, decMolSpeciesProcedure, decCpxProcedure, newSpeciesEvaluationIII, incCondensationCounter.
Referenced by performReaction.
bool environment::perform_endo_Condensation(acs_longInt tmpCatalyst, acs_longInt tmpSubstrate, acs_longInt tmpProduct, acs_longInt tmpComplex, acs_int tmpNRGside, acs_longInt tmpIdReaction, acs_longInt tmpIdCatalysis, MTRand &tmp__RndDoubleGen)
Perform ENDO CONDENSATION reaction 1.2 2011-02-12 tmpCatalyst Catalyst (bound in the complex) ID tmpSubstrate second (or first, depend on the condensation type) substrate ID tmpProduct product ID acs_longInt tmpComplex Complex ID acs_longInt tmpSubstrate Substrate ID acs_longInt tmpProduct Product ID MTRand& tmp__RndDoubleGen random generator
References FINDERRORDURINGRUNTIME, COMPLEXLOAD, SUBSTRATELOAD, ExitWithError, SMALL_DEBUG, incMolSpeciesProcedure, unchargeMolProcess, decMolSpeciesProcedure, decCpxProcedure, newSpeciesEvaluationIII, incEndoCondensationCounter.
Referenced by performReaction.
bool environment::performCleavage(acs_longInt tmpSubstrate, acs_longInt tmpProduct_I, acs_longInt tmpProduct_II, acs_longInt tmpIdReaction, acs_longInt tmpIdCatalysis, MTRand &tmp__RndDoubleGen)
Perform CLEAVAGE reaction 1.2 2011.02.12 acs_longInt tmpSubstrate Substrate ID acs_longInt tmpProduct_I Product 1 ID acs_longInt tmpProduct_II Product 2 ID tmpIdReaction Rections ID tmpIdCatalysis Catalysis ID MTRand& tmp__RndDoubleGen random number generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, ExitWithError, decMolSpeciesProcedure, newSpeciesEvaluationIII, incCleavageCounter.
Referenced by performReaction.
bool environment::perform_endo_Cleavage(acs_longInt tmpSubstrate, acs_longInt tmpProduct_I, acs_longInt tmpProduct_II, acs_int tmpNRGside, acs_longInt tmpIdReaction, acs_longInt tmpIdCatalysis, MTRand &tmp__RndDoubleGen)
Perform ENDO_CLEAVAGE reaction 1.2 2010.11.08 acs_longInt tmpSubstrate Substrate ID acs_longInt tmpProduct_I Product 1 ID acs_longInt tmpProduct_II Product 2 ID acs_int tmpNrgTarget Energy Target > catalyst loaded, substrate loaded or both tmpIdReaction Rections ID tmpIdCatalysis Catalysis ID MTRand& tmp__RndDoubleGen random number generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, CATALYSTLOAD, ExitWithError, unchargeMolProcess, decMolSpeciesProcedure, SUBSTRATELOAD, newSpeciesEvaluationIII, incEndoCleavageCounter.
Referenced by performReaction.
bool environment::performComplexFormation(acs_longInt tmpCatalyst, acs_longInt tmpSubstrate, acs_longInt tmpCatID, acs_longInt tmpSecSub, MTRand &tmp__RndDoubleGen)
Perform COMPLEX FORMATION reaction 1.2 2011.02.13 acs_longInt tmpCatalyst Catalyst ID acs_longInt tmpSubstrate Substrate ID Catalysis ID MTRand& tmp__RndDoubleGen random generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, ExitWithError, ENDOERGONIC, decMolSpeciesProcedure, COMPLEXSTUFF, complexEvaluation, incCpxFormCounter.
Referenced by performReaction.
bool environment::perform_endo_ComplexFormation(acs_longInt tmpCatalyst, acs_longInt tmpSubstrate, acs_longInt tmpCatID, acs_longInt tmpSecSub, acs_int tmpNRGSide, MTRand &tmp__RndDoubleGen)
Perform ENDO COMPLEX FORMATION reaction 1.2 2011.04.13 acs_longInt tmpCatalyst Catalyst ID acs_longInt tmpSubstrate Substrate ID Catalysis ID MTRand& tmp__RndDoubleGen random generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, ExitWithError, SUBSTRATELOAD, decMolSpeciesProcedure, unchargeMolProcess, CATALYSTLOAD, BOTHLOAD, complexEvaluation, ESOERGONIC, incCpxFormCounter.
Referenced by performReaction.
bool environment::performComplexDissociation(acs_longInt tmpComplex, acs_longInt tmpCatalyst, acs_longInt tmpSubstrate, MTRand &tmp__RndDoubleGen)
Perform COMPLEX DISASSOCIATION reaction 1.1 2010.06.08 acs_longInt tmpComplex Complex ID acs_longInt tmpCatalyst Catalyst ID acs_longInt tmpSubstrate Substrate ID MTRand& tmp__RndDoubleGen random generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, ExitWithError, decCpxProcedure, unchargeMolProcess, incMolSpeciesProcedure, incCpxDissCounter.
Referenced by performDETComplexDissociation, performReaction.
bool environment::performSpontaneousCondensation(acs_longInt tmpReaction, MTRand &tmp__RndDoubleGen)
Perform SPONTANEOUS CONDENSATION reaction 1.0 2013-10-28 acs_longInt tmpReaction Reaction ID MTRand& tmp__RndDoubleGen random generator
References FINDERRORDURINGRUNTIME, ENERGYBASED, ExitWithError, decMolSpeciesProcedure, decCpxProcedure, newSpeciesEvaluationIII, incSpontAssCounter.
Referenced by performReaction.
bool environment::performSpontaneousCleavage(acs_longInt tmpReaction, MTRand &tmp__RndDoubleGen)
Perform SPONTANEOUS CLEAVAGE reaction 1.0 2013.10.28 acs_longInt tmpReaction Reaction ID MTRand& tmp__RndDoubleGen random generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, ExitWithError, decMolSpeciesProcedure, newSpeciesEvaluationIII, incSpontDissCounter.
Referenced by performReaction.
bool environment::performMoleculeEfflux(acs_longInt tmpSpecies, MTRand &tmp__RndDoubleGen)
Perform MOLECULE EFFLUX reaction 2.5.1 2010-06-27 acs_longInt tmpSpecies Species ID MTRand& tmp__RndDoubleGen random generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, ExitWithError, decMolSpeciesProcedure, decCpxProcedure, unchargeMolProcess.
Referenced by performMoleculesEfflux, performReaction.
bool environment::performEnergyEfflux(MTRand &tmp__RndDoubleGen)
Perform ENERGY EFFLUX reaction 2.4.1 2010-06-27 MTRand& tmp__RndDoubleGen random number generator
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, species::getSequence, species::getAmount, species::getChargeMols, species::getNOTchargeMols, ExitWithError, species::decrement, species::unchargeMol.
Referenced by performReaction.
bool environment::structureCoherenceCheckUp()
This function check the coherence of the data structures. IF IT FAULTS THE SYSTEM RETURNS ERROR!!! IT IS VERY RECOMMENDED RUN THIS FUNCTION ALWAYS AFTER THE INITIALIZATION 1.1 2011-04-13
References FINDERRORDURINGRUNTIME, RUNNING_VERSION, getNumberOfTheoreticalSpecies, i, j, SMALL_DEBUG, ExitWithError, PRECIPITATED, getNumberOfReactions, MEDIUM_DEBUG, getNumberOfCatalysis, CLEAVAGE, notInverseReactionAlreadyCatalyzed, CONDENSATION.
Referenced by resetConcentrationToInitialConditions, main.
bool environment::notInverseReactionAlreadyCatalyzed(acs_int tmpRct, acs_longInt tmpID_I, acs_longInt tmpID_II)
Check if the reaction catalyze both one reaction and the inverted one 1.0
References FINDERRORDURINGRUNTIME, CLEAVAGE, CONDENSATION, SMALL_DEBUG, ExitWithError.
Referenced by createReactionsForThisSpecies, updateReactions, structureCoherenceCheckUp.
bool environment::checkIfOnlyMutualCatalysis(acs_int tmpCat, acs_int tmpCandidateProduct)
This function return false if the tmpCandidateProduct is a catalyst of tmpCat 1.0 - last update 2009/10/08 - build 009
References FINDERRORDURINGRUNTIME, i, getNumberOfCatalysis.
bool environment::checkAvailability(acs_longInt tmpMI, acs_longInt tmpMII, acs_longInt tmpQI, acs_longInt tmpQII)
Return TRUE if there are sufficient molecules for the reaction. It is used for the reaction in which catalyst and substrate are the same molecules 1.0 2011.07.25 tmpMI tmpMII tmpQI tmpQII
References HIGH_DEBUG, ExitWithError.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
void environment::inserSubListInSpecies()
Insert substrate reactions information in species if complex 1.0 20130917 Alessandro Filisetti
References FINDERRORDURINGRUNTIME, RUNNING_VERSION, CONDENSATION, SMALL_DEBUG.
Referenced by createInitialCatalysisLayerFromFileSTD, createInitialCatalysisLayerFromSpecificFileSTD.
void environment::showSubListInSpecies()
Function to show the substrates list of the complex species
References FINDERRORDURINGRUNTIME, RUNNING_VERSION, i.
void environment::showGillEngagementInSpecies()
Function to show the Gillespie engagement of each species. : 1.0 : 20131031 : Alessandro Filisetti
References FINDERRORDURINGRUNTIME, RUNNING_VERSION.
Referenced by main.
bool environment::saveConfigurationFileSTD(string tmpStoringPath)
Save a file with the configuration parameters 1.0 2013/07/03
References FINDERRORDURINGRUNTIME, out, ExitWithError, __SOFTVERSION__.
Referenced by saveInitialConditionsToFile.
bool environment::saveInfluxStructureSTD(string tmpStoringPath)
Save influx structure on file, standard C++ bool saveInfluxStructure(QString tmpStoringPath); 1.0 2013-047-03
References FINDERRORDURINGRUNTIME, out, ExitWithError.
Referenced by saveInitialConditionsToFile.
bool environment::saveNrgBoolFncStructureSTD(string tmpStoringPath)
Save Energetic Boolean Function on file, standard C++ bool saveInfluxStructure(QString tmpStoringPath); 1.0 2013-047-03
References FINDERRORDURINGRUNTIME, out, ExitWithError.
Referenced by saveInitialConditionsToFile.
string environment::zeroBeforeStringNumberSTD(acs_int tmpTotN, acs_int tmpCurrentN)
This function creates a chain of zero as STRING according to tmpTotN and tmpCurrent N in order to make possible a sorting (e.g. tmpTotN = 1000, tmpCurrentN = 3, return 0003 1.0 acs_int tmpTotN Total N acs_int tmpCurrentN current N
References i.
Referenced by createInitialMoleculesPopulationFromSpecificFileSTD, createInitialReactionsLayerFromSpecificFileSTD, createInitialCatalysisLayerFromSpecificFileSTD, saveSpeciesStructureSTD, saveReactionsStructureSTD, saveCatalysisStructureSTD, saveTimesSTD, saveReactionsParametersSTD, saveLivingSpeciesIDSTD, saveLivingSpeciesAmountSTD, saveLivingSpeciesConcentrationSTD.
bool environment::saveSpeciesStructureSTD(acs_int tmpCurrentGen, acs_int tmpCurrentSim, acs_int tmpCurrentStep, string tmpStoringPath)
Save the species structures in a file named species_[currentSims]_[currentStep].csv. This is file is equal to the acs_species.csv input file. C++ standard The file is saved in the directory indicated as a second parameter in the run command 1.0 2013/07/03
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, zeroBeforeStringNumberSTD, out, ExitWithError.
Referenced by saveToFile, saveInitialConditionsToFile.
bool environment::saveReactionsStructureSTD(acs_int tmpCurrentGen, acs_int tmpCurrentSim, acs_int tmpCurrentStep, string tmpStoringPath)
Save the reactions structures in a file named reactions_[currentSims]_[currentStep].csv. This is file is equal to the acs_reactions.csv input file. The file is saved in the directory indicated as a second parameter in the run command 1.0
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, zeroBeforeStringNumberSTD, out, ExitWithError.
Referenced by saveToFile, saveInitialConditionsToFile.
bool environment::saveCatalysisStructureSTD(acs_int tmpCurrentGen, acs_int tmpCurrentSim, acs_int tmpCurrentStep, string tmpStoringPath)
Save the catalysis structures in a file named catalysis_[currentSims]_[currentStep].csv. This is file is equal to the acs_catalysis.csv input file. Standard C++ The file is saved in the directory indicated as a second parameter in the run command 1.0
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, zeroBeforeStringNumberSTD, out, ExitWithError.
Referenced by saveToFile, saveInitialConditionsToFile.
bool environment::saveTimesSTD(acs_int tmpCurrentGen, acs_int tmpCurrentSim, acs_int tmpCurrentStep, string tmpStoringPath)
Save the reactions times in a file named times_[currentSim].csv. Standard C++ The file is saved in the directory indicated as a second parameter in the run command 1.0 2013/07/03
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, zeroBeforeStringNumberSTD, out, ExitWithError, getTotalNumberOfSpecies, getTotalNumberOfMolecules, getTotalNumberOfComplexSpecies, getTotalNumberOfComplexes, getTotalNumberOfMonomers.
Referenced by saveTimesToFile.
bool environment::saveReactionsParametersSTD(acs_int tmp__CurrentGen, acs_int tmp__CurrentSim, acs_int tmp__CurrentStep, string tmp__StoringPath, acs_int tmpRctType, acs_longInt tmpCat, acs_longInt tmpMol_I, acs_longInt tmpMol_II, acs_longInt tmpMol_III)
Save the reactions parameters in a file named reactions_parameters_[currentSim].csv. The file is saved in the directory indicated as a second parameter in the run command 1.0 2013/07/03
References FINDERRORDURINGRUNTIME, HIGH_DEBUG, zeroBeforeStringNumberSTD, out, ExitWithError, AVO.
Referenced by performReaction.
bool environment::saveLivingSpeciesIDSTD(acs_int tmp__CurrentGen, acs_int tmp__CurrentSim, acs_int tmp__CurrentStep, string tmp__StoringPath)
Save living species in a file named living_species_[currentSim].csv. Standard C++ The file is saved in the directory indicated as a second parameter in the run command 1.0 2013/07/03
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, zeroBeforeStringNumberSTD, out, ExitWithError, i.
Referenced by performReaction.
bool environment::saveLivingSpeciesAmountSTD(acs_int tmp__CurrentGen, acs_int tmp__CurrentSim, string tmp__StoringPath)
Save living species total AMOUNT in a file named livingAmount_[CurrentGen]_[currentSim].csv. The file is saved in the directory indicated as a second parameter in the run command - Standard C++ 1.0 2013/07/03
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, zeroBeforeStringNumberSTD, out, ExitWithError, i.
Referenced by performReaction.
bool environment::saveLivingSpeciesConcentrationSTD(acs_int tmp__CurrentGen, acs_int tmp__CurrentSim, string tmp__StoringPath)
Save living species total CONCENTRATION in a file named livingAmount_[CurrentGen]_[currentSim].csv. The file is saved in the directory indicated as a second parameter in the run command 1.0 2013/07/03
References FINDERRORDURINGRUNTIME, SMALL_DEBUG, zeroBeforeStringNumberSTD, out, ExitWithError, i.
Referenced by performReaction.
bool environment::devStd()
References FINDERRORDURINGRUNTIME.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.
bool environment::entropy()
References FINDERRORDURINGRUNTIME.
Referenced by performOPTGillespieComputation, perform_FIXED_GillespieComputation.