commonFunctions.cpp
acs_longInt returnSelectionIdFromAWeightProbVector(acs_double *tmpArray, MTRand &tmpRandomGenerator, acs_int tmpRow)
This funtion returns a random position in a probability weight array of N elements.
References acsSCCanalysis.position.
Referenced by environment::performOPTGillespieComputation, environment::performDETComplexDissociation, environment::performDETMoleculesCharging, environment::performMoleculesEfflux, environment::newSpeciesEvaluationIII.
acs_longInt returnSelectionIdFromAWeightProbVector(vector< acs_double > &tmpVector, acs_double tmpMaxValue, MTRand &tmpRandomGenerator, acs_int tmpRow)
Return position of a randomly selected element from a vector containing cumulative values for each element 1.0 vector<acs_double>& tmpVector acs_double MAX VALUE contained within the QList (being a cumulative list this is the last value) MTRand& tmpRandomGenerator
References acsSCCanalysis.position, ExitWithError.
acs_longInt returnSelectionIdFromAWeightProbVectorAlreadyNormalized(vector< acs_double > &tmpVector, MTRand &tmpRandomGenerator)
Return position of a randomly selected element from a normalized vector containing cumulative values for each element 1.0 vector<acs_double>& tmpQList MTRand& tmpRandomGenerator
References acsSCCanalysis.position, ExitWithError.
Referenced by environment::createReactionsForThisSpecies, environment::updateReactions, environment::performRefill.
acs_longInt returnUniformSelection_LONG_IdFromVector(vector< acs_longInt > &tmpVector, MTRand &tmpRandomGenerator)
Return position of a LONG INT randomly selected element from a normalized vector containing cumulative values for each element 1.0 vector<acs_double>& tmpVector MTRand& tmpRandomGenerator
References getIntRandom.
Referenced by environment::createReactionsForThisSpecies, environment::updateReactions.
acs_longInt getIntRandom(acs_longInt tmpFromNum, acs_longInt tmpToNum, MTRand &tmpRandomGenerator)
Referenced by returnUniformSelection_LONG_IdFromVector, environment::createReactionsForThisSpecies, environment::updateReactions, environment::newSpeciesEvaluationIII, species::species.
acs_double getDoubleRandom(acs_double tmpFromNum, acs_double tmpToNum, MTRand &tmpRandomGenerator)
Referenced by species::species.
acs_longInt random_poisson(acs_double tmpLambda, MTRand &tmpRandomGenerator)
Function to return a number from a poisson random distribution
References p, k.
acs_longInt random_binomial(acs_longInt n, acs_double tmpP, MTRand &tmpRandomGenerator)
Function to return a number from a binomial distribution
References k, i.
Referenced by environment::computeSngSpeciesRctsNumber.
acs_double acsround(acs_double tmpX)
Function to round double numbers in integers
Referenced by environment::performRefill, species::concToNum.
string dec2bin(acs_int tmpInt)
Function to convert a decimal number in a binary string composed of 12 bit such Example -> input: 10, binary 1010 > 000000001010
References size, a.
Referenced by environment::performOPTGillespieComputation.
bool ExitWithError(string strFunctionName, string strError)
Function to close the program after having en error
Referenced by catalysis::catalysis, returnSelectionIdFromAWeightProbVector, returnSelectionIdFromAWeightProbVectorAlreadyNormalized, environment::environment, environment::createReactionsForThisSpecies, environment::updateReactions, environment::createInitialMoleculesPopulationFromFileSTD, environment::createInitialMoleculesPopulationFromSpecificFileSTD, environment::structureCoherenceCheckUp, environment::notInverseReactionAlreadyCatalyzed, environment::checkAvailability, environment::performOPTGillespieComputation, environment::performSingleGilleSpieIntroduction, environment::performDETComplexDissociation, environment::performDETMoleculesCharging, environment::removeChargeMolFromList, environment::addChargeMolToList, environment::performMoleculesEfflux, environment::performMoleculeEfflux, environment::performEnergyEfflux, environment::performReaction, environment::performCondensation, environment::perform_endo_Condensation, environment::performCleavage, environment::perform_endo_Cleavage, environment::performComplexFormation, environment::perform_endo_ComplexFormation, environment::performComplexDissociation, environment::performSpontaneousCleavage, environment::performSpontaneousCondensation, environment::newSpeciesEvaluationIII, environment::complexEvaluation, environment::updateSpeciesAges, environment::printInitialCondition, environment::printAllChargeMols, environment::resetConcentrationToInitialConditions, environment::saveConfigurationFileSTD, environment::saveInfluxStructureSTD, environment::saveNrgBoolFncStructureSTD, environment::saveSpeciesStructureSTD, environment::saveReactionsStructureSTD, environment::saveCatalysisStructureSTD, environment::saveTimesSTD, environment::saveReactionsParametersSTD, environment::saveLivingSpeciesIDSTD, environment::saveLivingSpeciesAmountSTD, environment::saveLivingSpeciesConcentrationSTD, main, saveToFile, saveTimesToFile, saveInitialConditionsToFile.
vector<string> split(string str, const char *delim)
Function to split a string and save tokens in a vector
Referenced by environment::environment.
bool fromStrToBool(string const &string)
Function to convert from string to boolean
Referenced by environment::environment.