.TH "/home/ale/Documents/GIT/carness/_analysis/underDevelopment/lib/IO/__init__.py" 3 "Fri Mar 28 2014" "Version 4.8 (20140327.66)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ale/Documents/GIT/carness/_analysis/underDevelopment/lib/IO/__init__.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlib\&.IO\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBlib\&.IO\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBlib\&.IO\&.__all__\fP = ['readfiles', 'writefiles']"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
