.TH "/Users/alessandrofilisetti/Documents/GIT/carness Directory Reference" 3 "Tue Oct 1 2013" "Version 4.7 (20131001.59)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB_analysis\fP"
.br
.ti -1c
.RI "directory \fB_matlabinitializator\fP"
.br
.ti -1c
.RI "directory \fBDebug\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBacs_headers\&.h\fP"
.br
.ti -1c
.RI "file \fBcatalysis\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcatalysis\&.h\fP"
.br
.ti -1c
.RI "file \fBcommonFunctions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcommonFunctions\&.h\fP"
.br
.ti -1c
.RI "file \fBenvironment\&.cpp\fP"
.br
.ti -1c
.RI "file \fBenvironment\&.h\fP"
.br
.ti -1c
.RI "file \fBgillespie\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgillespie\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmtrand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmtrand\&.h\fP"
.br
.ti -1c
.RI "file \fBreactions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBreactions\&.h\fP"
.br
.ti -1c
.RI "file \fBspecies\&.cpp\fP"
.br
.ti -1c
.RI "file \fBspecies\&.h\fP"
.br
.in -1c
