.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator Directory Reference" 3 "Thu Dec 12 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcrea_catalizzatori\&.m\fP"
.br
.ti -1c
.RI "file \fBcrea_concentrazioni_iniziali\&.m\fP"
.br
.ti -1c
.RI "file \fBcrea_e_controlla_i_catalizzatori\&.m\fP"
.br
.ti -1c
.RI "file \fBcrea_firing_disk\&.m\fP"
.br
.ti -1c
.RI "file \fBcrea_influx\&.m\fP"
.br
.ti -1c
.RI "file \fBcrea_influx_semplice\&.m\fP"
.br
.ti -1c
.RI "file \fBcrea_tutte_le_combinazioni_di_elementi\&.m\fP"
.br
.ti -1c
.RI "file \fBinitial_distribution\&.m\fP"
.br
.ti -1c
.RI "file \fBinizializzatore_ACS\&.m\fP"
.br
.ti -1c
.RI "file \fBlancia_acs\&.m\fP"
.br
.ti -1c
.RI "file \fBlancia_inizializzatore_acs\&.m\fP"
.br
.ti -1c
.RI "file \fBstart\&.m\fP"
.br
.in -1c
