.TH "/Users/alessandrofilisetti/Documents/GIT/carness/acs_headers.h" 3 "Thu Dec 12 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/acs_headers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <clocale>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'mtrand\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__SOFTVERSION__\fP   '4\&.8b20131212\&.64'"
.br
.ti -1c
.RI "#define \fBMINIMAL_PROMPT\fP   -1"
.br
.ti -1c
.RI "#define \fBRUNNING_VERSION\fP   0"
.br
.ti -1c
.RI "#define \fBSMALL_DEBUG\fP   1"
.br
.ti -1c
.RI "#define \fBMEDIUM_DEBUG\fP   2"
.br
.ti -1c
.RI "#define \fBHIGH_DEBUG\fP   3"
.br
.ti -1c
.RI "#define \fBFINDERRORDURINGRUNTIME\fP   -10"
.br
.ti -1c
.RI "#define \fBCOMPLEXSTUFF\fP   -20"
.br
.ti -1c
.RI "#define \fBGILLESPIESTUFF\fP   -30"
.br
.ti -1c
.RI "#define \fBRANDOMRANGE\fP   random()"
.br
.ti -1c
.RI "#define \fBPROPORTIONALMOLECULEAMOUNT\fP   1"
.br
.ti -1c
.RI "#define \fBUNIFORMMOLECULEAMOUNT\fP   2"
.br
.ti -1c
.RI "#define \fBINVPROPORTIONALMOLECULEAMOUNT\fP   3"
.br
.ti -1c
.RI "#define \fBCONDENSATION\fP   0"
.br
.ti -1c
.RI "#define \fBCLEAVAGE\fP   1"
.br
.ti -1c
.RI "#define \fBCOMPLEXFORMATION\fP   2"
.br
.ti -1c
.RI "#define \fBCOMPLEXDEGRADATION\fP   3"
.br
.ti -1c
.RI "#define \fBSPECIESDECAY\fP   4"
.br
.ti -1c
.RI "#define \fBPHOSPHORILATION\fP   5"
.br
.ti -1c
.RI "#define \fBENDO_CLEAVAGE\fP   6"
.br
.ti -1c
.RI "#define \fBENDO_CONDENSATION\fP   7"
.br
.ti -1c
.RI "#define \fBENDO_COMPLEXFORMATION\fP   8"
.br
.ti -1c
.RI "#define \fBENERGYEFFLUX\fP   9"
.br
.ti -1c
.RI "#define \fBSPONTANEOUS_CONDENSATION\fP   10"
.br
.ti -1c
.RI "#define \fBSPONTANEOUS_CLEAVAGE\fP   11"
.br
.ti -1c
.RI "#define \fBSOLUBLE\fP   1"
.br
.ti -1c
.RI "#define \fBPRECIPITATED\fP   0"
.br
.ti -1c
.RI "#define \fBESOERGONIC\fP   1"
.br
.ti -1c
.RI "#define \fBENDOERGONIC\fP   0"
.br
.ti -1c
.RI "#define \fBCLEAVAGEBASED\fP   1"
.br
.ti -1c
.RI "#define \fBCONDENSATIONBASED\fP   0"
.br
.ti -1c
.RI "#define \fBENERGYBASED\fP   1"
.br
.ti -1c
.RI "#define \fBENERGYFREE\fP   0"
.br
.ti -1c
.RI "#define \fBTRUENRG\fP   '1'"
.br
.ti -1c
.RI "#define \fBFALSENRG\fP   '0'"
.br
.ti -1c
.RI "#define \fBENERGIZABLE\fP   1"
.br
.ti -1c
.RI "#define \fBNOTENERGIZABLE\fP   0"
.br
.ti -1c
.RI "#define \fBSUBSTRATELOAD\fP   0"
.br
.ti -1c
.RI "#define \fBCATALYSTLOAD\fP   1"
.br
.ti -1c
.RI "#define \fBBOTHLOAD\fP   2"
.br
.ti -1c
.RI "#define \fBCOMPLEXLOAD\fP   3"
.br
.ti -1c
.RI "#define \fBNOTHINGLOAD\fP   4"
.br
.ti -1c
.RI "#define \fBNEWREACTIONS\fP   1"
.br
.ti -1c
.RI "#define \fBUPGRADEREACTIONS\fP   0"
.br
.ti -1c
.RI "#define \fBNOSPONTANEOUS\fP   0"
.br
.ti -1c
.RI "#define \fBNEP\fP   2\&.7182818284590452353602874"
.br
.ti -1c
.RI "#define \fBAVO\fP   6\&.02214179e+23"
.br
.ti -1c
.RI "#define \fBMINIMALRCTTIMEMULTI\fP   100"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef long double \fBacs_double\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBacs_longInt\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBacs_int\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __SOFTVERSION__   '4\&.8b20131212\&.64'"

.PP
Definition at line 42 of file acs_headers\&.h\&.
.SS "#define AVO   6\&.02214179e+23"

.PP
Definition at line 108 of file acs_headers\&.h\&.
.SS "#define BOTHLOAD   2"

.PP
Definition at line 95 of file acs_headers\&.h\&.
.SS "#define CATALYSTLOAD   1"

.PP
Definition at line 94 of file acs_headers\&.h\&.
.SS "#define CLEAVAGE   1"

.PP
Definition at line 65 of file acs_headers\&.h\&.
.SS "#define CLEAVAGEBASED   1"

.PP
Definition at line 84 of file acs_headers\&.h\&.
.SS "#define COMPLEXDEGRADATION   3"

.PP
Definition at line 67 of file acs_headers\&.h\&.
.SS "#define COMPLEXFORMATION   2"

.PP
Definition at line 66 of file acs_headers\&.h\&.
.SS "#define COMPLEXLOAD   3"

.PP
Definition at line 96 of file acs_headers\&.h\&.
.SS "#define COMPLEXSTUFF   -20"

.PP
Definition at line 52 of file acs_headers\&.h\&.
.SS "#define CONDENSATION   0"

.PP
Definition at line 64 of file acs_headers\&.h\&.
.SS "#define CONDENSATIONBASED   0"

.PP
Definition at line 85 of file acs_headers\&.h\&.
.SS "#define ENDO_CLEAVAGE   6"

.PP
Definition at line 70 of file acs_headers\&.h\&.
.SS "#define ENDO_COMPLEXFORMATION   8"

.PP
Definition at line 72 of file acs_headers\&.h\&.
.SS "#define ENDO_CONDENSATION   7"

.PP
Definition at line 71 of file acs_headers\&.h\&.
.SS "#define ENDOERGONIC   0"

.PP
Definition at line 83 of file acs_headers\&.h\&.
.SS "#define ENERGIZABLE   1"

.PP
Definition at line 90 of file acs_headers\&.h\&.
.SS "#define ENERGYBASED   1"

.PP
Definition at line 86 of file acs_headers\&.h\&.
.SS "#define ENERGYEFFLUX   9"

.PP
Definition at line 73 of file acs_headers\&.h\&.
.SS "#define ENERGYFREE   0"

.PP
Definition at line 87 of file acs_headers\&.h\&.
.SS "#define ESOERGONIC   1"

.PP
Definition at line 82 of file acs_headers\&.h\&.
.SS "#define FALSENRG   '0'"

.PP
Definition at line 89 of file acs_headers\&.h\&.
.SS "#define FINDERRORDURINGRUNTIME   -10"

.PP
Definition at line 51 of file acs_headers\&.h\&.
.SS "#define GILLESPIESTUFF   -30"

.PP
Definition at line 53 of file acs_headers\&.h\&.
.SS "#define HIGH_DEBUG   3"

.PP
Definition at line 50 of file acs_headers\&.h\&.
.SS "#define INVPROPORTIONALMOLECULEAMOUNT   3"

.PP
Definition at line 61 of file acs_headers\&.h\&.
.SS "#define MEDIUM_DEBUG   2"

.PP
Definition at line 49 of file acs_headers\&.h\&.
.SS "#define MINIMAL_PROMPT   -1"

.PP
Definition at line 46 of file acs_headers\&.h\&.
.SS "#define MINIMALRCTTIMEMULTI   100"

.PP
Definition at line 111 of file acs_headers\&.h\&.
.SS "#define NEP   2\&.7182818284590452353602874"

.PP
Definition at line 107 of file acs_headers\&.h\&.
.SS "#define NEWREACTIONS   1"

.PP
Definition at line 100 of file acs_headers\&.h\&.
.SS "#define NOSPONTANEOUS   0"

.PP
Definition at line 104 of file acs_headers\&.h\&.
.SS "#define NOTENERGIZABLE   0"

.PP
Definition at line 91 of file acs_headers\&.h\&.
.SS "#define NOTHINGLOAD   4"

.PP
Definition at line 97 of file acs_headers\&.h\&.
.SS "#define PHOSPHORILATION   5"

.PP
Definition at line 69 of file acs_headers\&.h\&.
.SS "#define PRECIPITATED   0"

.PP
Definition at line 79 of file acs_headers\&.h\&.
.SS "#define PROPORTIONALMOLECULEAMOUNT   1"

.PP
Definition at line 59 of file acs_headers\&.h\&.
.SS "#define RANDOMRANGE   random()"

.PP
Definition at line 56 of file acs_headers\&.h\&.
.SS "#define RUNNING_VERSION   0"

.PP
Definition at line 47 of file acs_headers\&.h\&.
.SS "#define SMALL_DEBUG   1"

.PP
Definition at line 48 of file acs_headers\&.h\&.
.SS "#define SOLUBLE   1"

.PP
Definition at line 78 of file acs_headers\&.h\&.
.SS "#define SPECIESDECAY   4"

.PP
Definition at line 68 of file acs_headers\&.h\&.
.SS "#define SPONTANEOUS_CLEAVAGE   11"

.PP
Definition at line 75 of file acs_headers\&.h\&.
.SS "#define SPONTANEOUS_CONDENSATION   10"

.PP
Definition at line 74 of file acs_headers\&.h\&.
.SS "#define SUBSTRATELOAD   0"

.PP
Definition at line 93 of file acs_headers\&.h\&.
.SS "#define TRUENRG   '1'"

.PP
Definition at line 88 of file acs_headers\&.h\&.
.SS "#define UNIFORMMOLECULEAMOUNT   2"

.PP
Definition at line 60 of file acs_headers\&.h\&.
.SS "#define UPGRADEREACTIONS   0"

.PP
Definition at line 101 of file acs_headers\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef long double \fBacs_double\fP"

.PP
Definition at line 34 of file acs_headers\&.h\&.
.SS "typedef unsigned int \fBacs_int\fP"

.PP
Definition at line 36 of file acs_headers\&.h\&.
.SS "typedef unsigned long int \fBacs_longInt\fP"

.PP
Definition at line 35 of file acs_headers\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
