.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/underDevelopment/acsAttractorAnalysisInTime.py" 3 "Tue Dec 10 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/underDevelopment/acsAttractorAnalysisInTime.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBacsAttractorAnalysisInTime\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBacsAttractorAnalysisInTime\&.zeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.StrPath\fP = os\&.path\&.abspath(StrPath)"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.today\fP = dt\&.date\&.today()"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.tmpDirs\fP = sort(os\&.listdir(StrPath))"
.br
.ti -1c
.RI "list \fBacsAttractorAnalysisInTime\&.allSortedSpecies\fP = []"
.br
.ti -1c
.RI "list \fBacsAttractorAnalysisInTime\&.allConcentrations\fP = []"
.br
.ti -1c
.RI "list \fBacsAttractorAnalysisInTime\&.allSortedSpeciesNOINFLUX\fP = []"
.br
.ti -1c
.RI "list \fBacsAttractorAnalysisInTime\&.allConcentrationsNOINFLUX\fP = []"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.totDirName\fP = os\&.path\&.join(StrPath,tmpDir)"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.resDirPath\fP = os\&.path\&.abspath(os\&.path\&.join('\&./', 'res'))"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.numberOfGen\fP = len(glob\&.glob(os\&.path\&.join(resDirPath,'times_*')))"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.strZeros\fP = zeroBeforeStrNum(ngen, numberOfGen)"
.br
.ti -1c
.RI "string \fBacsAttractorAnalysisInTime\&.strSpeciesZero\fP = 'species_'"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.speciesFilesZero\fP = sorted(glob\&.glob(os\&.path\&.join(resDirPath,strSpeciesZero)))"
.br
.ti -1c
.RI "string \fBacsAttractorAnalysisInTime\&.strSpecies\fP = 'species_'"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.speciesFiles\fP = sorted(glob\&.glob(os\&.path\&.join(resDirPath,strSpecies)))"
.br
.ti -1c
.RI "list \fBacsAttractorAnalysisInTime\&.speciesFile\fP = \fBspeciesFiles\fP[timeFileID]"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.fidSpecies\fP = open(\fBspeciesFile\fP, '\fBr\fP')"
.br
.ti -1c
.RI "list \fBacsAttractorAnalysisInTime\&.seq\fP = []"
.br
.ti -1c
.RI "list \fBacsAttractorAnalysisInTime\&.overallConcList\fP = []"
.br
.ti -1c
.RI "list \fBacsAttractorAnalysisInTime\&.overallConcListNOINFLUX\fP = []"
.br
.ti -1c
.RI "int \fBacsAttractorAnalysisInTime\&.numberOfFolders\fP = 0"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.pos\fP = \fBseq\&.index\fP(key)"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.pos2\fP = \fBseq\&.index\fP(key2)"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.ANG_overallResMatrix\fP = np\&.zeros((numberOfFolders,numberOfFolders))"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.ANG_overallResMatrixNOINFLUX\fP = np\&.zeros((numberOfFolders,numberOfFolders))"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.HAM_overallResMatrix\fP = np\&.zeros((numberOfFolders,numberOfFolders))"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.HAM_overallResMatrixNOINFLUX\fP = np\&.zeros((numberOfFolders,numberOfFolders))"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.EUC_overallResMatrix\fP = np\&.zeros((numberOfFolders,numberOfFolders))"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.EUC_overallResMatrixNOINFLUX\fP = np\&.zeros((numberOfFolders,numberOfFolders))"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.vecX\fP = np\&.array(lx)"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.vecY\fP = np\&.array(ly)"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.tmpCos\fP = float(np\&.dot(vecX,vecY) / (np\&.linalg\&.norm(vecX) * np\&.linalg\&.norm(vecY)))"
.br
.ti -1c
.RI "int \fBacsAttractorAnalysisInTime\&.tmpHD\fP = 0"
.br
.ti -1c
.RI "int \fBacsAttractorAnalysisInTime\&.tmpEU\fP = 0"
.br
.ti -1c
.RI "string \fBacsAttractorAnalysisInTime\&.ndn\fP = '_0_new_allStatResults'"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.newdirAllResults\fP = os\&.path\&.join(os\&.curdir, ndn)"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.tmpZeroSaving\fP = zeroBeforeStrNum(timeFileID, tmpNOF)"
.br
.ti -1c
.RI "string \fBacsAttractorAnalysisInTime\&.outFnameStat\fP = 'speciesVector'"
.br
.ti -1c
.RI "tuple \fBacsAttractorAnalysisInTime\&.saveFileStat\fP = open(outFnameStat, 'w')"
.br
.ti -1c
.RI "string \fBacsAttractorAnalysisInTime\&.strTypes\fP = ''"
.br
.ti -1c
.RI "int \fBacsAttractorAnalysisInTime\&.cnt\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
