.TH "acsBufferedFluxes" 3 "Fri Mar 28 2014" "Version 4.8 (20140327.66)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acsBufferedFluxes \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBparser\fP"
.br
.ti -1c
.RI "tuple \fBargs\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "tuple \fBstrPath\fP = os\&.path\&.abspath(args\&.strPath)"
.br
.ti -1c
.RI "tuple \fBtmpDirs\fP = sort(os\&.listdir(StrPath))"
.br
.ti -1c
.RI "int \fB_CONDENSATION_\fP = 0"
.br
.ti -1c
.RI "int \fB_CLEAVAGE_\fP = 1"
.br
.ti -1c
.RI "int \fB_ENDOCONDENSATION_\fP = 7"
.br
.ti -1c
.RI "int \fB_ENDOCLEAVAGE_\fP = 6"
.br
.ti -1c
.RI "int \fB_SPONTCONDENSATION_\fP = 10"
.br
.ti -1c
.RI "int \fB_SPONTCLEAVAGE_\fP = 11"
.br
.ti -1c
.RI "int \fBchemistry\fP = 1"
.br
.ti -1c
.RI "string \fBndn\fP = '_0_new_allStatResults'"
.br
.ti -1c
.RI "tuple \fBnewdirAllResults\fP = os\&.path\&.join(StrPath, \fBndn\fP)"
.br
.ti -1c
.RI "tuple \fBtotDirName\fP = os\&.path\&.join(StrPath,tmpDir)"
.br
.ti -1c
.RI "tuple \fBresDirPath\fP = os\&.path\&.abspath(os\&.path\&.join('\&./', 'res'))"
.br
.ti -1c
.RI "tuple \fBnumberOfGen\fP = len(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,'times_*')))"
.br
.ti -1c
.RI "string \fBtmpFluxFile\fP = 'fluxDynamics_'"
.br
.ti -1c
.RI "tuple \fBtmpSpeciesStatsSummaryNameFID\fP = open(\fBtmpFluxFile\fP, 'w')"
.br
.ti -1c
.RI "tuple \fBstrZeros\fP = \fBzeroBeforeStrNum\fP(ngen, \fBnumberOfGen\fP)"
.br
.ti -1c
.RI "string \fBstrSpeciesZero\fP = 'species_'"
.br
.ti -1c
.RI "tuple \fBspeciesFilesZero\fP = sorted(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,\fBstrSpeciesZero\fP)))"
.br
.ti -1c
.RI "string \fBstrSpecies\fP = 'species_'"
.br
.ti -1c
.RI "tuple \fBspeciesFiles\fP = sorted(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,\fBstrSpecies\fP)))"
.br
.ti -1c
.RI "list \fBlastfilespecies\fP = \fBspeciesFiles\fP[-1]"
.br
.ti -1c
.RI "tuple \fBfidSpecies\fP = open(\fBlastfilespecies\fP, '\fBr\fP')"
.br
.ti -1c
.RI "list \fBflux_seq\fP = []"
.br
.ti -1c
.RI "tuple \fBcounters\fP = np\&.zeros((nSpecies,(len(seq)*2)+7))"
.br
.ti -1c
.RI "string \fBstrRctPar\fP = 'reactions_parameters_'"
.br
.ti -1c
.RI "tuple \fBfidRctPar\fP = open(\fBstrRctPar\fP, '\fBr\fP')"
.br
.ti -1c
.RI "int \fBtotIN\fP = 0"
.br
.ti -1c
.RI "int \fBtotOUT\fP = 0"
.br
.ti -1c
.RI "int \fBdeltaIO\fP = 0"
.br
.ti -1c
.RI "int \fBtotBIN\fP = 0"
.br
.ti -1c
.RI "int \fBtotBOUT\fP = 0"
.br
.ti -1c
.RI "tuple \fBrctTime\fP = int(tmpRctT)"
.br
.ti -1c
.RI "tuple \fBrctType\fP = int(tmpRctType)"
.br
.ti -1c
.RI "tuple \fBcat\fP = int(tmpCat)"
.br
.ti -1c
.RI "tuple \fBS1\fP = int(tmpS1)"
.br
.ti -1c
.RI "tuple \fBS2\fP = int(tmpS2)"
.br
.ti -1c
.RI "tuple \fBS3\fP = int(tmpS3)"
.br
.ti -1c
.RI "string \fBtmpFileName\fP = 'speciesStats_'"
.br
.ti -1c
.RI "tuple \fBtmpFileNameFID\fP = open(\fBtmpFileName\fP, 'w')"
.br
.ti -1c
.RI "int \fBID\fP = 0"
.br
.ti -1c
.RI "string \fBtmpStr\fP = 'Total Number of Reactions\\t\\t\\t\\t'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def acsBufferedFluxes\&.zeroBeforeStrNum (tmpl, tmpL)"

.PP
Definition at line 20 of file acsBufferedFluxes\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "int acsBufferedFluxes\&._CLEAVAGE_ = 1"

.PP
Definition at line 42 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&._CONDENSATION_ = 0"

.PP
Definition at line 41 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&._ENDOCLEAVAGE_ = 6"

.PP
Definition at line 44 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&._ENDOCONDENSATION_ = 7"

.PP
Definition at line 43 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&._SPONTCLEAVAGE_ = 11"

.PP
Definition at line 46 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&._SPONTCONDENSATION_ = 10"

.PP
Definition at line 45 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.args = parser\&.parse_args()"

.PP
Definition at line 34 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.cat = int(tmpCat)"

.PP
Definition at line 133 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&.chemistry = 1"

.PP
Definition at line 50 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.counters = np\&.zeros((nSpecies,(len(seq)*2)+7))"

.PP
Definition at line 111 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&.deltaIO = 0"

.PP
Definition at line 123 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.fidRctPar = open(\fBstrRctPar\fP, '\fBr\fP')"

.PP
Definition at line 117 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.fidSpecies = open(\fBlastfilespecies\fP, '\fBr\fP')"

.PP
Definition at line 96 of file acsBufferedFluxes\&.py\&.
.SS "list acsBufferedFluxes\&.flux_seq = []"

.PP
Definition at line 100 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&.ID = 0"

.PP
Definition at line 169 of file acsBufferedFluxes\&.py\&.
.SS "list acsBufferedFluxes\&.lastfilespecies = \fBspeciesFiles\fP[-1]"

.PP
Definition at line 92 of file acsBufferedFluxes\&.py\&.
.SS "string acsBufferedFluxes\&.ndn = '_0_new_allStatResults'"

.PP
Definition at line 53 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.newdirAllResults = os\&.path\&.join(StrPath, \fBndn\fP)"

.PP
Definition at line 54 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.numberOfGen = len(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,'times_*')))"

.PP
Definition at line 73 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.parser"
\fBInitial value:\fP
.PP
.nf
1 = ArgumentParser(
2                                 description='This script characterize the buffered flux dynamics\&.'
3                                 , epilog='''Buffered flux dynamics\&. ''')
.fi
.PP
Definition at line 30 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.rctTime = int(tmpRctT)"

.PP
Definition at line 131 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.rctType = int(tmpRctType)"

.PP
Definition at line 132 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.resDirPath = os\&.path\&.abspath(os\&.path\&.join('\&./', 'res'))"

.PP
Definition at line 67 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.S1 = int(tmpS1)"

.PP
Definition at line 134 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.S2 = int(tmpS2)"

.PP
Definition at line 135 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.S3 = int(tmpS3)"

.PP
Definition at line 136 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.speciesFiles = sorted(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,\fBstrSpecies\fP)))"

.PP
Definition at line 89 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.speciesFilesZero = sorted(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,\fBstrSpeciesZero\fP)))"

.PP
Definition at line 84 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.strPath = os\&.path\&.abspath(args\&.strPath)"

.PP
Definition at line 37 of file acsBufferedFluxes\&.py\&.
.SS "string acsBufferedFluxes\&.strRctPar = 'reactions_parameters_'"

.PP
Definition at line 113 of file acsBufferedFluxes\&.py\&.
.SS "string acsBufferedFluxes\&.strSpecies = 'species_'"

.PP
Definition at line 86 of file acsBufferedFluxes\&.py\&.
.SS "string acsBufferedFluxes\&.strSpeciesZero = 'species_'"

.PP
Definition at line 83 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.strZeros = \fBzeroBeforeStrNum\fP(ngen, \fBnumberOfGen\fP)"

.PP
Definition at line 81 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.tmpDirs = sort(os\&.listdir(StrPath))"

.PP
Definition at line 38 of file acsBufferedFluxes\&.py\&.
.SS "string acsBufferedFluxes\&.tmpFileName = 'speciesStats_'"

.PP
Definition at line 166 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.tmpFileNameFID = open(\fBtmpFileName\fP, 'w')"

.PP
Definition at line 168 of file acsBufferedFluxes\&.py\&.
.SS "string acsBufferedFluxes\&.tmpFluxFile = 'fluxDynamics_'"

.PP
Definition at line 78 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.tmpSpeciesStatsSummaryNameFID = open(\fBtmpFluxFile\fP, 'w')"

.PP
Definition at line 79 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.tmpStr = 'Total Number of Reactions\\t\\t\\t\\t'"

.PP
Definition at line 170 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&.totBIN = 0"

.PP
Definition at line 124 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&.totBOUT = 0"

.PP
Definition at line 125 of file acsBufferedFluxes\&.py\&.
.SS "tuple acsBufferedFluxes\&.totDirName = os\&.path\&.join(StrPath,tmpDir)"

.PP
Definition at line 63 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&.totIN = 0"

.PP
Definition at line 121 of file acsBufferedFluxes\&.py\&.
.SS "int acsBufferedFluxes\&.totOUT = 0"

.PP
Definition at line 122 of file acsBufferedFluxes\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
