.TH "/home/ale/Documents/GIT/carness/_analysis/underDevelopment/acsDynStatInTime.py" 3 "Fri Mar 28 2014" "Version 4.8 (20140327.66)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ale/Documents/GIT/carness/_analysis/underDevelopment/acsDynStatInTime.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBacsDynStatInTime\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBacsDynStatInTime\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBacsDynStatInTime\&.parser\fP"
.br
.ti -1c
.RI "tuple \fBacsDynStatInTime\&.args\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "tuple \fBacsDynStatInTime\&.strPath\fP = os\&.path\&.abspath(args\&.strPath)"
.br
.ti -1c
.RI "string \fBacsDynStatInTime\&.strSubStrKey\fP = '*'"
.br
.ti -1c
.RI "tuple \fBacsDynStatInTime\&.filesToAnal\fP = sorted(glob\&.glob(os\&.path\&.join(strPath,strSubStrKey)))"
.br
.ti -1c
.RI "tuple \fBacsDynStatInTime\&.lenFilesToAnal\fP = len(filesToAnal)"
.br
.ti -1c
.RI "int \fBacsDynStatInTime\&.numOfTraj\fP = 0"
.br
.ti -1c
.RI "tuple \fBacsDynStatInTime\&.x\fP = np\&.array(map(list, np\&.loadtxt(fileToAnal, str)), float)"
.br
.ti -1c
.RI "\fBacsDynStatInTime\&.xsize\fP = x\&.shape"
.br
.ti -1c
.RI "list \fBacsDynStatInTime\&.run4Chem\fP = xsize[0]"
.br
.ti -1c
.RI "tuple \fBacsDynStatInTime\&.y\fP = np\&.zeros((lenFilesToAnal,numOfTraj))"
.br
.ti -1c
.RI "int \fBacsDynStatInTime\&.pos\fP = 0"
.br
.ti -1c
.RI "int \fBacsDynStatInTime\&.chem\fP = 1"
.br
.ti -1c
.RI "string \fBacsDynStatInTime\&.tmpHead\fP = ''"
.br
.ti -1c
.RI "string \fBacsDynStatInTime\&.filename\fP = '_arranged_'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
