.TH "acsDynStatInTime" 3 "Tue Dec 10 2013" "Version 4.8 (20131209.62)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acsDynStatInTime \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBparser\fP"
.br
.ti -1c
.RI "tuple \fBargs\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "tuple \fBstrPath\fP = os\&.path\&.abspath(args\&.strPath)"
.br
.ti -1c
.RI "string \fBstrSubStrKey\fP = '*'"
.br
.ti -1c
.RI "tuple \fBfilesToAnal\fP = sorted(glob\&.glob(os\&.path\&.join(\fBstrPath\fP,\fBstrSubStrKey\fP)))"
.br
.ti -1c
.RI "tuple \fBlenFilesToAnal\fP = len(\fBfilesToAnal\fP)"
.br
.ti -1c
.RI "int \fBnumOfTraj\fP = 0"
.br
.ti -1c
.RI "tuple \fBx\fP = np\&.array(map(list, np\&.loadtxt(fileToAnal, str)), float)"
.br
.ti -1c
.RI "\fBxsize\fP = x\&.shape"
.br
.ti -1c
.RI "list \fBrun4Chem\fP = \fBxsize\fP[0]"
.br
.ti -1c
.RI "tuple \fBy\fP = np\&.zeros((\fBlenFilesToAnal\fP,\fBnumOfTraj\fP))"
.br
.ti -1c
.RI "int \fBpos\fP = 0"
.br
.ti -1c
.RI "int \fBchem\fP = 1"
.br
.ti -1c
.RI "string \fBtmpHead\fP = ''"
.br
.ti -1c
.RI "string \fBfilename\fP = '_arranged_'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple acsDynStatInTime\&.args = parser\&.parse_args()"

.PP
Definition at line 24 of file acsDynStatInTime\&.py\&.
.SS "int acsDynStatInTime\&.chem = 1"

.PP
Definition at line 47 of file acsDynStatInTime\&.py\&.
.SS "string acsDynStatInTime\&.filename = '_arranged_'"

.PP
Definition at line 66 of file acsDynStatInTime\&.py\&.
.SS "tuple acsDynStatInTime\&.filesToAnal = sorted(glob\&.glob(os\&.path\&.join(\fBstrPath\fP,\fBstrSubStrKey\fP)))"

.PP
Definition at line 34 of file acsDynStatInTime\&.py\&.
.SS "tuple acsDynStatInTime\&.lenFilesToAnal = len(\fBfilesToAnal\fP)"

.PP
Definition at line 35 of file acsDynStatInTime\&.py\&.
.SS "tuple acsDynStatInTime\&.numOfTraj = 0"

.PP
Definition at line 36 of file acsDynStatInTime\&.py\&.
.SS "tuple acsDynStatInTime\&.parser"
\fBInitial value:\fP
.PP
.nf
1 = ArgumentParser(
2                                 description='This script re-arrange results in a more friendly way from the angle analysis in time\&.'
3                                 , epilog='''File with angle trajectories are created\&. ''')
.fi
.PP
Definition at line 17 of file acsDynStatInTime\&.py\&.
.SS "int acsDynStatInTime\&.pos = 0"

.PP
Definition at line 46 of file acsDynStatInTime\&.py\&.
.SS "list acsDynStatInTime\&.run4Chem = \fBxsize\fP[0]"

.PP
Definition at line 42 of file acsDynStatInTime\&.py\&.
.SS "tuple acsDynStatInTime\&.strPath = os\&.path\&.abspath(args\&.strPath)"

.PP
Definition at line 27 of file acsDynStatInTime\&.py\&.
.SS "string acsDynStatInTime\&.strSubStrKey = '*'"

.PP
Definition at line 33 of file acsDynStatInTime\&.py\&.
.SS "string acsDynStatInTime\&.tmpHead = ''"

.PP
Definition at line 48 of file acsDynStatInTime\&.py\&.
.SS "tuple acsDynStatInTime\&.x = np\&.array(map(list, np\&.loadtxt(fileToAnal, str)), float)"

.PP
Definition at line 39 of file acsDynStatInTime\&.py\&.
.SS "acsDynStatInTime\&.xsize = x\&.shape"

.PP
Definition at line 40 of file acsDynStatInTime\&.py\&.
.SS "tuple acsDynStatInTime\&.y = np\&.zeros((\fBlenFilesToAnal\fP,\fBnumOfTraj\fP))"

.PP
Definition at line 44 of file acsDynStatInTime\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
