.TH "acsFromWim2Carness" 3 "Tue Dec 10 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acsFromWim2Carness \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBparser\fP"
.br
.ti -1c
.RI "tuple \fBargs\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "string \fBndn\fP = '_0_new_allStatResults'"
.br
.ti -1c
.RI "tuple \fBnewdirAllResults\fP = os\&.path\&.join(args\&.strOut, \fBndn\fP)"
.br
.ti -1c
.RI "tuple \fBfname_initRafRes\fP = os\&.path\&.join(\fBnewdirAllResults\fP, '0_initRafAnalysis\&.csv')"
.br
.ti -1c
.RI "tuple \fBfname_initRafResLIST\fP = os\&.path\&.join(\fBnewdirAllResults\fP, '0_initRafAnalysisLIST\&.csv')"
.br
.ti -1c
.RI "tuple \fBfname_initRafResALL\fP = os\&.path\&.join(\fBnewdirAllResults\fP, '0_initRafAnalysisALL\&.csv')"
.br
.ti -1c
.RI "tuple \fBfid_initRafRes\fP = open(\fBfname_initRafRes\fP, 'w')"
.br
.ti -1c
.RI "tuple \fBfid_initRafResLIST\fP = open(\fBfname_initRafResLIST\fP, 'w')"
.br
.ti -1c
.RI "tuple \fBfid_initRafResALL\fP = open(\fBfname_initRafResALL\fP, 'w')"
.br
.ti -1c
.RI "string \fBstrToWrite\fP = 'Folder\\tP\\tAC\\tM\\tRAFsize\\tClosure\\tCats\\tuRAF\\n'"
.br
.ti -1c
.RI "tuple \fBf\fP = open(args\&.wimFile)"
.br
.ti -1c
.RI "tuple \fBlines\fP = f\&.readlines()"
.br
.ti -1c
.RI "int \fBprocedure\fP = 0"
.br
.ti -1c
.RI "list \fBspeciesList\fP = []"
.br
.ti -1c
.RI "list \fBfoodList\fP = []"
.br
.ti -1c
.RI "int \fBrct\fP = 0"
.br
.ti -1c
.RI "tuple \fBl\fP = \fBline\&.split\fP()"
.br
.ti -1c
.RI "tuple \fBcatNums\fP = len(\fBl\fP)"
.br
.ti -1c
.RI "tuple \fBcats\fP = np\&.vstack([cats,(int(\fBrct\fP), int(\fBspeciesList\&.index\fP(\fBl\fP[6+\fBcatNums\fP-1][0:len(\fBl\fP[6+\fBcatNums\fP-1])-1])), int(\fBrct\fP), int(0), int(5), int(25), int(5), int(1))])"
.br
.ti -1c
.RI "tuple \fBrafsets\fP = raf\&.rafComputation(\fBfid_initRafRes\fP, \fBfid_initRafResALL\fP, \fBfid_initRafResLIST\fP, 'tmpDir', 0, \fBrct\fP/float(len(\fBspeciesList\fP)), rcts, \fBcats\fP, \fBfoodList\fP, 10)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple acsFromWim2Carness\&.args = parser\&.parse_args()"

.PP
Definition at line 33 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.catNums = len(\fBl\fP)"

.PP
Definition at line 100 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.cats = np\&.vstack([cats,(int(\fBrct\fP), int(\fBspeciesList\&.index\fP(\fBl\fP[6+\fBcatNums\fP-1][0:len(\fBl\fP[6+\fBcatNums\fP-1])-1])), int(\fBrct\fP), int(0), int(5), int(25), int(5), int(1))])"

.PP
Definition at line 110 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.f = open(args\&.wimFile)"

.PP
Definition at line 54 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.fid_initRafRes = open(\fBfname_initRafRes\fP, 'w')"

.PP
Definition at line 48 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.fid_initRafResALL = open(\fBfname_initRafResALL\fP, 'w')"

.PP
Definition at line 50 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.fid_initRafResLIST = open(\fBfname_initRafResLIST\fP, 'w')"

.PP
Definition at line 49 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.fname_initRafRes = os\&.path\&.join(\fBnewdirAllResults\fP, '0_initRafAnalysis\&.csv')"

.PP
Definition at line 45 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.fname_initRafResALL = os\&.path\&.join(\fBnewdirAllResults\fP, '0_initRafAnalysisALL\&.csv')"

.PP
Definition at line 47 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.fname_initRafResLIST = os\&.path\&.join(\fBnewdirAllResults\fP, '0_initRafAnalysisLIST\&.csv')"

.PP
Definition at line 46 of file acsFromWim2Carness\&.py\&.
.SS "list acsFromWim2Carness\&.foodList = []"

.PP
Definition at line 58 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.l = \fBline\&.split\fP()"

.PP
Definition at line 74 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.lines = f\&.readlines()"

.PP
Definition at line 55 of file acsFromWim2Carness\&.py\&.
.SS "string acsFromWim2Carness\&.ndn = '_0_new_allStatResults'"

.PP
Definition at line 36 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.newdirAllResults = os\&.path\&.join(args\&.strOut, \fBndn\fP)"

.PP
Definition at line 37 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.parser"
\fBInitial value:\fP
.PP
.nf
1 = ArgumentParser(
2                                 description='From WIM format to my format'
3                                 , epilog='''From WIM format to my format\&. ''')
.fi
.PP
Definition at line 26 of file acsFromWim2Carness\&.py\&.
.SS "int acsFromWim2Carness\&.procedure = 0"

.PP
Definition at line 56 of file acsFromWim2Carness\&.py\&.
.SS "tuple acsFromWim2Carness\&.rafsets = raf\&.rafComputation(\fBfid_initRafRes\fP, \fBfid_initRafResALL\fP, \fBfid_initRafResLIST\fP, 'tmpDir', 0, \fBrct\fP/float(len(\fBspeciesList\fP)), rcts, \fBcats\fP, \fBfoodList\fP, 10)"

.PP
Definition at line 116 of file acsFromWim2Carness\&.py\&.
.SS "int acsFromWim2Carness\&.rct = 0"

.PP
Definition at line 59 of file acsFromWim2Carness\&.py\&.
.SS "list acsFromWim2Carness\&.speciesList = []"

.PP
Definition at line 57 of file acsFromWim2Carness\&.py\&.
.SS "string acsFromWim2Carness\&.strToWrite = 'Folder\\tP\\tAC\\tM\\tRAFsize\\tClosure\\tCats\\tuRAF\\n'"

.PP
Definition at line 51 of file acsFromWim2Carness\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
