.TH "acsRAFanalysis" 3 "Thu Dec 12 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acsRAFanalysis \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBparser\fP"
.br
.ti -1c
.RI "tuple \fBargs\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "tuple \fBstrPath\fP = os\&.path\&.abspath(args\&.strPath)"
.br
.ti -1c
.RI "int \fB_CLOSE_\fP = 0"
.br
.ti -1c
.RI "int \fB_PROTO_\fP = 1"
.br
.ti -1c
.RI "int \fB_CSTR_\fP = 2"
.br
.ti -1c
.RI "tuple \fBconf\fP = rf\&.readConfFile(\fBstrPath\fP)"
.br
.ti -1c
.RI "tuple \fBclosure\fP = dm\&.generateFluxList(\fBstrPath\fP, sysType)"
.br
.ti -1c
.RI "tuple \fBfoodSet\fP = deepcopy(\fBclosure\fP)"
.br
.ti -1c
.RI "tuple \fBrcts\fP = rf\&.loadAllData(\fBstrPath\fP,'_acsreactions\&.csv')"
.br
.ti -1c
.RI "tuple \fBcats\fP = rf\&.loadAllData(\fBstrPath\fP,'_acscatalysis\&.csv')"
.br
.ti -1c
.RI "tuple \fBRA\fP = raf\&.RAcondition(\fBstrPath\fP,\fBclosure\fP,\fBrcts\fP,\fBcats\fP)"
.br
.ti -1c
.RI "tuple \fBRAF\fP = raf\&.Fcondition(\fBstrPath\fP,\fBclosure\fP,\fBRA\fP,\fBrcts\fP)"
.br
.ti -1c
.RI "tuple \fBRAFlpre\fP = len(\fBRAF\fP)"
.br
.ti -1c
.RI "list \fBredRcts\fP = \fBrcts\fP[\fBRAF\fP,:]"
.br
.ti -1c
.RI "int \fBRAFlpost\fP = 0"
.br
.ti -1c
.RI "tuple \fBcatalists\fP = raf\&.findCatforRAF(\fBcats\fP, \fBRAF\fP, \fBclosure\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int acsRAFanalysis\&._CLOSE_ = 0"

.PP
Definition at line 31 of file acsRAFanalysis\&.py\&.
.SS "int acsRAFanalysis\&._CSTR_ = 2"

.PP
Definition at line 33 of file acsRAFanalysis\&.py\&.
.SS "int acsRAFanalysis\&._PROTO_ = 1"

.PP
Definition at line 32 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.args = parser\&.parse_args()"

.PP
Definition at line 26 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.catalists = raf\&.findCatforRAF(\fBcats\fP, \fBRAF\fP, \fBclosure\fP)"

.PP
Definition at line 76 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.cats = rf\&.loadAllData(\fBstrPath\fP,'_acscatalysis\&.csv')"

.PP
Definition at line 45 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.closure = dm\&.generateFluxList(\fBstrPath\fP, sysType)"

.PP
Definition at line 41 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.conf = rf\&.readConfFile(\fBstrPath\fP)"

.PP
Definition at line 34 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.foodSet = deepcopy(\fBclosure\fP)"

.PP
Definition at line 42 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.parser"
\fBInitial value:\fP
.PP
.nf
1 = ArgumentParser(
2                                 description='Script to perform a RAF analysis\&.'
3                                 , epilog='''File with angle trajectories are created\&. ''')
.fi
.PP
Definition at line 22 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.RA = raf\&.RAcondition(\fBstrPath\fP,\fBclosure\fP,\fBrcts\fP,\fBcats\fP)"

.PP
Definition at line 50 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.RAF = raf\&.Fcondition(\fBstrPath\fP,\fBclosure\fP,\fBRA\fP,\fBrcts\fP)"

.PP
Definition at line 52 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.RAFlpost = 0"

.PP
Definition at line 60 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.RAFlpre = len(\fBRAF\fP)"

.PP
Definition at line 53 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.rcts = rf\&.loadAllData(\fBstrPath\fP,'_acsreactions\&.csv')"

.PP
Definition at line 44 of file acsRAFanalysis\&.py\&.
.SS "list acsRAFanalysis\&.redRcts = \fBrcts\fP[\fBRAF\fP,:]"

.PP
Definition at line 55 of file acsRAFanalysis\&.py\&.
.SS "tuple acsRAFanalysis\&.strPath = os\&.path\&.abspath(args\&.strPath)"

.PP
Definition at line 29 of file acsRAFanalysis\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
