.TH "/home/ale/Documents/GIT/carness/_analysis/underDevelopment/acsSpeciesActivities.py" 3 "Fri Mar 28 2014" "Version 4.8 (20140327.66)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ale/Documents/GIT/carness/_analysis/underDevelopment/acsSpeciesActivities.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBacsSpeciesActivities\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBacsSpeciesActivities\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBacsSpeciesActivities\&.zeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.StrPath\fP = os\&.path\&.abspath(StrPath)"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.tmpDirs\fP = sort(os\&.listdir(StrPath))"
.br
.ti -1c
.RI "int \fBacsSpeciesActivities\&.chemistry\fP = 1"
.br
.ti -1c
.RI "string \fBacsSpeciesActivities\&.ndn\fP = '_0_new_allStatResults'"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.newdirAllResults\fP = os\&.path\&.join(StrPath, ndn)"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.newdirAllResultsInner\fP = os\&.path\&.join(StrPath,'_0_new_allStatResults',ndn)"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.totDirName\fP = os\&.path\&.join(StrPath,tmpDir)"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.resDirPath\fP = os\&.path\&.abspath(os\&.path\&.join('\&./', 'res'))"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.numberOfGen\fP = len(glob\&.glob(os\&.path\&.join(resDirPath,'times_*')))"
.br
.ti -1c
.RI "string \fBacsSpeciesActivities\&.tmpSpeciesStatsSummaryName\fP = 'speciesStatsSummary_'"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.tmpSpeciesStatsSummaryNameFID\fP = open(tmpSpeciesStatsSummaryName, 'w')"
.br
.ti -1c
.RI "string \fBacsSpeciesActivities\&.tmpStr\fP = '\\n------- CHEMISTRY '"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.strZeros\fP = zeroBeforeStrNum(ngen, numberOfGen)"
.br
.ti -1c
.RI "string \fBacsSpeciesActivities\&.strSpeciesZero\fP = 'species_'"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.speciesFilesZero\fP = sorted(glob\&.glob(os\&.path\&.join(resDirPath,strSpeciesZero)))"
.br
.ti -1c
.RI "string \fBacsSpeciesActivities\&.strSpecies\fP = 'species_'"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.speciesFiles\fP = sorted(glob\&.glob(os\&.path\&.join(resDirPath,strSpecies)))"
.br
.ti -1c
.RI "list \fBacsSpeciesActivities\&.lastfilespecies\fP = \fBspeciesFiles\fP[-1]"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.fidSpecies\fP = open(lastfilespecies, '\fBr\fP')"
.br
.ti -1c
.RI "list \fBacsSpeciesActivities\&.seq\fP = []"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.counters\fP = np\&.zeros((nSpecies,3))"
.br
.ti -1c
.RI "string \fBacsSpeciesActivities\&.strRctPar\fP = 'reactions_parameters_'"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.fidRctPar\fP = open(strRctPar, '\fBr\fP')"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.rctType\fP = int(tmpRctType)"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.cat\fP = int(tmpCat)"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.S1\fP = int(tmpS1)"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.S2\fP = int(tmpS2)"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.S3\fP = int(tmpS3)"
.br
.ti -1c
.RI "string \fBacsSpeciesActivities\&.tmpFileName\fP = 'speciesStats_'"
.br
.ti -1c
.RI "tuple \fBacsSpeciesActivities\&.tmpFileNameFID\fP = open(tmpFileName, 'w')"
.br
.ti -1c
.RI "int \fBacsSpeciesActivities\&.ID\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
