.TH "acsSpeciesActivities" 3 "Tue Dec 10 2013" "Version 4.8 (20131209.62)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acsSpeciesActivities \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBStrPath\fP = os\&.path\&.abspath(StrPath)"
.br
.ti -1c
.RI "tuple \fBtmpDirs\fP = sort(os\&.listdir(\fBStrPath\fP))"
.br
.ti -1c
.RI "int \fBchemistry\fP = 1"
.br
.ti -1c
.RI "string \fBndn\fP = '_0_new_allStatResults'"
.br
.ti -1c
.RI "tuple \fBnewdirAllResults\fP = os\&.path\&.join(\fBStrPath\fP, \fBndn\fP)"
.br
.ti -1c
.RI "tuple \fBnewdirAllResultsInner\fP = os\&.path\&.join(\fBStrPath\fP,'_0_new_allStatResults',\fBndn\fP)"
.br
.ti -1c
.RI "tuple \fBtotDirName\fP = os\&.path\&.join(\fBStrPath\fP,tmpDir)"
.br
.ti -1c
.RI "tuple \fBresDirPath\fP = os\&.path\&.abspath(os\&.path\&.join('\&./', 'res'))"
.br
.ti -1c
.RI "tuple \fBnumberOfGen\fP = len(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,'times_*')))"
.br
.ti -1c
.RI "string \fBtmpSpeciesStatsSummaryName\fP = 'speciesStatsSummary_'"
.br
.ti -1c
.RI "tuple \fBtmpSpeciesStatsSummaryNameFID\fP = open(\fBtmpSpeciesStatsSummaryName\fP, 'w')"
.br
.ti -1c
.RI "string \fBtmpStr\fP = '\\n------- CHEMISTRY '"
.br
.ti -1c
.RI "tuple \fBstrZeros\fP = \fBzeroBeforeStrNum\fP(ngen, \fBnumberOfGen\fP)"
.br
.ti -1c
.RI "string \fBstrSpeciesZero\fP = 'species_'"
.br
.ti -1c
.RI "tuple \fBspeciesFilesZero\fP = sorted(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,\fBstrSpeciesZero\fP)))"
.br
.ti -1c
.RI "string \fBstrSpecies\fP = 'species_'"
.br
.ti -1c
.RI "tuple \fBspeciesFiles\fP = sorted(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,\fBstrSpecies\fP)))"
.br
.ti -1c
.RI "list \fBlastfilespecies\fP = \fBspeciesFiles\fP[-1]"
.br
.ti -1c
.RI "tuple \fBfidSpecies\fP = open(\fBlastfilespecies\fP, '\fBr\fP')"
.br
.ti -1c
.RI "list \fBseq\fP = []"
.br
.ti -1c
.RI "tuple \fBcounters\fP = np\&.zeros((nSpecies,3))"
.br
.ti -1c
.RI "string \fBstrRctPar\fP = 'reactions_parameters_'"
.br
.ti -1c
.RI "tuple \fBfidRctPar\fP = open(\fBstrRctPar\fP, '\fBr\fP')"
.br
.ti -1c
.RI "tuple \fBrctType\fP = int(tmpRctType)"
.br
.ti -1c
.RI "tuple \fBcat\fP = int(tmpCat)"
.br
.ti -1c
.RI "tuple \fBS1\fP = int(tmpS1)"
.br
.ti -1c
.RI "tuple \fBS2\fP = int(tmpS2)"
.br
.ti -1c
.RI "tuple \fBS3\fP = int(tmpS3)"
.br
.ti -1c
.RI "string \fBtmpFileName\fP = 'speciesStats_'"
.br
.ti -1c
.RI "tuple \fBtmpFileNameFID\fP = open(\fBtmpFileName\fP, 'w')"
.br
.ti -1c
.RI "int \fBID\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def acsSpeciesActivities\&.zeroBeforeStrNum (tmpl, tmpL)"

.PP
Definition at line 20 of file acsSpeciesActivities\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple acsSpeciesActivities\&.cat = int(tmpCat)"

.PP
Definition at line 130 of file acsSpeciesActivities\&.py\&.
.SS "int acsSpeciesActivities\&.chemistry = 1"

.PP
Definition at line 43 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.counters = np\&.zeros((nSpecies,3))"

.PP
Definition at line 116 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.fidRctPar = open(\fBstrRctPar\fP, '\fBr\fP')"

.PP
Definition at line 122 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.fidSpecies = open(\fBlastfilespecies\fP, '\fBr\fP')"

.PP
Definition at line 105 of file acsSpeciesActivities\&.py\&.
.SS "int acsSpeciesActivities\&.ID = 0"

.PP
Definition at line 162 of file acsSpeciesActivities\&.py\&.
.SS "list acsSpeciesActivities\&.lastfilespecies = \fBspeciesFiles\fP[-1]"

.PP
Definition at line 101 of file acsSpeciesActivities\&.py\&.
.SS "string acsSpeciesActivities\&.ndn = '_0_new_allStatResults'"

.PP
Definition at line 46 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.newdirAllResults = os\&.path\&.join(\fBStrPath\fP, \fBndn\fP)"

.PP
Definition at line 47 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.newdirAllResultsInner = os\&.path\&.join(\fBStrPath\fP,'_0_new_allStatResults',\fBndn\fP)"

.PP
Definition at line 55 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.numberOfGen = len(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,'times_*')))"

.PP
Definition at line 74 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.rctType = int(tmpRctType)"

.PP
Definition at line 129 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.resDirPath = os\&.path\&.abspath(os\&.path\&.join('\&./', 'res'))"

.PP
Definition at line 68 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.S1 = int(tmpS1)"

.PP
Definition at line 131 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.S2 = int(tmpS2)"

.PP
Definition at line 132 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.S3 = int(tmpS3)"

.PP
Definition at line 133 of file acsSpeciesActivities\&.py\&.
.SS "list acsSpeciesActivities\&.seq = []"

.PP
Definition at line 109 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.speciesFiles = sorted(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,\fBstrSpecies\fP)))"

.PP
Definition at line 98 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.speciesFilesZero = sorted(glob\&.glob(os\&.path\&.join(\fBresDirPath\fP,\fBstrSpeciesZero\fP)))"

.PP
Definition at line 93 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.StrPath = os\&.path\&.abspath(StrPath)"

.PP
Definition at line 36 of file acsSpeciesActivities\&.py\&.
.SS "string acsSpeciesActivities\&.strRctPar = 'reactions_parameters_'"

.PP
Definition at line 118 of file acsSpeciesActivities\&.py\&.
.SS "string acsSpeciesActivities\&.strSpecies = 'species_'"

.PP
Definition at line 95 of file acsSpeciesActivities\&.py\&.
.SS "string acsSpeciesActivities\&.strSpeciesZero = 'species_'"

.PP
Definition at line 92 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.strZeros = \fBzeroBeforeStrNum\fP(ngen, \fBnumberOfGen\fP)"

.PP
Definition at line 90 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.tmpDirs = sort(os\&.listdir(\fBStrPath\fP))"

.PP
Definition at line 38 of file acsSpeciesActivities\&.py\&.
.SS "string acsSpeciesActivities\&.tmpFileName = 'speciesStats_'"

.PP
Definition at line 159 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.tmpFileNameFID = open(\fBtmpFileName\fP, 'w')"

.PP
Definition at line 161 of file acsSpeciesActivities\&.py\&.
.SS "string acsSpeciesActivities\&.tmpSpeciesStatsSummaryName = 'speciesStatsSummary_'"

.PP
Definition at line 79 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.tmpSpeciesStatsSummaryNameFID = open(\fBtmpSpeciesStatsSummaryName\fP, 'w')"

.PP
Definition at line 80 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.tmpStr = '\\n------- CHEMISTRY '"

.PP
Definition at line 82 of file acsSpeciesActivities\&.py\&.
.SS "tuple acsSpeciesActivities\&.totDirName = os\&.path\&.join(\fBStrPath\fP,tmpDir)"

.PP
Definition at line 64 of file acsSpeciesActivities\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
