.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/old/allTimesAnalysis.m" 3 "Thu Dec 12 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/old/allTimesAnalysis.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "params do not prompt \fBfigures\fP (0)"
.br
.ti -1c
.RI "OUT \fBdisp\fP ('|--------------------------------|')"
.br
.ti -1c
.RI "\fBdisp\fP ('|-All \fBtimes\fP analysis\&.\&.\&.|')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBout\fP]"
.br
.ti -1c
.RI "params \fBfigureVisible\fP = prompt \fBfigures\fP (1)"
.br
.ti -1c
.RI "params \fBdeltaT\fP = Delta T"
.br
.ti -1c
.RI "params \fBtotT\fP = total time of the \fBsimulation\fP"
.br
.ti -1c
.RI "\fBcurrentDir\fP = \fBcd\fP()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "disp ('|--------------------------------|')"

.SS "disp ('|-All \fBtimes\fP analysis\&.\&.\&.|')"

.SS "params do not prompt figures (0)"

.SH "Variable Documentation"
.PP 
.SS "currentDir = \fBcd\fP()"

.PP
Definition at line 17 of file allTimesAnalysis\&.m\&.
.SS "params deltaT = Delta T"

.PP
Definition at line 9 of file allTimesAnalysis\&.m\&.
.SS "params figureVisible = prompt \fBfigures\fP (1)"

.PP
Definition at line 8 of file allTimesAnalysis\&.m\&.
.SS "function[\fBout\fP]"
\fBInitial value:\fP
.PP
.nf
= allTimesAnalysis(params)
% function [out] = allTimesAnalysis(params)
%

%
% INPUT
%    params\&.tmpPath = simulations path
.fi
.PP
Definition at line 1 of file allTimesAnalysis\&.m\&.
.SS "params totT = total time of the \fBsimulation\fP"

.PP
Definition at line 10 of file allTimesAnalysis\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
