.TH "catalysis" 3 "Wed Apr 3 2013" "Version 3.2 (20130403.51)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
catalysis \- 
.PP
CATALYSIS class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catalysis\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcatalysis\fP ()"
.br
.ti -1c
.RI "\fBcatalysis\fP (\fBacs_longInt\fP tmpCatId, \fBacs_longInt\fP tmpCat, \fBacs_longInt\fP tmpRctId, \fBacs_longInt\fP tmpAmount, \fBacs_double\fP tmpKass, \fBacs_double\fP tmpKdiss, \fBacs_double\fP tmpK_cpx)"
.br
.ti -1c
.RI "\fB~catalysis\fP ()"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetCatId\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetCat\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetReactionID\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetTotAmount\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetKass\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetKdiss\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetK_cpx\fP () const "
.br
.ti -1c
.RI "void \fBupdateTotAmount\fP ()"
.br
.ti -1c
.RI "void \fBresetEventsCounter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
CATALYSIS class\&. 

This class contains catalysis proprieties and methods 
.PP
\fBAuthor:\fP
.RS 4
Alessandro Filisetti 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2009-04-16 
.RE
.PP

.PP
Definition at line 16 of file catalysis\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "catalysis::catalysis ()"

.SS "catalysis::catalysis (\fBacs_longInt\fPtmpCatId, \fBacs_longInt\fPtmpCat, \fBacs_longInt\fPtmpRctId, \fBacs_longInt\fPtmpAmount, \fBacs_double\fPtmpKass, \fBacs_double\fPtmpKdiss, \fBacs_double\fPtmpK_cpx)"
.PP
.nf
    catalysis class constructor (FROM FILE)
.fi
.PP
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2010-03-16 
.RE
.PP

.PP
Definition at line 19 of file catalysis\&.cpp\&.
.SS "catalysis::~catalysis ()\fC [inline]\fP"

.PP
Definition at line 34 of file catalysis\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBacs_longInt\fP catalysis::getCat () const\fC [inline]\fP"

.PP
Definition at line 38 of file catalysis\&.h\&.
.SS "\fBacs_longInt\fP catalysis::getCatId () const\fC [inline]\fP"

.PP
Definition at line 37 of file catalysis\&.h\&.
.SS "\fBacs_double\fP catalysis::getK_cpx () const\fC [inline]\fP"

.PP
Definition at line 43 of file catalysis\&.h\&.
.SS "\fBacs_double\fP catalysis::getKass () const\fC [inline]\fP"

.PP
Definition at line 41 of file catalysis\&.h\&.
.SS "\fBacs_double\fP catalysis::getKdiss () const\fC [inline]\fP"

.PP
Definition at line 42 of file catalysis\&.h\&.
.SS "\fBacs_longInt\fP catalysis::getReactionID () const\fC [inline]\fP"

.PP
Definition at line 39 of file catalysis\&.h\&.
.SS "\fBacs_longInt\fP catalysis::getTotAmount () const\fC [inline]\fP"

.PP
Definition at line 40 of file catalysis\&.h\&.
.SS "void catalysis::resetEventsCounter ()\fC [inline]\fP"

.PP
Definition at line 48 of file catalysis\&.h\&.
.SS "void catalysis::updateTotAmount ()\fC [inline]\fP"

.PP
Definition at line 47 of file catalysis\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
