.TH "commonFunctions" 3 "Thu Sep 19 2013" "Version 4.5 (20130919.57)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commonFunctions \- 
.PP
This class contains all the common function of the system\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <commonFunctions\&.h>\fP
.SH "Detailed Description"
.PP 
This class contains all the common function of the system\&. 

This class contains all the functions useful in general 
.PP
\fBAuthors:\fP
.RS 4
alessandro filisetti 
.RE
.PP
\fBDate:\fP
.RS 4
2011/12/10 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
