.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator/crea_concentrazioni_iniziali.m" 3 "Wed Jul 24 2013" "Version 4.3 (20130719.55)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator/crea_concentrazioni_iniziali.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfiring_disk\fP (:, 3)"
.br
.ti -1c
.RI "\fBif\fP \fBfiring_disk\fP (\fBindex\fP, 3)"
.br
.ti -1c
.RI "\fBelse\fP \fBconcentrazioni_iniziali\fP (\fBi\fP)=0"
.br
.ti -1c
.RI "\fBfiring_disk_reale\fP (\fBk\fP,:) =\fBfiring_disk\fP(\fBi\fP,:)"
.br
.ti -1c
.RI "id \fBZ\fP ()"
.br
.ti -1c
.RI "\fBvalore\fP (1:\fBmax\fP(\fBfiring_disk_bck\fP(:, 2)))=0"
.br
.ti -1c
.RI "\fBvalore\fP (\fBi\fP)"
.br
.ti -1c
.RI "\fBend\fP \fBend\fP \fBend\fP STAMPA 
.br
DISTRIBUZIONI DELLE 
.br
CONCENTRAZIONI \fBfigure\fP (123)%plot(\fBvalore\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBconcentrazioni_iniziali\fP] = \fBcrea_concentrazioni_iniziali\fP(\fBalphabet\fP,\fBfiring_disk\fP,\fBinitialMaxLength\fP,\fBlunghezza_max_fd\fP,\fBratio_firing_disk\fP, \fBscelta_concentrazioni\fP, \fBoverallConcentration\fP, gamma)"
.br
.ti -1c
.RI "le specie fittizie create fino 
.br
alla 
.br
lunghezza_massima_per_calcolare_le_reazioni 
.br
vengono poste uguali \fBa\fP in 
.br
\fBconcentrazione\fP \fBtot_species\fP = 0"
.br
.ti -1c
.RI "for \fBi\fP"
.br
.ti -1c
.RI "\fBend\fP \fBlunghezza_totale\fP = length(\fBfiring_disk\fP(:,1))"
.br
.ti -1c
.RI "\fBfiring_disk_bck\fP =\fBfiring_disk\fP"
.br
.ti -1c
.RI "\fBfiring_disk_2\fP =\fBfiring_disk\fP(1:\fBtot_species\fP,:)"
.br
.ti -1c
.RI "\fBfiring_disk\fP =[]"
.br
.ti -1c
.RI "check di esistenza nel firing \fBdisk\fP \fBnumero_molecole\fP"
.br
.ti -1c
.RI "\fBa\fP seconda dei casi seleziono 
.br
le specie esistenti del firing \fBdisk\fP"
.br
.ti -1c
.RI "\fBa\fP seconda dei casi seleziono 
.br
le specie esistenti del firing 
.br
quelle non esistenti andranno 
.br
semplicemente \fBa\fP \fBconcentrazione\fP \fBremaining_species\fP = \fBtot_species\fP"
.br
.ti -1c
.RI "\fBl_max\fP =0"
.br
.ti -1c
.RI "\fBspecies_to_delete\fP = \fBround\fP(\fBratio_firing_disk\fP*\fBremaining_species\fP)"
.br
.ti -1c
.RI "la percentuale è di \fBreazioni\fP 
.br
fra quelle che restano \fBspecies_to_keep\fP = \fBremaining_species\fP - \fBspecies_to_delete\fP + \fBl_max\fP"
.br
.ti -1c
.RI "while \fBtrovato\fP"
.br
.ti -1c
.RI "\fBend\fP \fBend\fP \fBend\fP \fBswitch\fP 
.br
\fBscelta_concentrazioni\fP case 
.br
distribuzione uniforme su 
.br
tutte le specie esistenti del 
.br
firing \fBdisk\fP \fBprobabilita_uniforme\fP = 1/\fBspecies_to_keep\fP"
.br
.ti -1c
.RI "\fBend\fP \fBend\fP case uniforme sulle 
.br
\fBlunghezza\fP \fBk\fP =0"
.br
.ti -1c
.RI "\fBend\fP \fBend\fP \fBvettore_ordinato_lunghezze\fP = unique(\fBfiring_disk_reale\fP(:,2))"
.br
.ti -1c
.RI "\fBprobabilita_per_lunghezza\fP = 1/length(\fBvettore_ordinato_lunghezze\fP)"
.br
.ti -1c
.RI "\fBend\fP \fBend\fP normalizzazione per 
.br
avere la \fBconcentrazione\fP \fBconcentrazioni_iniziali\fP =concentrazioni_iniziali/\fBsum\fP(concentrazioni_iniziali)*\fBoverallConcentration\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBelse\fP concentrazioni_iniziali (\fBi\fP)\fC [pure virtual]\fP"

.SS "\fBend\fP \fBend\fP \fBend\fP STAMPA DISTRIBUZIONI DELLE CONCENTRAZIONI figure (123)"

.SS "firing_disk (:, 3)"

.SS "\fBif\fP firing_disk (\fBindex\fP, 3)"

.SS "firing_disk_reale (\fBk\fP, :) =\fBfiring_disk\fP(\fBi\fP,:)"

.SS "valore (1:maxfiring_disk_bck(:, 2))\fC [pure virtual]\fP"

.SS "valore (\fBi\fP)"

.SS "id Z ()\fC [virtual]\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBsum\fP(concentrazioni_iniziali) \fBend\fP concentrazioni_iniziali =concentrazioni_iniziali/\fBsum\fP(concentrazioni_iniziali)*\fBoverallConcentration\fP"

.PP
Definition at line 129 of file crea_concentrazioni_iniziali\&.m\&.
.SS "\fBa\fP seconda dei casi seleziono le specie esistenti del firing disk"

.PP
Definition at line 25 of file crea_concentrazioni_iniziali\&.m\&.
.SS "firing_disk =[]"

.PP
Definition at line 17 of file crea_concentrazioni_iniziali\&.m\&.
.SS "firing_disk_2 =\fBfiring_disk\fP(1:\fBtot_species\fP,:)"

.PP
Definition at line 16 of file crea_concentrazioni_iniziali\&.m\&.
.SS "firing_disk_bck =\fBfiring_disk\fP"

.PP
Definition at line 14 of file crea_concentrazioni_iniziali\&.m\&.
.SS "function[\fBconcentrazioni_iniziali\fP] = \fBcrea_concentrazioni_iniziali\fP(\fBalphabet\fP,\fBfiring_disk\fP,\fBinitialMaxLength\fP,\fBlunghezza_max_fd\fP,\fBratio_firing_disk\fP, \fBscelta_concentrazioni\fP, \fBoverallConcentration\fP, gamma)"

.PP
Definition at line 1 of file crea_concentrazioni_iniziali\&.m\&.
.SS "for i"
\fBInitial value:\fP
.PP
.nf
= 1:initialMaxLength
    tot_species = tot_species+length(alphabet)^i
.fi
.PP
Definition at line 9 of file crea_concentrazioni_iniziali\&.m\&.
.SS "\fBend\fP \fBend\fP case favorire quelle corte con una scale free di esponente gamma k =0"

.PP
Definition at line 73 of file crea_concentrazioni_iniziali\&.m\&.
.SS "l_max =0"

.PP
Definition at line 31 of file crea_concentrazioni_iniziali\&.m\&.
.SS "\fBend\fP lunghezza_totale = length(\fBfiring_disk\fP(:,1))"

.PP
Definition at line 13 of file crea_concentrazioni_iniziali\&.m\&.
.SS "check di esistenza nel firing \fBdisk\fP numero_molecole"
\fBInitial value:\fP
.PP
.nf
= overallConcentration*volume
numero_specie = length(firing_disk(:,1))
.fi
.PP
Definition at line 22 of file crea_concentrazioni_iniziali\&.m\&.
.SS "probabilita_per_lunghezza = 1/length(\fBvettore_ordinato_lunghezze\fP)"

.PP
Definition at line 82 of file crea_concentrazioni_iniziali\&.m\&.
.SS "\fBend\fP \fBend\fP \fBend\fP \fBswitch\fP \fBscelta_concentrazioni\fP case distribuzione uniforme su tutte le specie esistenti del firing \fBdisk\fP probabilita_uniforme = 1/\fBspecies_to_keep\fP"

.PP
Definition at line 60 of file crea_concentrazioni_iniziali\&.m\&.
.SS "\fBend\fP remaining_species = \fBtot_species\fP"

.PP
Definition at line 30 of file crea_concentrazioni_iniziali\&.m\&.
.SS "\fBend\fP \fBend\fP species_to_delete = \fBround\fP(\fBratio_firing_disk\fP*\fBremaining_species\fP)"

.PP
Definition at line 38 of file crea_concentrazioni_iniziali\&.m\&.
.SS "la percentuale è di \fBreazioni\fP fra quelle che restano species_to_keep = \fBremaining_species\fP - \fBspecies_to_delete\fP + \fBl_max\fP"

.PP
Definition at line 39 of file crea_concentrazioni_iniziali\&.m\&.
.SS "le specie fittizie create fino alla lunghezza_massima_per_calcolare_le_reazioni vengono poste uguali \fBa\fP in \fBconcentrazione\fP tot_species = 0"

.PP
Definition at line 8 of file crea_concentrazioni_iniziali\&.m\&.
.SS "while trovato"
\fBInitial value:\fP
.PP
.nf
==0
                index = l_max+ceil(rand*remaining_species)
.fi
.PP
Definition at line 44 of file crea_concentrazioni_iniziali\&.m\&.
.SS "\fBend\fP \fBend\fP vettore_ordinato_lunghezze = unique(\fBfiring_disk_reale\fP(:,2))"

.PP
Definition at line 81 of file crea_concentrazioni_iniziali\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
