.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator/crea_influx.m" 3 "Thu Sep 19 2013" "Version 4.5 (20130919.57)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator/crea_influx.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinflux\fP (\fBi\fP, 2)"
.br
.ti -1c
.RI "\fBinflux\fP (\fBi\fP,:)"
.br
.ti -1c
.RI "\fBif\fP \fBsum\fP (\fBinflux\fP(\fBi\fP, 1)==\fBinflux\fP(:, 1))"
.br
.ti -1c
.RI "\fBinflux\fP (1, 1:2)=0"
.br
.ti -1c
.RI "\fBif\fP \fBinflux\fP (1, 1)>0%%%for \fBi\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBinflux\fP]"
.br
.ti -1c
.RI "\fBend\fP for \fBj\fP"
.br
.ti -1c
.RI "\fBend\fP \fBend\fP \fBtot_species\fP = length(\fBfiring_disk\fP(:,1))"
.br
.ti -1c
.RI "\fBswitch\fP scelta_influx casuale case \fBspecies_to_delete\fP = \fBround\fP(ratio_influx*\fBtot_species\fP)"
.br
.ti -1c
.RI "\fBspecies_to_keep\fP = \fBtot_species\fP - \fBspecies_to_delete\fP"
.br
.ti -1c
.RI "for \fBi\fP"
.br
.ti -1c
.RI "while \fBtrovato\fP == 0"
.br
.ti -1c
.RI "\fBend\fP \fBend\fP \fBend\fP \fBinflux\fP =sort(influx)"
.br
.ti -1c
.RI "casuale tenendo \fBi\fP polimeri 
.br
fino \fBa\fP \fBlunghezza\fP \fBx\fP e poi ne 
.br
toglie l \fBx\fP case \fBremaining_species\fP = \fBtot_species\fP"
.br
.ti -1c
.RI "\fBend\fP proporzionale alla \fBlunghezza\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "influx (\fBi\fP, 2)"

.SS "influx (\fBi\fP, :)"

.SS "influx (1, 1:2)\fC [pure virtual]\fP"

.SS "\fBif\fP influx (1, 1)"

.SS "\fBif\fP sum (\fBinflux\fP(\fBi\fP, 1) = \fC=\fBinflux\fP(:, 1)\fP)"
\fBInitial value:\fP
.PP
.nf
==1
%                         trovato = 1
.fi
.SH "Variable Documentation"
.PP 
.SS "function[\fBinflux\fP]"
\fBInitial value:\fP
.PP
.nf
= crea_influx(concentrazioni_iniziali)
%function [influx] = crea_influx(concentrazioni_iniziali)


for i =1:length(concentrazioni_iniziali)
    
    influx(i,1)=i
.fi
.PP
Definition at line 3 of file crea_influx\&.m\&.
.SS "for i"
\fBInitial value:\fP
.PP
.nf
= 1:species_to_keep
%             trovato = 0
.fi
.PP
Definition at line 56 of file crea_influx\&.m\&.
.SS "\fBelse\fP clear influx influx =sort(influx)"

.PP
Definition at line 65 of file crea_influx\&.m\&.
.SS "\fBend\fP for j"
\fBInitial value:\fP
.PP
.nf
= length(concentrazioni_iniziali):-1:1
    if influx (j,2)==0
        influx(j,:)=[]
.fi
.PP
Definition at line 13 of file crea_influx\&.m\&.
.SS "\fBend\fP proporzionale alla lunghezza"

.PP
Definition at line 108 of file crea_influx\&.m\&.
.SS "remaining_species = \fBtot_species\fP"

.PP
Definition at line 71 of file crea_influx\&.m\&.
.SS "\fBend\fP \fBend\fP species_to_delete = \fBround\fP(ratio_influx*\fBtot_species\fP)"

.PP
Definition at line 53 of file crea_influx\&.m\&.
.SS "species_to_keep = \fBtot_species\fP - \fBspecies_to_delete\fP"

.PP
Definition at line 54 of file crea_influx\&.m\&.
.SS "\fBend\fP \fBend\fP tot_species = length(\fBfiring_disk\fP(:,1))"

.PP
Definition at line 44 of file crea_influx\&.m\&.
.SS "while trovato == 0"

.PP
Definition at line 58 of file crea_influx\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
