.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator/crea_firing_disk.m" 3 "Thu Dec 12 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator/crea_firing_disk.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstep\fP (\fBi\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBfiring_disk\fP]"
.br
.ti -1c
.RI "for \fBi\fP"
.br
.ti -1c
.RI "\fBend\fP \fBk\fP = 1"
.br
.ti -1c
.RI "\fBend\fP \fBfiring_disk\fP =id_species"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "step (\fBi\fP)"

.SH "Variable Documentation"
.PP 
.SS "\fBend\fP firing_disk =id_species"

.PP
Definition at line 24 of file crea_firing_disk\&.m\&.
.SS "function[\fBfiring_disk\fP]"
\fBInitial value:\fP
.PP
.nf
= crea_firing_disk(alphabet,massima_lunghezza_su_cui_calcolare_le_reazioni)
%function [firing_disk] = crea_firing_disk(alphabet,massima_lunghezza_su_cui_calcolare_le_reazioni)

tot_species = 0
.fi
.PP
Definition at line 3 of file crea_firing_disk\&.m\&.
.SS "for i"
\fBInitial value:\fP
.PP
.nf
= 1:massima_lunghezza_su_cui_calcolare_le_reazioni
    tot_species = tot_species+length(alphabet)^i
.fi
.PP
Definition at line 8 of file crea_firing_disk\&.m\&.
.SS "k = 1"

.PP
Definition at line 18 of file crea_firing_disk\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
