.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator/crea_influx_semplice.m" 3 "Tue Dec 10 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_matlabinitializator/crea_influx_semplice.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinflux\fP (\fBj\fP, 2)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBinflux\fP]"
.br
.ti -1c
.RI "for \fBi\fP"
.br
.ti -1c
.RI "\fBend\fP \fBinflux\fP = zeros(sn,2)"
.br
.ti -1c
.RI "for \fBj\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "influx (\fBj\fP, 2)"

.SH "Variable Documentation"
.PP 
.SS "function[\fBinflux\fP]"
\fBInitial value:\fP
.PP
.nf
= crea_influx_semplice(lMaxInflux,alphabet)

% total Number of species
sn = 0
.fi
.PP
Definition at line 3 of file crea_influx_semplice\&.m\&.
.SS "for i"
\fBInitial value:\fP
.PP
.nf
= 1:lMaxInflux
   sn = sn + length(alphabet)^i
.fi
.PP
Definition at line 7 of file crea_influx_semplice\&.m\&.
.SS "\fBend\fP influx = zeros(sn,2)"

.PP
Definition at line 11 of file crea_influx_semplice\&.m\&.
.SS "for j"
\fBInitial value:\fP
.PP
.nf
= 1:sn
   influx(j,1)=j
.fi
.PP
Definition at line 12 of file crea_influx_semplice\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
