.TH "environment" 3 "Tue Dec 10 2013" "Version 4.8 (20131209.62)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
environment \- 
.PP
environment class  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <environment\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBenvironment\fP (string tmpInitialPath)"
.br
.ti -1c
.RI "\fB~environment\fP ()"
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetNgen\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetNsim\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetActualTime\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetNseconds\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetNreactions\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetMAXhours\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetMAXattempts\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetCurrentAttempts\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetTimeStructuresSavingInterval\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetFileTimesSavingInterval\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetLastFiringDiskSpeciesID\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetOverallConcentration\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetMaxNonCatalyticLength\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetRctProb\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetCleavProb\fP () const "
.br
.ti -1c
.RI "bool \fBgetReverseReactions\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetEnergy\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetRatioSpeciesEnergizable\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetADP\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetATP\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetMols\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNewMols\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNspecies\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNnewSpecies\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNcpx\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNcpxMols\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetGillespieMean\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetgillespieSD\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetgillespieEntropy\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetRatioBetweenNewGillTotGill\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetRatioBetweenBackandForw\fP () const "
.br
.ti -1c
.RI "bool \fBgetSystemExpFlag\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetKdiss\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetKass\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetKcpx\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetKcpxDiss\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetKnrg\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetKirrad\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetK_spont_diss\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetK_spont_ass\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetCleavageKC\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetComplexKC\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetCondensationKC\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetComplexDegKC\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetMoleculeDecayKC\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetMaxLOut\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetSolubilityThreshold\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetDiffusionContribute\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetInflux\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetRefillInterval\fP () const "
.br
.ti -1c
.RI "string \fBgetAlphabet\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetVolume\fP () const "
.br
.ti -1c
.RI "\fBacs_double\fP \fBgetRandomSeed\fP () const "
.br
.ti -1c
.RI "vector< \fBspecies\fP > \fBgetMoleculesPopulation\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetTotalNumberOfSpecies\fP ()"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetTotalNumberOfPossibleCatalysts\fP ()"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetTotalNumberOfMolecules\fP ()"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetTotalNumberOfComplexSpecies\fP ()"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetTotalNumberOfComplexes\fP ()"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetTotalNumberOfMonomers\fP ()"
.br
.ti -1c
.RI "vector< \fBreactions\fP > \fBgetReactionsLayer\fP () const "
.br
.ti -1c
.RI "int \fBgetDebugLevel\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNumberOfTheoreticalSpecies\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNumberOfReactions\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNumberOfCatalysis\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNumberOfGillespieCOPYpossibleRcts\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetNumberOfGillespiePossibleRcts\fP () const "
.br
.ti -1c
.RI "void \fBsetLivingSpeciesIDsAndAmounts\fP ()"
.br
.ti -1c
.RI "void \fBsetNotChargedAndChargedSpeciesIDsAndAmounts\fP ()"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetCleavageCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetEndoCleavageCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetCondensationCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetEndoCondensationCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetCpxFormCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetCpxDissCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetOverallLoadedMolsCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetSpontDissCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetSpontAssCounter\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetTotNumberOfChargedMols\fP ()"
.br
.ti -1c
.RI "void \fBshowGlobalParameter\fP ()"
.br
.ti -1c
.RI "void \fBprintInitialCondition\fP ()"
.br
.ti -1c
.RI "void \fBprintAllSpeciesIdAndSequence\fP ()"
.br
.ti -1c
.RI "void \fBprintGillespieStructure\fP ()"
.br
.ti -1c
.RI "void \fBprintNutrientsAndProbability\fP ()"
.br
.ti -1c
.RI "void \fBprintAllChargeMols\fP ()"
.br
.ti -1c
.RI "bool \fBcreateInitialMoleculesPopulationFromFileSTD\fP (string tmpSpeciesFilePath)"
.br
.ti -1c
.RI "bool \fBcreateInitialReactionsLayerFromFileSTD\fP (string tmpSpeciesFilePath)"
.br
.ti -1c
.RI "bool \fBcreateInitialCatalysisLayerFromFileSTD\fP (string tmpCatalysisFilePath)"
.br
.ti -1c
.RI "bool \fBcreateInfluxLayersFromFileSTD\fP (string tmpInfluxFilePath)"
.br
.ti -1c
.RI "bool \fBcreateNrgBooleanFunctionsFromFileSTD\fP (string tmpBoolNrgFilePath)"
.br
.ti -1c
.RI "bool \fBcreateInitialMoleculesPopulationFromSpecificFileSTD\fP (string tmpSpeciesFilePath, \fBacs_int\fP tmpActGEN, \fBacs_int\fP tmpActSIM)"
.br
.ti -1c
.RI "bool \fBcreateInitialReactionsLayerFromSpecificFileSTD\fP (string tmpReactionsFilePath, \fBacs_int\fP tmpActGEN, \fBacs_int\fP tmpActSIM)"
.br
.ti -1c
.RI "bool \fBcreateInitialCatalysisLayerFromSpecificFileSTD\fP (string tmpCatalysisFilePath, \fBacs_int\fP tmpActGEN, \fBacs_int\fP tmpActSIM)"
.br
.ti -1c
.RI "void \fBnutrientsAmountsFixing\fP ()"
.br
.ti -1c
.RI "\fBacs_int\fP \fBcomputeSngSpeciesRctsNumber\fP (\fBacs_longInt\fP tmpTotalNumberOfReactions, \fBMTRand\fP &tmpRndDoubleGen)"
.br
.ti -1c
.RI "\fBacs_int\fP \fBselectWhetherCleavageOrCond\fP (\fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBcreateReactionsForThisSpecies\fP (\fBacs_longInt\fP tmpsID, \fBacs_int\fP tmpReactionsForThisSpecies, \fBMTRand\fP &tmp_RndDoubleGen, vector< \fBacs_longInt\fP > &tmpIDOfCandidateSpecies, \fBacs_int\fP tmpRctCreationType)"
.br
.ti -1c
.RI "bool \fBupdateReactions\fP (\fBacs_longInt\fP tmpIDtoUpdate, \fBacs_longInt\fP tmpNewSpecies, \fBacs_int\fP tmpRctType, vector< \fBacs_longInt\fP > &tmp_AlreadyEvaluatedSpeciesVector, \fBMTRand\fP &tmp_RndDoubleGen)"
.br
.ti -1c
.RI "\fBacs_double\fP \fBcreateDiffusionRenforcement\fP (\fBacs_double\fP tmpDiffEnh, \fBacs_int\fP tmpNewSpeciesLength)"
.br
.ti -1c
.RI "bool \fBsetSolubility\fP (\fBacs_int\fP tmpNewSpeciesLength, \fBMTRand\fP &tmpRndDoubleGen)"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBreturnPosSpeciesAlreadyPresent\fP (string tmpNewSequence)"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBreturnPosReactionAlreadyPresent\fP (\fBacs_int\fP tmpReactionType, \fBacs_longInt\fP tmpIds_I, \fBacs_longInt\fP tmpIds_II, \fBacs_longInt\fP tmpIds_III)"
.br
.ti -1c
.RI "bool \fBcheckIfTheReactionIsAlreadyCatalyzedByThisSpecies\fP (\fBacs_longInt\fP tmpSPeciesID, \fBacs_longInt\fP tmpIdReaction)"
.br
.ti -1c
.RI "bool \fBperformOPTGillespieComputation\fP (\fBMTRand\fP &tmpRndDoubleGen, clock_t &tmpTimeElapsed, \fBacs_int\fP tmpActGEN, \fBacs_int\fP tmpActSIM, \fBacs_int\fP tmpActSTEP, string tmpStoringPath)"
.br
.ti -1c
.RI "bool \fBperformReaction\fP (\fBacs_longInt\fP reaction_u, \fBMTRand\fP &tmp_RndDoubleGen, \fBacs_int\fP tmp_ActGEN, \fBacs_int\fP tmp_ActSIM, \fBacs_int\fP tmp_ActSTEP, string tmp_StoringPath)"
.br
.ti -1c
.RI "bool \fBnewSpeciesEvaluationIII\fP (\fBacs_longInt\fP tmpNewSpecies, \fBMTRand\fP &tmp___RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBcomplexEvaluation\fP (string tmpComplex, \fBMTRand\fP &tmp___RndDoubleGen, \fBacs_int\fP tmpCuttingPnt, \fBacs_longInt\fP tmpCatalyst_ID, \fBacs_longInt\fP tmpCatID, \fBacs_longInt\fP tmpSubstrate_ID, \fBacs_longInt\fP tmpSecSub_ID, bool tmpCpxType)"
.br
.ti -1c
.RI "\fBacs_double\fP \fBcomputeSinglGilScore\fP (\fBacs_longInt\fP tmpAmountI, \fBacs_double\fP tmpDifI, \fBacs_int\fP tmpSolI, \fBacs_longInt\fP tmpAmountII, \fBacs_double\fP tmpDifII, \fBacs_int\fP tmpSolII, \fBacs_double\fP tmpK, bool tmpSameMol)"
.br
.ti -1c
.RI "void \fBperformSingleGilleSpieIntroduction\fP (\fBacs_longInt\fP tmpAmountI, \fBacs_longInt\fP tmpAmountII, \fBacs_longInt\fP tmpIDI, \fBacs_longInt\fP tmpIDII, \fBacs_longInt\fP tmpIDCatalysis, \fBacs_int\fP tmp__rctType, \fBacs_longInt\fP tmpMol_I, \fBacs_longInt\fP tmpMol_II, \fBacs_longInt\fP tmpMol_III, \fBacs_longInt\fP tmpMol_IV, \fBacs_int\fP tmpNRGDirection, \fBacs_longInt\fP tmpRctID, bool tmpSameSpeciesControl)"
.br
.ti -1c
.RI "void \fBchangeVolume\fP (\fBacs_int\fP tmpTimeSinceLastReaction)"
.br
.ti -1c
.RI "void \fBincNumberOfSpecies\fP ()"
.br
.ti -1c
.RI "void \fBdecNumberOfSpecies\fP (\fBacs_int\fP tmpID)"
.br
.ti -1c
.RI "void \fBincNumberOfMols\fP ()"
.br
.ti -1c
.RI "void \fBdecNumberOfMols\fP ()"
.br
.ti -1c
.RI "void \fBincNumberOfCpx\fP ()"
.br
.ti -1c
.RI "void \fBdecNumberOfCpx\fP (\fBacs_int\fP tmpID)"
.br
.ti -1c
.RI "void \fBincNumberOfCpxMols\fP ()"
.br
.ti -1c
.RI "void \fBdecNumberOfCpxMols\fP ()"
.br
.ti -1c
.RI "void \fBincNumberOfNewSpecies\fP (\fBacs_int\fP tmpID)"
.br
.ti -1c
.RI "void \fBdecNumberOfNewSpecies\fP (\fBacs_int\fP tmpID)"
.br
.ti -1c
.RI "void \fBincNumberOfNewMols\fP (\fBacs_int\fP tmpID)"
.br
.ti -1c
.RI "void \fBdecNumberOfNewMols\fP (\fBacs_int\fP tmpID)"
.br
.ti -1c
.RI "void \fBdecMolSpeciesProcedure\fP (\fBacs_int\fP tmp_ID)"
.br
.ti -1c
.RI "void \fBdecCpxProcedure\fP (\fBacs_int\fP tmp_ID)"
.br
.ti -1c
.RI "void \fBincMolProcedure\fP (\fBacs_int\fP tmp_ID)"
.br
.ti -1c
.RI "void \fBincSpeciesProcedure\fP (\fBacs_int\fP tmp_ID)"
.br
.ti -1c
.RI "void \fBunchargeMolProcess\fP (\fBacs_int\fP tmp_ID)"
.br
.ti -1c
.RI "void \fBincCleavageCounter\fP ()"
.br
.ti -1c
.RI "void \fBincEndoCleavageCounter\fP ()"
.br
.ti -1c
.RI "void \fBincCondensationCounter\fP ()"
.br
.ti -1c
.RI "void \fBincEndoCondensationCounter\fP ()"
.br
.ti -1c
.RI "void \fBincCpxFormCounter\fP ()"
.br
.ti -1c
.RI "void \fBincCpxDissCounter\fP ()"
.br
.ti -1c
.RI "void \fBincOverallLoadedMolsCounter\fP ()"
.br
.ti -1c
.RI "void \fBdecOverallLoadedMolsCounter\fP ()"
.br
.ti -1c
.RI "void \fBincSpontDissCounter\fP ()"
.br
.ti -1c
.RI "void \fBincSpontAssCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetCleavageCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetEndoCleavageCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetCondensationCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetEndoCondensationCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetOverallLoadedMolsCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetCpxFormCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetCpxDissCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetSpontDissCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetSpontAssCounter\fP ()"
.br
.ti -1c
.RI "void \fBresetReactionsCounter\fP ()"
.br
.ti -1c
.RI "bool \fBaddChargeMolToList\fP (\fBacs_int\fP tmpSpeciesID)"
.br
.ti -1c
.RI "bool \fBremoveChargeMolFromList\fP (\fBacs_int\fP tmpSpeciesID)"
.br
.ti -1c
.RI "void \fBclearAllStructures\fP ()"
.br
.ti -1c
.RI "void \fBresetConcentrationToInitialConditions\fP ()"
.br
.ti -1c
.RI "void \fBstoreInitialStructures\fP ()"
.br
.ti -1c
.RI "bool \fBperformRefill\fP (\fBacs_double\fP tmpTimeSinceTheLastInFlux, \fBacs_double\fP tmpMinimalTimeForOneMols, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformMoleculesEfflux\fP (\fBacs_double\fP tmpTimeInterval, \fBMTRand\fP &tmp_RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformDETMoleculesCharging\fP (\fBacs_double\fP tmpTimeInterval, \fBMTRand\fP &tmp_RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformDETComplexDissociation\fP (\fBacs_double\fP tmpTimeInterval, \fBMTRand\fP &tmp_RndDoubleGen)"
.br
.ti -1c
.RI "void \fBsetActualTime\fP (\fBacs_double\fP tmpActualTime)"
.br
.ti -1c
.RI "void \fBupdateSpeciesAges\fP ()"
.br
.ti -1c
.RI "void \fBincreaseAttempts\fP ()"
.br
.ti -1c
.RI "bool \fBperformCondensation\fP (\fBacs_longInt\fP tmpCatalyst, \fBacs_longInt\fP tmpSubstrate, \fBacs_longInt\fP tmpProduct, \fBacs_longInt\fP tmpComplex, \fBacs_longInt\fP tmpIdReaction, \fBacs_longInt\fP tmpIdCatalysis, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperform_endo_Condensation\fP (\fBacs_longInt\fP tmpCatalyst, \fBacs_longInt\fP tmpSubstrate, \fBacs_longInt\fP tmpProduct, \fBacs_longInt\fP tmpComplex, \fBacs_int\fP tmpNRGside, \fBacs_longInt\fP tmpIdReaction, \fBacs_longInt\fP tmpIdCatalysis, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformCleavage\fP (\fBacs_longInt\fP tmpSubstrate, \fBacs_longInt\fP tmpProduct_I, \fBacs_longInt\fP tmpProduct_II, \fBacs_longInt\fP tmpIdReaction, \fBacs_longInt\fP tmpIdCatalysis, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperform_endo_Cleavage\fP (\fBacs_longInt\fP tmpSubstrate, \fBacs_longInt\fP tmpProduct_I, \fBacs_longInt\fP tmpProduct_II, \fBacs_int\fP tmpNRGside, \fBacs_longInt\fP tmpIdReaction, \fBacs_longInt\fP tmpIdCatalysis, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformComplexFormation\fP (\fBacs_longInt\fP tmpCatalyst, \fBacs_longInt\fP tmpSubstrate, \fBacs_longInt\fP tmpCatID, \fBacs_longInt\fP tmpSecSub, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperform_endo_ComplexFormation\fP (\fBacs_longInt\fP tmpCatalyst, \fBacs_longInt\fP tmpSubstrate, \fBacs_longInt\fP tmpCatID, \fBacs_longInt\fP tmpSecSub, \fBacs_int\fP tmpNRGSide, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformComplexDissociation\fP (\fBacs_longInt\fP tmpComplex, \fBacs_longInt\fP tmpCatalyst, \fBacs_longInt\fP tmpSubstrate, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformSpontaneousCondensation\fP (\fBacs_longInt\fP tmpReaction, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformSpontaneousCleavage\fP (\fBacs_longInt\fP tmpReaction, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformMoleculeEfflux\fP (\fBacs_longInt\fP tmpSpecies, \fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBperformEnergyEfflux\fP (\fBMTRand\fP &tmp__RndDoubleGen)"
.br
.ti -1c
.RI "bool \fBstructureCoherenceCheckUp\fP ()"
.br
.ti -1c
.RI "bool \fBnotInverseReactionAlreadyCatalyzed\fP (\fBacs_int\fP tmpRct, \fBacs_longInt\fP tmpID_I, \fBacs_longInt\fP tmpID_II)"
.br
.ti -1c
.RI "bool \fBcheckIfOnlyMutualCatalysis\fP (\fBacs_int\fP tmpCat, \fBacs_int\fP tmpCandidateProduct)"
.br
.ti -1c
.RI "bool \fBcheckAvailability\fP (\fBacs_longInt\fP tmpMI, \fBacs_longInt\fP tmpMII, \fBacs_longInt\fP tmpQI, \fBacs_longInt\fP tmpQII)"
.br
.ti -1c
.RI "void \fBinserSubListInSpecies\fP ()"
.br
.ti -1c
.RI "void \fBshowSubListInSpecies\fP ()"
.br
.ti -1c
.RI "void \fBshowGillEngagementInSpecies\fP ()"
.br
.ti -1c
.RI "bool \fBsaveConfigurationFileSTD\fP (string tmpStoringPath)"
.br
.ti -1c
.RI "bool \fBsaveInfluxStructureSTD\fP (string tmpStoringPath)"
.br
.ti -1c
.RI "bool \fBsaveNrgBoolFncStructureSTD\fP (string tmpStoringPath)"
.br
.ti -1c
.RI "string \fBzeroBeforeStringNumberSTD\fP (\fBacs_int\fP tmpTotN, \fBacs_int\fP tmpCurrentN)"
.br
.ti -1c
.RI "bool \fBsaveSpeciesStructureSTD\fP (\fBacs_int\fP tmpCurrentGen, \fBacs_int\fP tmpCurrentSim, \fBacs_int\fP tmpCurrentStep, string tmpStoringPath)"
.br
.ti -1c
.RI "bool \fBsaveReactionsStructureSTD\fP (\fBacs_int\fP tmpCurrentGen, \fBacs_int\fP tmpCurrentSim, \fBacs_int\fP tmpCurrentStep, string tmpStoringPath)"
.br
.ti -1c
.RI "bool \fBsaveCatalysisStructureSTD\fP (\fBacs_int\fP tmpCurrentGen, \fBacs_int\fP tmpCurrentSim, \fBacs_int\fP tmpCurrentStep, string tmpStoringPath)"
.br
.ti -1c
.RI "bool \fBsaveTimesSTD\fP (\fBacs_int\fP tmpCurrentGen, \fBacs_int\fP tmpCurrentSim, \fBacs_int\fP tmpCurrentStep, string tmpStoringPath)"
.br
.ti -1c
.RI "bool \fBsaveReactionsParametersSTD\fP (\fBacs_int\fP tmp__CurrentGen, \fBacs_int\fP tmp__CurrentSim, \fBacs_int\fP tmp__CurrentStep, string tmp__StoringPath, \fBacs_int\fP tmpRctType, \fBacs_longInt\fP tmpCat, \fBacs_longInt\fP tmpMol_I, \fBacs_longInt\fP tmpMol_II, \fBacs_longInt\fP tmpMol_III)"
.br
.ti -1c
.RI "bool \fBsaveLivingSpeciesIDSTD\fP (\fBacs_int\fP tmp__CurrentGen, \fBacs_int\fP tmp__CurrentSim, \fBacs_int\fP tmp__CurrentStep, string tmp__StoringPath)"
.br
.ti -1c
.RI "bool \fBsaveLivingSpeciesAmountSTD\fP (\fBacs_int\fP tmp__CurrentGen, \fBacs_int\fP tmp__CurrentSim, string tmp__StoringPath)"
.br
.ti -1c
.RI "bool \fBsaveLivingSpeciesConcentrationSTD\fP (\fBacs_int\fP tmp__CurrentGen, \fBacs_int\fP tmp__CurrentSim, string tmp__StoringPath)"
.br
.ti -1c
.RI "bool \fBdevStd\fP ()"
.br
.ti -1c
.RI "bool \fBentropy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
environment class 


.PP
\fBAuthor:\fP
.RS 4
Alessandro Filisetti 
.RE
.PP
\fBVersion:\fP
.RS 4
2\&.4 
.RE
.PP
\fBDate:\fP
.RS 4
2010-06-10 *^*^*^*^*
.RE
.PP
This class contains environmental proprieties and methods; within this class all things occur 
.PP
\fBAuthor:\fP
.RS 4
Alessandro Filisetti 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
2011-12-15 
.RE
.PP

.PP
Definition at line 20 of file environment\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "environment::environment (stringtmpInitialPath)"
TEMPLATE DEACLARATION AND DEFINITION Test environment costructor 
.PP
\fBVersion:\fP
.RS 4
2\&.4 
.RE
.PP
\fBDate:\fP
.RS 4
2010-06-27 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpRndDoubleGen\fP randomGenerator reference Environment Constructor 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpInitialPath\fP 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/04 
.RE
.PP

.PP
Definition at line 80 of file environment\&.cpp\&.
.SS "environment::~environment ()\fC [inline]\fP"

.PP
Definition at line 148 of file environment\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool environment::addChargeMolToList (\fBacs_int\fPtmpSpeciesID)"
Perform vector unchargedIDlist update adding a new charge molecule vector unchargedIDlist and cumUnchargedAmountList are involved 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2010-10-10 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_int\fP tmpSpeciesID Specie to charge 
.RE
.PP

.PP
Definition at line 4313 of file environment\&.cpp\&.
.SS "void environment::changeVolume (\fBacs_int\fPtmpTimeSinceLastReaction)"
Change volume function  1\&.0 
.PP
\fBDate:\fP
.RS 4
2013/07/17 
.RE
.PP
\fBAuthor:\fP
.RS 4
Alessandro Filisetti 
.RE
.PP

.PP
Definition at line 6157 of file environment\&.cpp\&.
.SS "bool environment::checkAvailability (\fBacs_longInt\fPtmpMI, \fBacs_longInt\fPtmpMII, \fBacs_longInt\fPtmpQI, \fBacs_longInt\fPtmpQII)"
Return TRUE if there are sufficient molecules for the reaction\&. It is used for the reaction in which catalyst and substrate are the same molecules 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2011\&.07\&.25 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpMI\fP 
.br
\fItmpMII\fP 
.br
\fItmpQI\fP 
.br
\fItmpQII\fP 
.RE
.PP

.PP
Definition at line 2635 of file environment\&.cpp\&.
.SS "bool environment::checkIfOnlyMutualCatalysis (\fBacs_int\fPtmpCat, \fBacs_int\fPtmpCandidateProduct)"
This function return false if the tmpCandidateProduct is a catalyst of tmpCat 
.PP
\fBVersion:\fP
.RS 4
1\&.0 - last update 2009/10/08 - build 009 
.RE
.PP

.PP
Definition at line 1965 of file environment\&.cpp\&.
.SS "bool environment::checkIfTheReactionIsAlreadyCatalyzedByThisSpecies (\fBacs_longInt\fPtmpSPeciesID, \fBacs_longInt\fPtmpIdReaction)"
If the reaction is not new this function checks if the reactions has been already catalysed by this species 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_int\fP tmpSPeciesID catalyst ID 
.br
\fItmpIdReaction\fP reaction ID 
.RE
.PP

.PP
Definition at line 1937 of file environment\&.cpp\&.
.SS "void environment::clearAllStructures ()"
Clear all structures after each simulation 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6405 of file environment\&.cpp\&.
.SS "bool environment::complexEvaluation (stringtmpComplex, \fBMTRand\fP &tmp___RndDoubleGen, \fBacs_int\fPtmpCuttingPnt, \fBacs_longInt\fPtmpCatalyst_ID, \fBacs_longInt\fPtmpSubstrate_ID, \fBacs_longInt\fPtmpCatID, \fBacs_longInt\fPtmpSecSub_ID, booltmpCpxType)"
Complex evaluation 
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2010-06-04 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpNewSpecies New species sequence to evaluate 
.br
\fIMTRand&\fP tmp___RndDoubleGen random number generator 
.br
\fItmpCuttingPnt\fP Complex cutting point 
.br
\fItmpCatalyst_ID\fP catalyst ID 
.br
\fItmpSubstrate_ID\fP substrate ID 
.br
\fItmp_catalysisID\fP catalysis ID 
.br
\fItmpCpxType\fP ENDOERGONIC or ESOERGONIC 
.RE
.PP

.PP
Definition at line 6025 of file environment\&.cpp\&.
.SS "\fBacs_double\fP environment::computeSinglGilScore (\fBacs_longInt\fPtmpAmountI, \fBacs_double\fPtmpDifI, \fBacs_int\fPtmpSolI, \fBacs_longInt\fPtmpAmountII, \fBacs_double\fPtmpDifII, \fBacs_int\fPtmpSolII, \fBacs_double\fPtmpK, booltmpSameMol)"
Compute a single gillespie score according to the amount and peoprieties of the species involved 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
20110214 
.RE
.PP

.PP
Definition at line 3288 of file environment\&.cpp\&.
.SS "\fBacs_int\fP environment::computeSngSpeciesRctsNumber (\fBacs_longInt\fPtmpTotalNumberOfReactions, \fBMTRand\fP &tmpRndDoubleGen)"
Initial molecule population creation\&. If the number of species stored in the configuration file is grater than the possible number of species according to the alphabet and maximum length all species up to the MAX length will be created 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIMTRand&\fP tmpRndDoubleGen initial layer initialization 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIMTRand&\fP tmpRndDoubleGen Compute number of reaction catalysd by a catalyst according to the total number of reactions and reactions probabilities 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_int\fP tmpTotalNumberOfReactions Total number of conceivable reactions 
.br
\fIacs_double\fP tmpRctsProb reaction probability 
.RE
.PP

.PP
Definition at line 481 of file environment\&.cpp\&.
.SS "\fBacs_double\fP environment::createDiffusionRenforcement (\fBacs_double\fPtmpDiffEnh, \fBacs_int\fPtmpNewSpeciesLength)"
Create the diffusion constant renforcement according to the species length 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpDiffEnh\fP diffusion enhancement from parameters 
.br
\fIMTRand&\fP tmp_RndDoubleGen random number generator 
.br
\fItmpNewSpeciesLength\fP Lenght of the species 
.RE
.PP

.PP
Definition at line 1819 of file environment\&.cpp\&.
.SS "bool environment::createInfluxLayersFromFileSTD (stringtmpInfluxFilePath)"
Create influx layer from file C++ libraries 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpInfluxFilePath file path 
.RE
.PP
\fBDate:\fP
.RS 4
20130702 
.RE
.PP

.PP
Definition at line 1572 of file environment\&.cpp\&.
.SS "bool environment::createInitialCatalysisLayerFromFileSTD (stringtmpCatalysisFilePath)"
Catalysis from file using standard C++ libraries 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpSpeciesFilePath file path 
.RE
.PP
\fBDate:\fP
.RS 4
20130702 
.RE
.PP

.PP
Definition at line 1724 of file environment\&.cpp\&.
.SS "bool environment::createInitialCatalysisLayerFromSpecificFileSTD (stringtmpCatalysisFilePath, \fBacs_int\fPtmpActGEN, \fBacs_int\fPtmpActSIM)"
catalysis from file using standard C++ libraries 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpSpeciesFilePath file path 
.RE
.PP
\fBDate:\fP
.RS 4
20130702 
.RE
.PP

.PP
Definition at line 1766 of file environment\&.cpp\&.
.SS "bool environment::createInitialMoleculesPopulationFromFileSTD (stringtmpSpeciesFilePath)"
Initial molecule population creation from file using standard C++ libraries 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpSpeciesFilePath file path 
.RE
.PP
\fBDate:\fP
.RS 4
20130702 
.RE
.PP

.PP
Definition at line 1249 of file environment\&.cpp\&.
.SS "bool environment::createInitialMoleculesPopulationFromSpecificFileSTD (stringtmpSpeciesFilePath, \fBacs_int\fPtmpActGEN, \fBacs_int\fPtmpActSIM)"
Initial molecule population creation from file 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIQString\fP tmpSpeciesFilePath file path Initial molecule population creation\&. Species are uploaed from a SPECIFIC file created using actual generation and simuation 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIQString\fP tmpSpeciesFilePath file path Initial molecule population creation\&. Species are uploaed from a SPECIFIC file created using actual generation and simuation (standard C++ libraries) 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIQString\fP tmpSpeciesFilePath file path 
.RE
.PP

.PP
Definition at line 1478 of file environment\&.cpp\&.
.SS "bool environment::createInitialReactionsLayerFromFileSTD (stringtmpSpeciesFilePath)"
Reactions from file using standard C++ libraries 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpSpeciesFilePath file path 
.RE
.PP
\fBDate:\fP
.RS 4
20130702 
.RE
.PP

.PP
Definition at line 1635 of file environment\&.cpp\&.
.SS "bool environment::createInitialReactionsLayerFromSpecificFileSTD (stringtmpReactionsFilePath, \fBacs_int\fPtmpActGEN, \fBacs_int\fPtmpActSIM)"
Reactions from file using standard C++ libraries 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpSpeciesFilePath file path 
.RE
.PP
\fBDate:\fP
.RS 4
20130702 
.RE
.PP

.PP
Definition at line 1674 of file environment\&.cpp\&.
.SS "bool environment::createNrgBooleanFunctionsFromFileSTD (stringtmpBoolNrgFilePath)"
load energy boolean function (in decimal format) - Standard C++ 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpBoolNrgFilePath file path 
.RE
.PP
\fBDate:\fP
.RS 4
20130702 
.RE
.PP

.PP
Definition at line 1604 of file environment\&.cpp\&.
.SS "bool environment::createReactionsForThisSpecies (\fBacs_longInt\fPtmpsID, \fBacs_int\fPtmpReactionsForThisSpecies, \fBMTRand\fP &tmp_RndDoubleGen, vector< \fBacs_longInt\fP > &tmpIDOfCandidateSpecies, \fBacs_int\fPtmpRctCreationType)"
Creation of all the reactions related to one specific species 
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2011/07/07 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpsID species vector ID 
.br
\fIacs_int\fP tmpReactionsForThisSpecies number of reactions to create for this species 
.br
\fIMTRand&\fP tmp_RndDoubleGen random number generator 
.br
\fIvector<acs_longInt>&\fP tmpIDOfCandidateSpecies ID of the species avalaible for the reaction 
.br
\fIacs_int\fP tmpRctCreationType NEWREACTION or UPGRADEREACTIONS 
.RE
.PP

.PP
Definition at line 525 of file environment\&.cpp\&.
.SS "void environment::decCpxProcedure (\fBacs_int\fPtmp_ID)\fC [inline]\fP"

.PP
Definition at line 298 of file environment\&.h\&.
.SS "void environment::decMolSpeciesProcedure (\fBacs_int\fPtmp_ID)\fC [inline]\fP"

.PP
Definition at line 297 of file environment\&.h\&.
.SS "void environment::decNumberOfCpx (\fBacs_int\fPtmpID)\fC [inline]\fP"

.PP
Definition at line 288 of file environment\&.h\&.
.SS "void environment::decNumberOfCpxMols ()\fC [inline]\fP"

.PP
Definition at line 290 of file environment\&.h\&.
.SS "void environment::decNumberOfMols ()\fC [inline]\fP"

.PP
Definition at line 286 of file environment\&.h\&.
.SS "void environment::decNumberOfNewMols (\fBacs_int\fPtmpID)\fC [inline]\fP"

.PP
Definition at line 295 of file environment\&.h\&.
.SS "void environment::decNumberOfNewSpecies (\fBacs_int\fPtmpID)\fC [inline]\fP"

.PP
Definition at line 293 of file environment\&.h\&.
.SS "void environment::decNumberOfSpecies (\fBacs_int\fPtmpID)\fC [inline]\fP"

.PP
Definition at line 284 of file environment\&.h\&.
.SS "void environment::decOverallLoadedMolsCounter ()\fC [inline]\fP"

.PP
Definition at line 311 of file environment\&.h\&.
.SS "bool environment::devStd ()"

.PP
Definition at line 7370 of file environment\&.cpp\&.
.SS "bool environment::entropy ()"

.PP
Definition at line 7388 of file environment\&.cpp\&.
.SS "\fBacs_double\fP environment::getActualTime () const\fC [inline]\fP"

.PP
Definition at line 153 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getADP () const\fC [inline]\fP"

.PP
Definition at line 169 of file environment\&.h\&.
.SS "string environment::getAlphabet () const\fC [inline]\fP"

.PP
Definition at line 207 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getATP () const\fC [inline]\fP"

.PP
Definition at line 170 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getCleavageCounter () const\fC [inline]\fP"

.PP
Definition at line 226 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getCleavageKC () const\fC [inline]\fP"

.PP
Definition at line 195 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getCleavProb () const\fC [inline]\fP"

.PP
Definition at line 165 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getComplexDegKC () const\fC [inline]\fP"

.PP
Definition at line 198 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getComplexKC () const\fC [inline]\fP"

.PP
Definition at line 196 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getCondensationCounter () const\fC [inline]\fP"

.PP
Definition at line 228 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getCondensationKC () const\fC [inline]\fP"

.PP
Definition at line 197 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getCpxDissCounter () const\fC [inline]\fP"

.PP
Definition at line 231 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getCpxFormCounter () const\fC [inline]\fP"

.PP
Definition at line 230 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getCurrentAttempts () const\fC [inline]\fP"

.PP
Definition at line 158 of file environment\&.h\&.
.SS "int environment::getDebugLevel () const\fC [inline]\fP"

.PP
Definition at line 218 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getDiffusionContribute () const\fC [inline]\fP"

.PP
Definition at line 204 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getEndoCleavageCounter () const\fC [inline]\fP"

.PP
Definition at line 227 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getEndoCondensationCounter () const\fC [inline]\fP"

.PP
Definition at line 229 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getEnergy () const\fC [inline]\fP"

.PP
Definition at line 167 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getFileTimesSavingInterval () const\fC [inline]\fP"

.PP
Definition at line 160 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getgillespieEntropy () const\fC [inline]\fP"

.PP
Definition at line 180 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getGillespieMean () const\fC [inline]\fP"

.PP
Definition at line 178 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getgillespieSD () const\fC [inline]\fP"

.PP
Definition at line 179 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getInflux () const\fC [inline]\fP"

.PP
Definition at line 205 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getK_spont_ass () const\fC [inline]\fP"

.PP
Definition at line 193 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getK_spont_diss () const\fC [inline]\fP"

.PP
Definition at line 192 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getKass () const\fC [inline]\fP"

.PP
Definition at line 187 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getKcpx () const\fC [inline]\fP"

.PP
Definition at line 188 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getKcpxDiss () const\fC [inline]\fP"

.PP
Definition at line 189 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getKdiss () const\fC [inline]\fP"

.PP
Definition at line 186 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getKirrad () const\fC [inline]\fP"

.PP
Definition at line 191 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getKnrg () const\fC [inline]\fP"

.PP
Definition at line 190 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getLastFiringDiskSpeciesID () const\fC [inline]\fP"

.PP
Definition at line 161 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getMAXattempts () const\fC [inline]\fP"

.PP
Definition at line 157 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getMAXhours () const\fC [inline]\fP"

.PP
Definition at line 156 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getMaxLOut () const\fC [inline]\fP"

.PP
Definition at line 200 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getMaxNonCatalyticLength () const\fC [inline]\fP"

.PP
Definition at line 163 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getMoleculeDecayKC () const\fC [inline]\fP"

.PP
Definition at line 199 of file environment\&.h\&.
.SS "vector<\fBspecies\fP> environment::getMoleculesPopulation () const\fC [inline]\fP"

.PP
Definition at line 210 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getMols () const\fC [inline]\fP"

.PP
Definition at line 171 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNcpx () const\fC [inline]\fP"

.PP
Definition at line 175 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNcpxMols () const\fC [inline]\fP"

.PP
Definition at line 176 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNewMols () const\fC [inline]\fP"

.PP
Definition at line 172 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getNgen () const\fC [inline]\fP"

.PP
Definition at line 151 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNnewSpecies () const\fC [inline]\fP"

.PP
Definition at line 174 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getNreactions () const\fC [inline]\fP"

.PP
Definition at line 155 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getNseconds () const\fC [inline]\fP"

.PP
Definition at line 154 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getNsim () const\fC [inline]\fP"

.PP
Definition at line 152 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNspecies () const\fC [inline]\fP"

.PP
Definition at line 173 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNumberOfCatalysis () const\fC [inline]\fP"

.PP
Definition at line 221 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNumberOfGillespieCOPYpossibleRcts () const\fC [inline]\fP"

.PP
Definition at line 222 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNumberOfGillespiePossibleRcts () const\fC [inline]\fP"

.PP
Definition at line 223 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNumberOfReactions () const\fC [inline]\fP"

.PP
Definition at line 220 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getNumberOfTheoreticalSpecies () const\fC [inline]\fP"

.PP
Definition at line 219 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getOverallConcentration () const\fC [inline]\fP"

.PP
Definition at line 162 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getOverallLoadedMolsCounter () const\fC [inline]\fP"

.PP
Definition at line 232 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getRandomSeed () const\fC [inline]\fP"

.PP
Definition at line 209 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getRatioBetweenBackandForw () const\fC [inline]\fP"

.PP
Definition at line 182 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getRatioBetweenNewGillTotGill () const\fC [inline]\fP"

.PP
Definition at line 181 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getRatioSpeciesEnergizable () const\fC [inline]\fP"

.PP
Definition at line 168 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getRctProb () const\fC [inline]\fP"

.PP
Definition at line 164 of file environment\&.h\&.
.SS "vector<\fBreactions\fP> environment::getReactionsLayer () const\fC [inline]\fP"

.PP
Definition at line 217 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getRefillInterval () const\fC [inline]\fP"

.PP
Definition at line 206 of file environment\&.h\&.
.SS "bool environment::getReverseReactions () const\fC [inline]\fP"

.PP
Definition at line 166 of file environment\&.h\&.
.SS "\fBacs_int\fP environment::getSolubilityThreshold () const\fC [inline]\fP"

.PP
Definition at line 201 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getSpontAssCounter () const\fC [inline]\fP"

.PP
Definition at line 234 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getSpontDissCounter () const\fC [inline]\fP"

.PP
Definition at line 233 of file environment\&.h\&.
.SS "bool environment::getSystemExpFlag () const\fC [inline]\fP"

.PP
Definition at line 183 of file environment\&.h\&.
.SS "\fBacs_double\fP environment::getTimeStructuresSavingInterval () const\fC [inline]\fP"

.PP
Definition at line 159 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::getTotalNumberOfComplexes ()"
This Function returns the total amount of MOLECULES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBParameters:\fP
.RS 4
\fIvector<species>*\fP tmpSpeciesvector pointer to tmpSpeciesvector 
.RE
.PP

.PP
Definition at line 3578 of file environment\&.cpp\&.
.SS "\fBacs_longInt\fP environment::getTotalNumberOfComplexSpecies ()"
This Function returns the total amount of COMPLEX SPECIES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBParameters:\fP
.RS 4
\fIvector<species>*\fP tmpSpeciesvector pointer to tmpSpeciesvector 
.RE
.PP

.PP
Definition at line 3557 of file environment\&.cpp\&.
.SS "\fBacs_longInt\fP environment::getTotalNumberOfMolecules ()"
This Function returns the total amount of MOLECULES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBParameters:\fP
.RS 4
\fIvector<species>*\fP tmpSpeciesvector pointer to tmpSpeciesvector 
.RE
.PP

.PP
Definition at line 3533 of file environment\&.cpp\&.
.SS "\fBacs_longInt\fP environment::getTotalNumberOfMonomers ()"
This Function returns the total amount of MONOMERS in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBParameters:\fP
.RS 4
\fIvector<species>*\fP tmpSpeciesvector pointer to tmpSpeciesvector 
.RE
.PP

.PP
Definition at line 3599 of file environment\&.cpp\&.
.SS "\fBacs_longInt\fP environment::getTotalNumberOfPossibleCatalysts ()"
This Function returns the total amount of MOLECULES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBParameters:\fP
.RS 4
\fIvector<species>*\fP tmpSpeciesvector pointer to tmpSpeciesvector 
.RE
.PP

.PP
Definition at line 3510 of file environment\&.cpp\&.
.SS "\fBacs_longInt\fP environment::getTotalNumberOfSpecies ()"
This Function returns the total amount of MOLECULES in the tmpSpeciesvector The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBParameters:\fP
.RS 4
\fIvector<species>*\fP tmpSpeciesvector pointer to tmpSpeciesvector 
.RE
.PP

.PP
Definition at line 3486 of file environment\&.cpp\&.
.SS "\fBacs_int\fP environment::getTotNumberOfChargedMols ()"
Get the total number of charged molecules 
.PP
Definition at line 3619 of file environment\&.cpp\&.
.SS "\fBacs_double\fP environment::getVolume () const\fC [inline]\fP"

.PP
Definition at line 208 of file environment\&.h\&.
.SS "void environment::incCleavageCounter ()\fC [inline]\fP"

.PP
Definition at line 304 of file environment\&.h\&.
.SS "void environment::incCondensationCounter ()\fC [inline]\fP"

.PP
Definition at line 306 of file environment\&.h\&.
.SS "void environment::incCpxDissCounter ()\fC [inline]\fP"

.PP
Definition at line 309 of file environment\&.h\&.
.SS "void environment::incCpxFormCounter ()\fC [inline]\fP"

.PP
Definition at line 308 of file environment\&.h\&.
.SS "void environment::incEndoCleavageCounter ()\fC [inline]\fP"

.PP
Definition at line 305 of file environment\&.h\&.
.SS "void environment::incEndoCondensationCounter ()\fC [inline]\fP"

.PP
Definition at line 307 of file environment\&.h\&.
.SS "void environment::incMolProcedure (\fBacs_int\fPtmp_ID)\fC [inline]\fP"

.PP
Definition at line 299 of file environment\&.h\&.
.SS "void environment::incNumberOfCpx ()\fC [inline]\fP"

.PP
Definition at line 287 of file environment\&.h\&.
.SS "void environment::incNumberOfCpxMols ()\fC [inline]\fP"

.PP
Definition at line 289 of file environment\&.h\&.
.SS "void environment::incNumberOfMols ()\fC [inline]\fP"

.PP
Definition at line 285 of file environment\&.h\&.
.SS "void environment::incNumberOfNewMols (\fBacs_int\fPtmpID)\fC [inline]\fP"

.PP
Definition at line 294 of file environment\&.h\&.
.SS "void environment::incNumberOfNewSpecies (\fBacs_int\fPtmpID)\fC [inline]\fP"

.PP
Definition at line 292 of file environment\&.h\&.
.SS "void environment::incNumberOfSpecies ()\fC [inline]\fP"

.PP
Definition at line 283 of file environment\&.h\&.
.SS "void environment::incOverallLoadedMolsCounter ()\fC [inline]\fP"

.PP
Definition at line 310 of file environment\&.h\&.
.SS "void environment::increaseAttempts ()\fC [inline]\fP"

.PP
Definition at line 346 of file environment\&.h\&.
.SS "void environment::incSpeciesProcedure (\fBacs_int\fPtmp_ID)\fC [inline]\fP"

.PP
Definition at line 300 of file environment\&.h\&.
.SS "void environment::incSpontAssCounter ()\fC [inline]\fP"

.PP
Definition at line 313 of file environment\&.h\&.
.SS "void environment::incSpontDissCounter ()\fC [inline]\fP"

.PP
Definition at line 312 of file environment\&.h\&.
.SS "void environment::inserSubListInSpecies ()"
Insert substrate reactions information in species if complex 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
20130917 
.RE
.PP
\fBAuthor:\fP
.RS 4
Alessandro Filisetti 
.RE
.PP

.PP
Definition at line 2462 of file environment\&.cpp\&.
.SS "bool environment::newSpeciesEvaluationIII (\fBacs_longInt\fPtmpNewSpecies, \fBMTRand\fP &tmp___RndDoubleGen)"
Evaluate new species (Optimized function with new species reactions update process) 
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_int\fP tmpNewSpecies New species ID to evaluate 
.br
\fIMTRand&\fP tmp___RndDoubleGen random number generator 
.RE
.PP

.PP
Definition at line 5851 of file environment\&.cpp\&.
.SS "bool environment::notInverseReactionAlreadyCatalyzed (\fBacs_int\fPtmpRct, \fBacs_longInt\fPtmpID_I, \fBacs_longInt\fPtmpID_II)"
Check if the reaction catalyze both one reaction and the inverted one 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 2578 of file environment\&.cpp\&.
.SS "void environment::nutrientsAmountsFixing ()"
Nutrients amount fixing process\&. The amount of nutrients has to be fixed according to the initial theoretical distribution 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 3685 of file environment\&.cpp\&.
.SS "bool environment::perform_endo_Cleavage (\fBacs_longInt\fPtmpSubstrate, \fBacs_longInt\fPtmpProduct_I, \fBacs_longInt\fPtmpProduct_II, \fBacs_int\fPtmpNRGside, \fBacs_longInt\fPtmpIdReaction, \fBacs_longInt\fPtmpIdCatalysis, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform ENDO_CLEAVAGE reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
2010\&.11\&.08 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpSubstrate Substrate ID 
.br
\fIacs_longInt\fP tmpProduct_I Product 1 ID 
.br
\fIacs_longInt\fP tmpProduct_II Product 2 ID 
.br
\fIacs_int\fP tmpNrgTarget Energy Target --> catalyst loaded, substrate loaded or both 
.br
\fItmpIdReaction\fP Rections ID 
.br
\fItmpIdCatalysis\fP Catalysis ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random number generator 
.RE
.PP

.PP
Definition at line 5258 of file environment\&.cpp\&.
.SS "bool environment::perform_endo_ComplexFormation (\fBacs_longInt\fPtmpCatalyst, \fBacs_longInt\fPtmpSubstrate, \fBacs_longInt\fPtmpCatID, \fBacs_longInt\fPtmpSecSub, \fBacs_int\fPtmpNRGSide, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform ENDO COMPLEX FORMATION reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
2011\&.04\&.13 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpCatalyst Catalyst ID 
.br
\fIacs_longInt\fP tmpSubstrate Substrate ID  Catalysis ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random generator 
.RE
.PP

.PP
Definition at line 5467 of file environment\&.cpp\&.
.SS "bool environment::perform_endo_Condensation (\fBacs_longInt\fPtmpCatalyst, \fBacs_longInt\fPtmpSubstrate, \fBacs_longInt\fPtmpProduct, \fBacs_longInt\fPtmpComplex, \fBacs_int\fPtmpNRGside, \fBacs_longInt\fPtmpIdReaction, \fBacs_longInt\fPtmpIdCatalysis, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform ENDO CONDENSATION reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
2011-02-12 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpCatalyst\fP Catalyst (bound in the complex) ID 
.br
\fItmpSubstrate\fP second (or first, depend on the condensation type) substrate ID 
.br
\fItmpProduct\fP product ID 
.br
\fIacs_longInt\fP tmpComplex Complex ID 
.br
\fIacs_longInt\fP tmpSubstrate Substrate ID 
.br
\fIacs_longInt\fP tmpProduct Product ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random generator 
.RE
.PP

.PP
Definition at line 5015 of file environment\&.cpp\&.
.SS "bool environment::performCleavage (\fBacs_longInt\fPtmpSubstrate, \fBacs_longInt\fPtmpProduct_I, \fBacs_longInt\fPtmpProduct_II, \fBacs_longInt\fPtmpIdReaction, \fBacs_longInt\fPtmpIdCatalysis, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform CLEAVAGE reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
2011\&.02\&.12 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpSubstrate Substrate ID 
.br
\fIacs_longInt\fP tmpProduct_I Product 1 ID 
.br
\fIacs_longInt\fP tmpProduct_II Product 2 ID 
.br
\fItmpIdReaction\fP Rections ID 
.br
\fItmpIdCatalysis\fP Catalysis ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random number generator 
.RE
.PP

.PP
Definition at line 5151 of file environment\&.cpp\&.
.SS "bool environment::performComplexDissociation (\fBacs_longInt\fPtmpComplex, \fBacs_longInt\fPtmpCatalyst, \fBacs_longInt\fPtmpSubstrate, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform COMPLEX DISASSOCIATION reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2010\&.06\&.08 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpComplex Complex ID 
.br
\fIacs_longInt\fP tmpCatalyst Catalyst ID 
.br
\fIacs_longInt\fP tmpSubstrate Substrate ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random generator 
.RE
.PP

.PP
Definition at line 5565 of file environment\&.cpp\&.
.SS "bool environment::performComplexFormation (\fBacs_longInt\fPtmpCatalyst, \fBacs_longInt\fPtmpSubstrate, \fBacs_longInt\fPtmpCatID, \fBacs_longInt\fPtmpSecSub, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform COMPLEX FORMATION reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
2011\&.02\&.13 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpCatalyst Catalyst ID 
.br
\fIacs_longInt\fP tmpSubstrate Substrate ID  Catalysis ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random generator 
.RE
.PP

.PP
Definition at line 5379 of file environment\&.cpp\&.
.SS "bool environment::performCondensation (\fBacs_longInt\fPtmpCatalyst, \fBacs_longInt\fPtmpSubstrate, \fBacs_longInt\fPtmpProduct, \fBacs_longInt\fPtmpComplex, \fBacs_longInt\fPtmpIdReaction, \fBacs_longInt\fPtmpIdCatalysis, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform CONDENSATION reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
2011-02-12 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpComplex Complex ID 
.br
\fIacs_longInt\fP tmpSubstrate Substrate ID 
.br
\fIacs_longInt\fP tmpProduct Product ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random generator 
.RE
.PP

.PP
Definition at line 4898 of file environment\&.cpp\&.
.SS "bool environment::performDETComplexDissociation (\fBacs_double\fPtmpTimeInterval, \fBMTRand\fP &tmp_RndDoubleGen)"
This function perform the deterministic dissociation of the complex 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013-09-18 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpTimeInterval\fP time elapsed since the last reaction 
.br
\fIMTrand\fP &tmp_RndDoubleGen random number generator 
.RE
.PP

.PP
Definition at line 3809 of file environment\&.cpp\&.
.SS "bool environment::performDETMoleculesCharging (\fBacs_double\fPtmpTimeInterval, \fBMTRand\fP &tmp_RndDoubleGen)"
This function perform the pseudo-deterministic molecules charging process 
.PP
\fBVersion:\fP
.RS 4
2\&.6 
.RE
.PP
\fBDate:\fP
.RS 4
2011-02-24 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpTimeInterval\fP time elapsed since the last reaction 
.br
\fIMTrand\fP &tmp_RndDoubleGen random number generator 
.RE
.PP

.PP
Definition at line 3937 of file environment\&.cpp\&.
.SS "bool environment::performEnergyEfflux (\fBMTRand\fP &tmp__RndDoubleGen)"
Perform ENERGY EFFLUX reaction 
.PP
\fBVersion:\fP
.RS 4
2\&.4\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2010-06-27 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIMTRand&\fP tmp__RndDoubleGen random number generator 
.RE
.PP

.PP
Definition at line 4611 of file environment\&.cpp\&.
.SS "bool environment::performMoleculeEfflux (\fBacs_longInt\fPtmpSpecies, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform MOLECULE EFFLUX reaction 
.PP
\fBVersion:\fP
.RS 4
2\&.5\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2010-06-27 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpSpecies Species ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random generator 
.RE
.PP

.PP
Definition at line 4531 of file environment\&.cpp\&.
.SS "bool environment::performMoleculesEfflux (\fBacs_double\fPtmpTimeInterval, \fBMTRand\fP &tmp_RndDoubleGen)"
This function perform the deterministic molecules efflux process 
.PP
\fBVersion:\fP
.RS 4
2\&.5 
.RE
.PP
\fBDate:\fP
.RS 4
2010-06-25 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpTimeInterval\fP time elapsed since the last reaction 
.br
\fIMTrand\fP &tmp_RndDoubleGen random number generator 
.RE
.PP

.PP
Definition at line 4369 of file environment\&.cpp\&.
.SS "bool environment::performOPTGillespieComputation (\fBMTRand\fP &tmpRndDoubleGen, clock_t &tmpTimeElapsed, \fBacs_int\fPtmpActGEN, \fBacs_int\fPtmpActSIM, \fBacs_int\fPtmpActSTEP, stringtmpStoringPath)"
Perform all the gillespie algorithm procedure (OPTIMIZED VERSION) 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013\&.09\&.17 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpRndDoubleGen\fP random numbers generator 
.br
\fItmpTimeElapsed\fP Computation time elapsed from the T0 
.br
\fItmpActGEN\fP actual generation 
.br
\fItmpActSIM\fP actual simulation 
.br
\fItmpActSTEP\fP actual step (reaction) 
.br
\fItmpStoringPath\fP path where results are stored 
.RE
.PP

.PP
Definition at line 2668 of file environment\&.cpp\&.
.SS "bool environment::performReaction (\fBacs_longInt\fPreaction_u, \fBMTRand\fP &tmp_RndDoubleGen, \fBacs_int\fPtmp_ActGEN, \fBacs_int\fPtmp_ActSIM, \fBacs_int\fPtmp_ActSTEP, stringtmp_StoringPath)"
Perform the reaction after the Gillespie computation 
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2013-10-29 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP reaction_u reaction ID in Gillespie structure 
.br
\fIMTRand&\fP tmp_RndDoubleGen Random number generator 
.br
\fIacs_int\fP tmp_ActGEN Current generation 
.br
\fIacs_int\fP tmp_ActSIM Current generation 
.br
\fIacs_int\fP tmp_ActSTEP Current step (reaction) 
.br
\fIstring\fP Storing directory 
.RE
.PP

.PP
Definition at line 4668 of file environment\&.cpp\&.
.SS "bool environment::performRefill (\fBacs_double\fPtmpTimeSinceTheLastInFlux, \fBacs_double\fPtmpMinimalTimeForOneMols, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform Refill according to the time interval and the total amount of refill 
.PP
\fBVersion:\fP
.RS 4
2\&.4 
.RE
.PP
\fBDate:\fP
.RS 4
2010\&.06\&.10 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpTimeSinceTheLastInFlux\fP time elapsed since the last influx of at least one molcolule 
.br
\fItmpMinimalTimeForOneMols\fP time necessary to feed to the system one molecule 
.br
\fItmp__RndDoubleGen\fP random number generator 
.RE
.PP

.PP
Definition at line 3718 of file environment\&.cpp\&.
.SS "void environment::performSingleGilleSpieIntroduction (\fBacs_longInt\fPtmpAmountI, \fBacs_longInt\fPtmpAmountII, \fBacs_longInt\fPtmpIDI, \fBacs_longInt\fPtmpIDII, \fBacs_longInt\fPtmpIDCatalysis, \fBacs_int\fPtmp__rctType, \fBacs_longInt\fPtmpMol_I, \fBacs_longInt\fPtmpMol_II, \fBacs_longInt\fPtmpMol_III, \fBacs_longInt\fPtmpMol_IV, \fBacs_int\fPtmp_NRGDirection, \fBacs_longInt\fPtmpRctID, booltmpSameSpeciesControl)"
Compute and introduct a single Gillespie entry within the Gillespie Structure 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
20110222 
.RE
.PP

.PP
Definition at line 3314 of file environment\&.cpp\&.
.SS "bool environment::performSpontaneousCleavage (\fBacs_longInt\fPtmpReaction, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform SPONTANEOUS CLEAVAGE reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013\&.10\&.28 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpReaction Reaction ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random generator 
.RE
.PP

.PP
Definition at line 5657 of file environment\&.cpp\&.
.SS "bool environment::performSpontaneousCondensation (\fBacs_longInt\fPtmpReaction, \fBMTRand\fP &tmp__RndDoubleGen)"
Perform SPONTANEOUS CONDENSATION reaction 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013-10-28 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpReaction Reaction ID 
.br
\fIMTRand&\fP tmp__RndDoubleGen random generator 
.RE
.PP

.PP
Definition at line 5727 of file environment\&.cpp\&.
.SS "void environment::printAllChargeMols ()"
Print all the energized molecules  1\&.0 
.PP
\fBDate:\fP
.RS 4
2010-11-14 
.RE
.PP

.PP
Definition at line 6381 of file environment\&.cpp\&.
.SS "void environment::printAllSpeciesIdAndSequence ()"
Show all the species with their ID 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6325 of file environment\&.cpp\&.
.SS "void environment::printGillespieStructure ()"
Show all the Gillespie Structure 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6353 of file environment\&.cpp\&.
.SS "void environment::printInitialCondition ()"
Show all initial species in table format 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6267 of file environment\&.cpp\&.
.SS "void environment::printNutrientsAndProbability ()"
This Function populates two vectors containing all the nutrients and all the probabilities for the influx selected species from the firing disk according to the max length of the influx This function print to monitor the content of the vectors nutrientsForInflux and nutrientsProb2BeSelected 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2010-05-17 
.RE
.PP

.PP
Definition at line 3660 of file environment\&.cpp\&.
.SS "bool environment::removeChargeMolFromList (\fBacs_int\fPtmpSpeciesID)"
Perform vector unchargedIDlist update removing a new charge molecule vectors unchargedIDlist and cumUnchargedAmountList are involved 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2010-10-10 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_int\fP tmpSpeciesID Specie to uncharge 
.RE
.PP

.PP
Definition at line 4265 of file environment\&.cpp\&.
.SS "void environment::resetCleavageCounter ()\fC [inline]\fP"

.PP
Definition at line 315 of file environment\&.h\&.
.SS "void environment::resetConcentrationToInitialConditions ()"
set the concentrations to the initial values and reset internal statistics and counter 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6472 of file environment\&.cpp\&.
.SS "void environment::resetCondensationCounter ()\fC [inline]\fP"

.PP
Definition at line 317 of file environment\&.h\&.
.SS "void environment::resetCpxDissCounter ()\fC [inline]\fP"

.PP
Definition at line 321 of file environment\&.h\&.
.SS "void environment::resetCpxFormCounter ()\fC [inline]\fP"

.PP
Definition at line 320 of file environment\&.h\&.
.SS "void environment::resetEndoCleavageCounter ()\fC [inline]\fP"

.PP
Definition at line 316 of file environment\&.h\&.
.SS "void environment::resetEndoCondensationCounter ()\fC [inline]\fP"

.PP
Definition at line 318 of file environment\&.h\&.
.SS "void environment::resetOverallLoadedMolsCounter ()\fC [inline]\fP"

.PP
Definition at line 319 of file environment\&.h\&.
.SS "void environment::resetReactionsCounter ()\fC [inline]\fP"

.PP
Definition at line 325 of file environment\&.h\&.
.SS "void environment::resetSpontAssCounter ()\fC [inline]\fP"

.PP
Definition at line 323 of file environment\&.h\&.
.SS "void environment::resetSpontDissCounter ()\fC [inline]\fP"

.PP
Definition at line 322 of file environment\&.h\&.
.SS "\fBacs_longInt\fP environment::returnPosReactionAlreadyPresent (\fBacs_int\fPtmpReactionType, \fBacs_longInt\fPtmpIds_I, \fBacs_longInt\fPtmpIds_II, \fBacs_longInt\fPtmpIds_III)"
Return the reaction ID if the reaction is already present, otherwise it returns the new reaction ID 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_int\fP tmpReactionType rection type (cleavage or condensation) 
.br
\fIacs_longInt\fP tmpIds_I species I ID 
.br
\fIacs_longInt\fP tmpIds_II species II ID 
.br
\fIacs_longInt\fP tmpIds_III species III ID 
.RE
.PP

.PP
Definition at line 1904 of file environment\&.cpp\&.
.SS "\fBacs_longInt\fP environment::returnPosSpeciesAlreadyPresent (stringtmpNewSequence)"
This functions returns the ID of the species whether this one is already present, otherwise the new ID is created as the number of elements in the species vector 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpNewSequence\fP New sequence to evaluate 
.br
\fIMTRand&\fP tmp_RndDoubleGen random number generator 
.br
\fItmpNewSpeciesLength\fP Lenght of the species 
.RE
.PP

.PP
Definition at line 1874 of file environment\&.cpp\&.
.SS "bool environment::saveCatalysisStructureSTD (\fBacs_int\fPtmpCurrentGen, \fBacs_int\fPtmpCurrentSim, \fBacs_int\fPtmpCurrentStep, stringtmpStoringPath)"
Save the catalysis structures in a file named catalysis_[currentSims]_[currentStep]\&.csv\&. This is file is equal to the acs_catalysis\&.csv input file\&. Standard C++ The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6978 of file environment\&.cpp\&.
.SS "bool environment::saveConfigurationFileSTD (stringtmpStoringPath)"
Save a file with the configuration parameters 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 6613 of file environment\&.cpp\&.
.SS "bool environment::saveInfluxStructureSTD (stringtmpStoringPath)"
Save influx structure on file, standard C++ 
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP saveInfluxStructure(QString tmpStoringPath); 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013-047-03 
.RE
.PP

.PP
Definition at line 6783 of file environment\&.cpp\&.
.SS "bool environment::saveLivingSpeciesAmountSTD (\fBacs_int\fPtmp__CurrentGen, \fBacs_int\fPtmp__CurrentSim, stringtmp__StoringPath)"
Save living species total AMOUNT in a file named livingAmount_[CurrentGen]_[currentSim]\&.csv\&. The file is saved in the directory indicated as a second parameter in the run command - Standard C++ 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 7242 of file environment\&.cpp\&.
.SS "bool environment::saveLivingSpeciesConcentrationSTD (\fBacs_int\fPtmp__CurrentGen, \fBacs_int\fPtmp__CurrentSim, stringtmp__StoringPath)"
Save living species total CONCENTRATION in a file named livingAmount_[CurrentGen]_[currentSim]\&.csv\&. The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 7308 of file environment\&.cpp\&.
.SS "bool environment::saveLivingSpeciesIDSTD (\fBacs_int\fPtmp__CurrentGen, \fBacs_int\fPtmp__CurrentSim, \fBacs_int\fPtmp__CurrentStep, stringtmp__StoringPath)"
Save living species in a file named living_species_[currentSim]\&.csv\&. Standard C++ The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 7181 of file environment\&.cpp\&.
.SS "bool environment::saveNrgBoolFncStructureSTD (stringtmpStoringPath)"
Save Energetic Boolean Function on file, standard C++ 
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP saveInfluxStructure(QString tmpStoringPath); 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013-047-03 
.RE
.PP

.PP
Definition at line 6821 of file environment\&.cpp\&.
.SS "bool environment::saveReactionsParametersSTD (\fBacs_int\fPtmp__CurrentGen, \fBacs_int\fPtmp__CurrentSim, \fBacs_int\fPtmp__CurrentStep, stringtmp__StoringPath, \fBacs_int\fPtmpRctType, \fBacs_longInt\fPtmpCat, \fBacs_longInt\fPtmpMol_I, \fBacs_longInt\fPtmpMol_II, \fBacs_longInt\fPtmpMol_III)"
Save the reactions parameters in a file named reactions_parameters_[currentSim]\&.csv\&. The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 7122 of file environment\&.cpp\&.
.SS "bool environment::saveReactionsStructureSTD (\fBacs_int\fPtmpCurrentGen, \fBacs_int\fPtmpCurrentSim, \fBacs_int\fPtmpCurrentStep, stringtmpStoringPath)"
Save the reactions structures in a file named reactions_[currentSims]_[currentStep]\&.csv\&. This is file is equal to the acs_reactions\&.csv input file\&. The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6924 of file environment\&.cpp\&.
.SS "bool environment::saveSpeciesStructureSTD (\fBacs_int\fPtmpCurrentGen, \fBacs_int\fPtmpCurrentSim, \fBacs_int\fPtmpCurrentStep, stringtmpStoringPath)"
Save the species structures in a file named species_[currentSims]_[currentStep]\&.csv\&. This is file is equal to the acs_species\&.csv input file\&. C++ standard The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 6859 of file environment\&.cpp\&.
.SS "bool environment::saveTimesSTD (\fBacs_int\fPtmpCurrentGen, \fBacs_int\fPtmpCurrentSim, \fBacs_int\fPtmpCurrentStep, stringtmpStoringPath)"
Save the reactions times in a file named times_[currentSim]\&.csv\&. Standard C++ The file is saved in the directory indicated as a second parameter in the run command 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 7035 of file environment\&.cpp\&.
.SS "\fBacs_int\fP environment::selectWhetherCleavageOrCond (\fBMTRand\fP &tmp__RndDoubleGen)"
Select reaction type (cleavage or condensation) according to the cleavage probability 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_int\fP tmpTotalNumberOfReactions Total number of conceivable reactions 
.br
\fIacs_double\fP tmpRctsProb reaction probability 
.RE
.PP

.PP
Definition at line 1227 of file environment\&.cpp\&.
.SS "void environment::setActualTime (\fBacs_double\fPtmpActualTime)\fC [inline]\fP"

.PP
Definition at line 343 of file environment\&.h\&.
.SS "void environment::setLivingSpeciesIDsAndAmounts ()"
This function populates to lists, the first containing all the living species ID and the second one containing the cumulative number of living species 
.PP
\fBVersion:\fP
.RS 4
2\&.5\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
2010-11-11 
.RE
.PP

.PP
Definition at line 4176 of file environment\&.cpp\&.
.SS "void environment::setNotChargedAndChargedSpeciesIDsAndAmounts ()"
This function populates to lists, the first one contains the IDs of the uncharged mols and the second one contains the cumulative amount of uncharged molecules 
.PP
\fBVersion:\fP
.RS 4
2\&.5\&.3 
.RE
.PP
\fBDate:\fP
.RS 4
2011-02-22 
.RE
.PP

.PP
Definition at line 4217 of file environment\&.cpp\&.
.SS "bool environment::setSolubility (\fBacs_int\fPtmpNewSpeciesLength, \fBMTRand\fP &tmpRndDoubleGen)"
Create the precipitation constant renforcement according to the species length 
.PP
\fBVersion:\fP
.RS 4
2\&.5\&.1 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItmpPreEnh\fP precipitation enhancement from parameters 
.br
\fIMTRand&\fP tmp_RndDoubleGen random number generator 
.br
\fItmpNewSpeciesLength\fP Lenght of the species 
.RE
.PP

.PP
Definition at line 1840 of file environment\&.cpp\&.
.SS "void environment::showGillEngagementInSpecies ()"
Function to show the Gillespie engagement of each species\&. 
.PP
\fBVersion:\fP
.RS 4
: 1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
: 20131031 
.RE
.PP
\fBAuthor:\fP
.RS 4
: Alessandro Filisetti 
.RE
.PP

.PP
Definition at line 2559 of file environment\&.cpp\&.
.SS "void environment::showGlobalParameter ()"
Shows all parameters uploaded from the configuration file 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6174 of file environment\&.cpp\&.
.SS "void environment::showSubListInSpecies ()"
Function to show the substrates list of the complex species 
.PP
Definition at line 2523 of file environment\&.cpp\&.
.SS "void environment::storeInitialStructures ()"
Store initial structures into storing variables 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6567 of file environment\&.cpp\&.
.SS "bool environment::structureCoherenceCheckUp ()"
This function check the coherence of the data structures\&. IF IT FAULTS THE SYSTEM RETURNS ERROR!!! IT IS VERY RECOMMENDED RUN THIS FUNCTION ALWAYS AFTER THE INITIALIZATION 
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2011-04-13 
.RE
.PP

.PP
Definition at line 2004 of file environment\&.cpp\&.
.SS "void environment::unchargeMolProcess (\fBacs_int\fPtmp_ID)\fC [inline]\fP"

.PP
Definition at line 302 of file environment\&.h\&.
.SS "bool environment::updateReactions (\fBacs_longInt\fPtmpIDtoUpdate, \fBacs_longInt\fPtmpNewSpecies, \fBacs_int\fPtmpRctType, vector< \fBacs_longInt\fP > &tmp_AlreadyEvaluatedSpeciesVector, \fBMTRand\fP &tmp_RndDoubleGen)"
Old Species Reactions and Catalysis update process 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/30 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_longInt\fP tmpIDtoUpdate ID of the species to update 
.br
\fIacs_longInt\fP ID of the new species involved in the reactions to update 
.br
\fIacs_int\fP tmpRctType Reaction type, namely cleavage or condensation 
.br
\fIMTRand&\fP tmp____RndDoubleGen Random number generator 
.RE
.PP

.PP
Definition at line 941 of file environment\&.cpp\&.
.SS "void environment::updateSpeciesAges ()"
Update the species age 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 6125 of file environment\&.cpp\&.
.SS "string environment::zeroBeforeStringNumberSTD (\fBacs_int\fPtmpTotN, \fBacs_int\fPtmpCurrentN)"
This function creates a chain of zero as STRING according to tmpTotN and tmpCurrent N in order to make possible a sorting (e\&.g\&. tmpTotN = 1000, tmpCurrentN = 3, return 0003 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIacs_int\fP tmpTotN Total N 
.br
\fIacs_int\fP tmpCurrentN current N 
.RE
.PP

.PP
Definition at line 6590 of file environment\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
