.TH "/Users/alessandrofilisetti/Dropbox/ACS_SVN/carness/carness_simulator/_analysis/fromWithin2Between.py" 3 "Wed Apr 3 2013" "Version 3.2 (20130403.51)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Dropbox/ACS_SVN/carness/carness_simulator/_analysis/fromWithin2Between.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBfromWithin2Between\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfromWithin2Between\&.zeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBfromWithin2Between\&.zeroSIM\fP zeroBeforeStrNum(\fBi\fP,numSim)"
.br
.ti -1c
.RI "tuple \fBfromWithin2Between\&.zeroGEN\fP zeroBeforeStrNum(\fBj\fP,numGen)"
.br
.ti -1c
.RI "string \fBfromWithin2Between\&.folderNew\fP 's_'"
.br
.ti -1c
.RI "tuple \fBfromWithin2Between\&.resdir\fP os\&.path\&.join(os\&.curdir, 'res')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
