.TH "fromWithin2Between" 3 "Sat Oct 26 2013" "Version 4.8 (20131026.60)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fromWithin2Between \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBzeroSIM\fP = \fBzeroBeforeStrNum\fP(\fBi\fP,numSim)"
.br
.ti -1c
.RI "tuple \fBzeroGEN\fP = \fBzeroBeforeStrNum\fP(\fBj\fP,numGen)"
.br
.ti -1c
.RI "string \fBfolderNew\fP = 's_'"
.br
.ti -1c
.RI "tuple \fBresdir\fP = os\&.path\&.join(os\&.curdir, 'res')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def fromWithin2Between\&.zeroBeforeStrNum (tmpl, tmpL)"

.PP
Definition at line 10 of file fromWithin2Between\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "string fromWithin2Between\&.folderNew = 's_'"

.PP
Definition at line 41 of file fromWithin2Between\&.py\&.
.SS "tuple fromWithin2Between\&.resdir = os\&.path\&.join(os\&.curdir, 'res')"

.PP
Definition at line 52 of file fromWithin2Between\&.py\&.
.SS "tuple fromWithin2Between\&.zeroGEN = \fBzeroBeforeStrNum\fP(\fBj\fP,numGen)"

.PP
Definition at line 39 of file fromWithin2Between\&.py\&.
.SS "tuple fromWithin2Between\&.zeroSIM = \fBzeroBeforeStrNum\fP(\fBi\fP,numSim)"

.PP
Definition at line 35 of file fromWithin2Between\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
