.TH "/Users/alessandrofilisetti/Dropbox/ACS_SVN/carness/carness_simulator/_analysis/generalStatistics.py" 3 "Mon Mar 12 2012" "Version 3.2 (20120312.46)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Dropbox/ACS_SVN/carness/carness_simulator/_analysis/generalStatistics.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgeneralStatistics\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBgeneralStatistics\&.initTime\fP = time\&.time()"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.StrPath\fP = sys\&.argv[1]"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.threshold\fP = float(sys\&.argv[2])"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.singleGraphCreation\fP = sys\&.argv[3]"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.speciesToObserve\fP = np\&.array([[1,2,3,4]])"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.tmpDirs\fP = sort(os\&.listdir(StrPath))"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.samples\fP = 0"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.nFolders\fP = 0"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.speciesFilesInThisSim\fP = 'species_*'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.speciesfileslist\fP = sorted(glob\&.glob(speciesFilesInThisSim))"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.paramFile\fP = 'acsm2s\&.conf'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.fid\fP = open(paramFile, '\fBr\fP')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.strLine\fP = line\&.split('=')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.gens\fP = int(strLine[1])"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.sims\fP = int(strLine[1])"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.rcts\fP = int(strLine[1])"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.nsec\fP = int(strLine[1])"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallTimes\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.timesFrames\fP = range(0,samples)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallLivSpe\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallMols\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallCpx\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallCpxCopies\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallDeath\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallnewSpecies\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallmaxAmount\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallminAmount\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallmeanAmount\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallmedianAmount\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallmaxL\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallminL\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallmeanL\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallmedianL\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallLoadedSpecies\fP = np\&.zeros((samples,nFolders))"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.ndn\fP = '_0_allStatResults_'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.newdirAllResults\fP = os\&.path\&.join(os\&.curdir, ndn)"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.dirCount\fP = 0"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.rgens\fP = fl\&.zeroBeforeStrNum(1, 1)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.rsims\fP = fl\&.zeroBeforeStrNum(1, 1)"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.ndnII\fP = '__10_stastisticFiles_'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.newdir\fP = os\&.path\&.join(os\&.curdir, ndnII)"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.influxSpeciesFile\fP = '_acsinflux\&.csv'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.fidflux\fP = open(influxSpeciesFile, '\fBr\fP')"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.indexIn\fP = []"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.timesfileslist\fP = sorted(glob\&.glob('times_*'))"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.simulationID\fP = 1"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.rrcts\fP = fl\&.zeroBeforeStrNum(0, rcts)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.rgen\fP = fl\&.zeroBeforeStrNum(genID, gens)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.species3DSIZEamountLAST\fP = np\&.array([[int(0), int(0), float(0), int(0)]])"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.speciesFileID\fP = 1"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.rsim\fP = fl\&.zeroBeforeStrNum(simulationID, \fBsims\fP)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.origDir\fP = os\&.getcwd()"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.statDir\fP = os\&.path\&.join(os\&.curdir, newdir)"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.outFnameStat\fP = '\fB_\fP'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.statfilesFlag\fP = os\&.path\&.isfile(outFnameStat)"
.br
.ti -1c
.RI "float \fBgeneralStatistics\&.rctIDshow\fP = 1\&.0"
.br
.ti -1c
.RI "float \fBgeneralStatistics\&.rctIDshowNoSave\fP = 1\&.0"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.rctID\fP = 1"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.previousTime\fP = 0"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.filename\fP = '01_gillespie_'"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.stat\fP = []"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.species3Damount\fP = []"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.species3DSIZEamount\fP = []"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.concSpeciesHystory\fP = np\&.zeros((samples,\fBsize\fP(speciesToObserve)))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.concSpeciesRelativeHystory\fP = np\&.zeros((samples,\fBsize\fP(speciesToObserve)))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.totTimes\fP = np\&.zeros((samples,\fBsize\fP(speciesToObserve)))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.strs\fP = string\&.split(root, '\fB_\fP')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.rctNumber\fP = int(strs[len(strs)-1])"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.sngSpFileFid\fP = open(sngSpFile, '\fBr\fP')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.speciesTable\fP = sngSpFileFid\&.readlines()"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.sID\fP = []"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.loadedSpecies\fP = []"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.Kdeg\fP = array(Kdeg)"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.sizes\fP = []"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.seqID\fP = 0"
.br
.ti -1c
.RI "\fBgeneralStatistics\&.realTheshold\fP = \fBthreshold\fP"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.totAmount\fP = 0"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.eqLen\fP = where(species3DSIZEamount[:,0] == len(seq))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.eqLenLAST\fP = where(species3DSIZEamountLAST[:,0] == len(seq))"
.br
.ti -1c
.RI "list \fBgeneralStatistics\&.stoPosition\fP = speciesToObserve[0,:]"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MSizes\fP = int(\fBmax\fP(sizes))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.mSizes\fP = int(min(sizes))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.avSizes\fP = float(mean(sizes))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.meSizes\fP = float(median(sizes))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallControlledSpecies\fP = float(\fBsum\fP(concSpeciesHystory[speciesFileID-1,:]))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallControlledSpeciesOverTotConc\fP = overallControlledSpecies/float(\fBsum\fP(amount[cutPnt==0]))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.overallControlledSpeciesOverTotPlusCpxConc\fP = overallControlledSpecies/float(\fBsum\fP(amount[:]))"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.statControlled\fP = np\&.vstack([statControlled,(overallControlledSpecies,overallControlledSpeciesOverTotConc,overallControlledSpeciesOverTotPlusCpxConc)])"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.finalStatDir\fP = '__10_stastisticFiles_'"
.br
.ti -1c
.RI "\fBgeneralStatistics\&.species3DNoInflux\fP = species3Damount"
.br
.ti -1c
.RI "\fBgeneralStatistics\&.species3DSIZEnoInflux\fP = species3DSIZEamount"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.outFname3DSize\fP = '\fB_\fP'"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.outFname3DSizeGrouped\fP = '\fB_\fP'"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.outFname3DSizeGroupedLAST\fP = '\fB_\fP'"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.outFname3DSizeGroupedLASTtot\fP = '\fB_\fP'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.saveFileStat\fP = open(outFnameStat, 'w')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.saveFile3Dsize\fP = open(outFname3DSize, 'w')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.saveFile3DsizeGR\fP = open(outFname3DSizeGrouped, 'w')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.saveFile3DsizeGRLAST\fP = open(outFname3DSizeGroupedLAST, 'w')"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.outFnameStatToObserve\fP = '\fB_\fP'"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.outFnameToObserve\fP = '\fB_\fP'"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.outFnameRatioToObserve\fP = '\fB_\fP'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.saveFileStatKeepInEye\fP = open(outFnameStatToObserve, 'w')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.saveFileKeepInEye\fP = open(outFnameToObserve, 'w')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.saveFileRatioKeepInEye\fP = open(outFnameRatioToObserve, 'w')"
.br
.ti -1c
.RI "string \fBgeneralStatistics\&.sngStatFile\fP = '\fB_\fP'"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.sngStatFileFid\fP = open(sngStatFile, '\fBr\fP')"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.linesID\fP = 0"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.Time\fP = float(tmpTime)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.LivSpe\fP = int(tmpLivSpe)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.Mols\fP = float(tmpMols)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.Death\fP = int(tmpDeath)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.NewS\fP = int(tmpNewS)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MaxA\fP = float(tmpMaxA)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MinA\fP = float(tmpMinA)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MeanA\fP = float(tmpMeanA)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MedianA\fP = float(tmpMedianA)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.Cpx\fP = int(tmpCpx)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.CpxCopies\fP = float(tmpCpxCopies)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MaxL\fP = int(tmpMaxL)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MinL\fP = int(tmpMinL)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MeanL\fP = float(tmpMeanL)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.MedianL\fP = float(tmpMedianL)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.loadedConc\fP = float(tmpLoadedConc)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.statfileslastFID\fP = open(outFname3DSizeGroupedLAST, '\fBr\fP')"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.normTimes\fP = np\&.mean(overallTimes,1)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.normTimesStd\fP = np\&.std(overallTimes,1)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.normY\fP = np\&.mean(overallLivSpe,1)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.normYstd\fP = np\&.std(overallLivSpe,1)"
.br
.ti -1c
.RI "tuple \fBgeneralStatistics\&.endTime\fP = time\&.time()"
.br
.ti -1c
.RI "int \fBgeneralStatistics\&.minutes\fP = 60"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
