.TH "/Users/alessandrofilisetti/Documents/GIT/carness/gillespie.h" 3 "Tue Oct 1 2013" "Version 4.7 (20131001.59)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/gillespie.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'acs_headers\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgillespie\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
