.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/KillSpam.m" 3 "Thu Sep 19 2013" "Version 4.5 (20130919.57)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/KillSpam.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBKillSpam\fP (\fBparam\fP) \fBcurrentDir\fP"
.br
.ti -1c
.RI "\fBcd\fP (\fBparam\&.tmpPath\fP)"
.br
.ti -1c
.RI "\fBdisp\fP ('|-----------------------------------------|')"
.br
.ti -1c
.RI "\fBdisp\fP ('|-Killer \fBand\fP Spammer \fBanalysis\fP is started|')"
.br
.ti -1c
.RI "READ ALL THE DIRECTORY 
.br
CONTAINING SIMULATIONS \fBif\fP \fB~isdir\fP ('0_statistics') mkdir('0_statistics')"
.br
.ti -1c
.RI "\fBcd\fP ('0_statistics')"
.br
.ti -1c
.RI "\fBfclose\fP (\fBfid\fP)"
.br
.ti -1c
.RI "\fBcd\fP ('\&.\&./')"
.br
.ti -1c
.RI "\fBdisp\fP (strcat('|-Folder: ', \fBsimDirs\fP(\fBx\fP)\&.\fBname\fP,'/res\&.\&.\&.'))"
.br
.ti -1c
.RI "\fBbreak\fP \fBend\fP \fBreactionsMatrix\fP (\fBcontinua\fP, 1:6)"
.br
.ti -1c
.RI "\fBcleavagesMatrix\fP (\fBcleavages\fP, 1:6)"
.br
.ti -1c
.RI "\fBcondensationsMatrix\fP (\fBcondensations\fP, 1:6)"
.br
.ti -1c
.RI "\fBend\fP \fBcatalysisMatrix\fP (\fBcontinua\fP, 1:4)"
.br
.ti -1c
.RI "\fBoutliersMatrix\fP (\fBoutRows\fP, 1:6)"
.br
.ti -1c
.RI "\fBif\fP ((\fBoutliersMatrix\fP(\fBi\fP, 2)==1)&&(\fBcheck2\fP==1 &&\fBcheck3\fP==1))||(\fBoutliersMatrix\fP(\fBi\fP"
.br
.ti -1c
.RI "\fBkillersMatrix\fP (\fBkillRows\fP, 1:6)"
.br
.ti -1c
.RI "\fBkillerCatalysts\fP (\fBKCRows\fP, 1)"
.br
.ti -1c
.RI "\fBkillerCatalysts\fP (\fBKCRows\fP, 2)"
.br
.ti -1c
.RI "\fBkillerCatalysts\fP (\fBKCRows\fP, 3)"
.br
.ti -1c
.RI "id \fBKSRows\fP ()"
.br
.ti -1c
.RI "\fBif\fP \fBoutliersMatrix\fP (\fBi\fP, 2)"
.br
.ti -1c
.RI "\fBKSMatrix\fP (\fBKSRows\fP, 1:6)"
.br
.ti -1c
.RI "\fBKSMatrix\fP (\fBi\fP,:)"
.br
.ti -1c
.RI "\fBKSCatalysts\fP (\fBKSCRows\fP, 1)"
.br
.ti -1c
.RI "\fBKSCatalysts\fP (\fBKSCRows\fP, 2)"
.br
.ti -1c
.RI "\fBKSCatalysts\fP (\fBKSCRows\fP, 3)"
.br
.ti -1c
.RI "\fBif\fP ((\fBoutliersMatrix\fP(\fBi\fP, 2)==1)&&(\fBcheck2\fP==0 &&\fBcheck3\fP==0))||(\fBoutliersMatrix\fP(\fBi\fP"
.br
.ti -1c
.RI "\fBSpammersMatrix\fP (\fBSpamRows\fP, 1:6)"
.br
.ti -1c
.RI "\fBif\fP \fBSpamRows\fP \fBSpammersMatrix\fP (:, 7)"
.br
.ti -1c
.RI "\fBSpammersMatrix\fP (\fBi\fP,:)"
.br
.ti -1c
.RI "\fBelse\fP \fBSpammersMatrix\fP (\fBi\fP, 7)"
.br
.ti -1c
.RI "\fBspammerCatalysts\fP (\fBKSCRows\fP, 1)"
.br
.ti -1c
.RI "\fBspammerCatalysts\fP (\fBKSCRows\fP, 2)"
.br
.ti -1c
.RI "\fBspammerCatalysts\fP (\fBKSCRows\fP, 3)"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'NET%d\\n\\n', \fBx\fP)"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'KILLERS\\n\\n')"
.br
.ti -1c
.RI "\fBend\fP \fBfprintf\fP (\fBfid\fP,'\\n\\n')"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'Catalysts\\n\\n')"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'%d\\t', \fBkillerCatalysts\fP(\fBi\fP, 2))"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'%d\\n\\n', \fBkillerCatalysts\fP(\fBi\fP, 3))"
.br
.ti -1c
.RI "\fBend\fP \fBfprintf\fP (\fBfid\fP,'KILLERS-SPAMMERS\\n\\n')"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'%d\\t', \fBKSCatalysts\fP(\fBKSCRows\fP, 2))"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'%d\\n\\n', \fBKSCatalysts\fP(\fBKSCRows\fP, 3))"
.br
.ti -1c
.RI "\fBend\fP \fBfprintf\fP (\fBfid\fP,'SPAMMERS\\n\\n')"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'%d\\t', \fBspammerCatalysts\fP(\fBSCRows\fP, 2))"
.br
.ti -1c
.RI "\fBfprintf\fP (\fBfid\fP,'%d\\n\\n', \fBspammerCatalysts\fP(\fBSCRows\fP, 3))"
.br
.ti -1c
.RI "\fBend\fP \fBcd\fP (\fBcurrentDir\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBend\fP \fBtmpFolder\fP = strcat('*',\fBparam\&.simFolder\fP,'*')"
.br
.ti -1c
.RI "\fBsimDirs\fP = dir(\fBtmpFolder\fP)"
.br
.ti -1c
.RI "\fBfid\fP = fopen('ALL_results_TS1\&.txt','w')"
.br
.ti -1c
.RI "for \fBx\fP"
.br
.ti -1c
.RI "\fBblocked\fP = 0:\fBparam\&.lastSpecies\fP"
.br
.ti -1c
.RI "creating \fBreactions\fP matrix \fBrFiles\fP = dir('\fBreactions\fP*')"
.br
.ti -1c
.RI "\fBreactionsFile\fP = \fBrFiles\fP(length(\fBrFiles\fP)-1)\&.\fBname\fP"
.br
.ti -1c
.RI "\fBcontinua\fP = 1"
.br
.ti -1c
.RI "\fBreactionsMatrix\fP = 0"
.br
.ti -1c
.RI "while \fBcontinua\fP \fBrValues\fP = \fBfscanf\fP(\fBfid\fP,'%d',7)"
.br
.ti -1c
.RI "\fBstop\fP = \fBisempty\fP(\fBrValues\fP)"
.br
.ti -1c
.RI "dividing into condensations 
.br
\fBand\fP \fBcleavages\fP \fBcondensations\fP = 0"
.br
.ti -1c
.RI "\fBcleavages\fP = 0"
.br
.ti -1c
.RI "\fBcleavagesMatrix\fP = 0"
.br
.ti -1c
.RI "\fBcondensationsMatrix\fP = 0"
.br
.ti -1c
.RI "for \fBi\fP"
.br
.ti -1c
.RI "creating \fBcatalysis\fP matrix \fBcFiles\fP = dir('\fBcatalysis\fP*')"
.br
.ti -1c
.RI "\fBcatalysisFile\fP = \fBcFiles\fP(length(\fBcFiles\fP))\&.\fBname\fP"
.br
.ti -1c
.RI "\fBcatalysisMatrix\fP = 0"
.br
.ti -1c
.RI "while \fBcontinua\fP \fBcValues\fP = \fBfscanf\fP(\fBfid\fP,'%\fBf\fP',7)"
.br
.ti -1c
.RI "\fBbreak\fP"
.br
.ti -1c
.RI "identifying outliers \fBreactionsCounters\fP = \fBreactionsMatrix\fP(:,6)"
.br
.ti -1c
.RI "\fBoutRows\fP = 0"
.br
.ti -1c
.RI "\fBoutliersMatrix\fP = 0"
.br
.ti -1c
.RI "\fBif\fP \fBpossible\fP"
.br
.ti -1c
.RI "identifying killers \fBkillRows\fP = 0"
.br
.ti -1c
.RI "\fBkillersMatrix\fP = 0"
.br
.ti -1c
.RI "\fBcheck2\fP = ismember(\fBoutliersMatrix\fP(\fBi\fP,4),\fBblocked\fP)"
.br
.ti -1c
.RI "\fBcheck3\fP = ismember(\fBoutliersMatrix\fP(\fBi\fP,5),\fBblocked\fP)"
.br
.ti -1c
.RI "\fBkillerCatalysts\fP = 0"
.br
.ti -1c
.RI "\fBKCRows\fP = 0"
.br
.ti -1c
.RI "for \fBj\fP"
.br
.ti -1c
.RI "\fBKSMatrix\fP = 0"
.br
.ti -1c
.RI "\fBcheck4\fP = xor(\fBcheck2\fP,\fBcheck3\fP)"
.br
.ti -1c
.RI "\fBcheck6\fP = ismember(\fBKSMatrix\fP(\fBi\fP,5),\fBcleavagesMatrix\fP(:,3))"
.br
.ti -1c
.RI "\fBcheck7\fP = ismember(\fBKSMatrix\fP(\fBi\fP,5),\fBcatalysisMatrix\fP(:,2))"
.br
.ti -1c
.RI "\fBif\fP \fBcheck5\fP"
.br
.ti -1c
.RI "\fBcheckKSM\fP = \fBisempty\fP(\fBKSMatrix\fP)"
.br
.ti -1c
.RI "\fBKSCatalysts\fP = 0"
.br
.ti -1c
.RI "\fBKSCRows\fP = 0"
.br
.ti -1c
.RI "\fBend\fP identifying spammers \fBSpamRows\fP = 0"
.br
.ti -1c
.RI "\fBSpammersMatrix\fP = 0"
.br
.ti -1c
.RI "\fBend\fP \fBcheckSM\fP = \fBisempty\fP(\fBSpammersMatrix\fP)"
.br
.ti -1c
.RI "\fBspammersCatalysts\fP = 0"
.br
.ti -1c
.RI "\fBSCRows\fP = 0"
.br
.ti -1c
.RI "\fBcheckKM\fP = \fBisempty\fP(\fBkillersMatrix\fP)"
.br
.ti -1c
.RI "\fBelse\fP [\fBr\fP \fBc\fP] = \fBsize\fP(\fBkillersMatrix\fP)"
.br
.ti -1c
.RI "clear \fBr\fP"
.br
.ti -1c
.RI "clear \fBc\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBend\fP catalysisMatrix (\fBcontinua\fP, 1:4)"

.SS "cd (param\&.tmpPath)"

.SS "cd ('0_statistics')"

.SS "cd ('\&.\&./')"

.SS "\fBend\fP cd (\fBcurrentDir\fP)"

.SS "cleavagesMatrix (\fBcleavages\fP, 1:6)"

.SS "condensationsMatrix (\fBcondensations\fP, 1:6)"

.SS "disp ('|-----------------------------------------|')"

.SS "disp ('|-Killer \fBand\fP Spammer \fBanalysis\fP is started|')"

.SS "disp (strcat('|-Folder: ', \fBsimDirs\fP(\fBx\fP)\&.\fBname\fP,'/res\&.\&.\&.'))"

.SS "fclose (\fBfid\fP)"

.SS "fprintf (\fBfid\fP, 'NET%d\\n\\n', \fBx\fP)"

.SS "fprintf (\fBfid\fP, 'KILLERS\\n\\n')"

.SS "\fBend\fP fprintf (\fBfid\fP, '\\n\\n')"

.SS "fprintf (\fBfid\fP, 'Catalysts\\n\\n')"

.SS "fprintf (\fBfid\fP, '%d\\t', \fBkillerCatalysts\fP(\fBi\fP, 2))"

.SS "fprintf (\fBfid\fP, '%d\\n\\n', \fBkillerCatalysts\fP(\fBi\fP, 3))"

.SS "\fBend\fP fprintf (\fBfid\fP, 'KILLERS-SPAMMERS\\n\\n')"

.SS "fprintf (\fBfid\fP, '%d\\t', \fBKSCatalysts\fP(\fBKSCRows\fP, 2))"

.SS "fprintf (\fBfid\fP, '%d\\n\\n', \fBKSCatalysts\fP(\fBKSCRows\fP, 3))"

.SS "\fBend\fP fprintf (\fBfid\fP, 'SPAMMERS\\n\\n')"

.SS "fprintf (\fBfid\fP, '%d\\t', \fBspammerCatalysts\fP(\fBSCRows\fP, 2))"

.SS "fprintf (\fBfid\fP, '%d\\n\\n', \fBspammerCatalysts\fP(\fBSCRows\fP, 3))"

.SS "if ((\fBoutliersMatrix\fP(\fBi\fP, 2)==1)&&(\fBcheck2\fP==1 &&\fBcheck3\fP==1))"

.SS "if ((\fBoutliersMatrix\fP(\fBi\fP, 2)==1)&&(\fBcheck2\fP==0 &&\fBcheck3\fP==0))"

.SS "killerCatalysts (\fBKCRows\fP, 1)"

.SS "killerCatalysts (\fBKCRows\fP, 2)"

.SS "killerCatalysts (\fBKCRows\fP, 3)"

.SS "killersMatrix (\fBkillRows\fP, 1:6)"

.SS "\fBfunction\fP KillSpam (\fBparam\fP)"

.SS "KSCatalysts (\fBKSCRows\fP, 1)"

.SS "KSCatalysts (\fBKSCRows\fP, 2)"

.SS "KSCatalysts (\fBKSCRows\fP, 3)"

.SS "KSMatrix (\fBKSRows\fP, 1:6)"

.SS "KSMatrix (\fBi\fP, :)"

.SS "id KSRows ()\fC [virtual]\fP"

.SS "outliersMatrix (\fBoutRows\fP, 1:6)"

.SS "\fBif\fP outliersMatrix (\fBi\fP, 2)"

.SS "\fBbreak\fP \fBend\fP reactionsMatrix (\fBcontinua\fP, 1:6)"

.SS "spammerCatalysts (\fBKSCRows\fP, 1)"

.SS "spammerCatalysts (\fBKSCRows\fP, 2)"

.SS "spammerCatalysts (\fBKSCRows\fP, 3)"

.SS "SpammersMatrix (\fBSpamRows\fP, 1:6)"

.SS "\fBif\fP \fBSpamRows\fP SpammersMatrix (:, 7)"

.SS "SpammersMatrix (\fBi\fP, :)"

.SS "\fBelse\fP SpammersMatrix (\fBi\fP, 7)"

.SS "READ ALL THE DIRECTORY CONTAINING SIMULATIONS \fBif\fP ~isdir ('0_statistics')"

.SH "Variable Documentation"
.PP 
.SS "blocked = 0:\fBparam\&.lastSpecies\fP"

.PP
Definition at line 27 of file KillSpam\&.m\&.
.SS "break"

.PP
Definition at line 74 of file KillSpam\&.m\&.
.SS "clear c"

.PP
Definition at line 273 of file KillSpam\&.m\&.
.SS "catalysisFile = \fBcFiles\fP(length(\fBcFiles\fP))\&.\fBname\fP"

.PP
Definition at line 65 of file KillSpam\&.m\&.
.SS "catalysisMatrix = 0"

.PP
Definition at line 68 of file KillSpam\&.m\&.
.SS "creating \fBcatalysis\fP matrix cFiles = dir('\fBcatalysis\fP*')"

.PP
Definition at line 64 of file KillSpam\&.m\&.
.SS "check2 = ismember(\fBoutliersMatrix\fP(\fBi\fP,4),\fBblocked\fP)"

.PP
Definition at line 106 of file KillSpam\&.m\&.
.SS "check3 = ismember(\fBoutliersMatrix\fP(\fBi\fP,5),\fBblocked\fP)"

.PP
Definition at line 107 of file KillSpam\&.m\&.
.SS "check4 = xor(\fBcheck2\fP,\fBcheck3\fP)"

.PP
Definition at line 139 of file KillSpam\&.m\&.
.SS "\fBif\fP check5"
\fBInitial value:\fP
.PP
.nf
== 1 || check6 == 1 || check7 == 1
                    KSRows = KSRows-1
.fi
.PP
Definition at line 152 of file KillSpam\&.m\&.
.SS "check6 = ismember(\fBKSMatrix\fP(\fBi\fP,5),\fBcleavagesMatrix\fP(:,3))"

.PP
Definition at line 150 of file KillSpam\&.m\&.
.SS "check7 = ismember(\fBKSMatrix\fP(\fBi\fP,5),\fBcatalysisMatrix\fP(:,2))"

.PP
Definition at line 151 of file KillSpam\&.m\&.
.SS "\fBif\fP checkKM = \fBisempty\fP(\fBkillersMatrix\fP)"

.PP
Definition at line 259 of file KillSpam\&.m\&.
.SS "\fBif\fP checkKSM = \fBisempty\fP(\fBKSMatrix\fP)"

.PP
Definition at line 168 of file KillSpam\&.m\&.
.SS "\fBif\fP checkSM = \fBisempty\fP(\fBSpammersMatrix\fP)"

.PP
Definition at line 234 of file KillSpam\&.m\&.
.SS "cleavages = 0"

.PP
Definition at line 48 of file KillSpam\&.m\&.
.SS "cleavagesMatrix = 0"

.PP
Definition at line 50 of file KillSpam\&.m\&.
.SS "\fBelse\fP condensations = 0"

.PP
Definition at line 47 of file KillSpam\&.m\&.
.SS "condensationsMatrix = 0"

.PP
Definition at line 51 of file KillSpam\&.m\&.
.SS "continua = 1"

.PP
Definition at line 32 of file KillSpam\&.m\&.
.SS "while \fBcontinua\fP cValues = \fBfscanf\fP(\fBfid\fP,'%\fBf\fP',7)"

.PP
Definition at line 70 of file KillSpam\&.m\&.
.SS "else[\fBr\fP \fBc\fP] = \fBsize\fP(\fBkillersMatrix\fP)"

.PP
Definition at line 263 of file KillSpam\&.m\&.
.SS "fid = fopen('ALL_results_TS1\&.txt','w')"

.PP
Definition at line 20 of file KillSpam\&.m\&.
.SS "\fBend\fP clear i"
\fBInitial value:\fP
.PP
.nf
= 1:rrm
        if reactionsMatrix(i,2) == 1
            cleavages = cleavages+1
.fi
.PP
Definition at line 52 of file KillSpam\&.m\&.
.SS "clear j"
\fBInitial value:\fP
.PP
.nf
= 1:rcm
                if killerReaction == catalysisMatrix(j,3) && catalysisMatrix(j,4) > 0
                    KCRows = KCRows+1
.fi
.PP
Definition at line 120 of file KillSpam\&.m\&.
.SS "KCRows = 0"

.PP
Definition at line 117 of file KillSpam\&.m\&.
.SS "killerCatalysts = 0"

.PP
Definition at line 116 of file KillSpam\&.m\&.
.SS "killersMatrix = 0"

.PP
Definition at line 103 of file KillSpam\&.m\&.
.SS "\fBif\fP killRows = 0"

.PP
Definition at line 102 of file KillSpam\&.m\&.
.SS "KSCatalysts = 0"

.PP
Definition at line 171 of file KillSpam\&.m\&.
.SS "KSCRows = 0"

.PP
Definition at line 172 of file KillSpam\&.m\&.
.SS "KSMatrix = 0"

.PP
Definition at line 135 of file KillSpam\&.m\&.
.SS "outliersMatrix = 0"

.PP
Definition at line 91 of file KillSpam\&.m\&.
.SS "outRows = 0"

.PP
Definition at line 90 of file KillSpam\&.m\&.
.SS "\fBif\fP possible"
\fBInitial value:\fP
.PP
.nf
== 1
            outRows = outRows+1
.fi
.PP
Definition at line 94 of file KillSpam\&.m\&.
.SS "clear r"

.PP
Definition at line 272 of file KillSpam\&.m\&.
.SS "identifying outliers reactionsCounters = \fBreactionsMatrix\fP(:,6)"

.PP
Definition at line 83 of file KillSpam\&.m\&.
.SS "reactionsFile = \fBrFiles\fP(length(\fBrFiles\fP)-1)\&.\fBname\fP"

.PP
Definition at line 30 of file KillSpam\&.m\&.
.SS "reactionsMatrix = 0"

.PP
Definition at line 33 of file KillSpam\&.m\&.
.SS "creating \fBreactions\fP matrix rFiles = dir('\fBreactions\fP*')"

.PP
Definition at line 29 of file KillSpam\&.m\&.
.SS "while \fBcontinua\fP rValues = \fBfscanf\fP(\fBfid\fP,'%d',7)"

.PP
Definition at line 35 of file KillSpam\&.m\&.
.SS "SCRows = 0"

.PP
Definition at line 238 of file KillSpam\&.m\&.
.SS "simDirs = dir(\fBtmpFolder\fP)"

.PP
Definition at line 17 of file KillSpam\&.m\&.
.SS "spammersCatalysts = 0"

.PP
Definition at line 237 of file KillSpam\&.m\&.
.SS "SpammersMatrix = 0"

.PP
Definition at line 190 of file KillSpam\&.m\&.
.SS "\fBend\fP identifying spammers SpamRows = 0"

.PP
Definition at line 189 of file KillSpam\&.m\&.
.SS "\fBif\fP stop = \fBisempty\fP(\fBrValues\fP)"

.PP
Definition at line 36 of file KillSpam\&.m\&.
.SS "\fBend\fP tmpFolder = strcat('*',\fBparam\&.simFolder\fP,'*')"

.PP
Definition at line 16 of file KillSpam\&.m\&.
.SS "for x"
\fBInitial value:\fP
.PP
.nf
= 1:length(simDirs)
    cd(strcat(simDirs(x)\&.name,'/res'))
.fi
.PP
Definition at line 24 of file KillSpam\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
