.TH "/Users/alessandrofilisetti/Dropbox/ACS_SVN/carness/carness_simulator/_matlabinitializator/lancia_acs.m" 3 "Wed Apr 3 2013" "Version 3.2 (20130403.51)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Dropbox/ACS_SVN/carness/carness_simulator/_matlabinitializator/lancia_acs.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKeq\fP (\fBk\fP, \fBj\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "lancia_acs m clear all close 
.br
all parametri \fBkdiss\fP = 0"
.br
.ti -1c
.RI "\fBkcomplex\fP = 1e6"
.br
.ti -1c
.RI "\fBkcond\fP = 6e8"
.br
.ti -1c
.RI "\fBk_complex\fP = 1e-4"
.br
.ti -1c
.RI "\fBAB\fP = 0"
.br
.ti -1c
.RI "\fBC\fP = 2e-7"
.br
.ti -1c
.RI "\fBCA\fP = 0"
.br
.ti -1c
.RI "\fBk\fP = 0"
.br
.ti -1c
.RI "for \fBA\fP"
.br
.ti -1c
.RI "for \fBB\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Keq (\fBk\fP, \fBj\fP)"

.SH "Variable Documentation"
.PP 
.SS "for A"
\fBInitial value:\fP
.PP
.nf
= 10e-7:10e-7:10e-6
    
    k=k+1
    j=0
.fi
.PP
Definition at line 17 of file lancia_acs\&.m\&.
.SS "AB = 0"

.PP
Definition at line 12 of file lancia_acs\&.m\&.
.SS "for B"
\fBInitial value:\fP
.PP
.nf
= 10e-7:10e-7:10e-6
        
        j=j+1
        
        
        [t y] = ACS_reverse_reaction_con_input(A,B,AB,C,CA,kdiss,kcomplex,kcond,k_complex)
.fi
.PP
Definition at line 21 of file lancia_acs\&.m\&.
.SS "C = 2e-7"

.PP
Definition at line 13 of file lancia_acs\&.m\&.
.SS "CA = 0"

.PP
Definition at line 14 of file lancia_acs\&.m\&.
.SS "k = 0"

.PP
Definition at line 16 of file lancia_acs\&.m\&.
.SS "k_complex = 1e-4"

.PP
Definition at line 10 of file lancia_acs\&.m\&.
.SS "kcomplex = 1e6"

.PP
Definition at line 8 of file lancia_acs\&.m\&.
.SS "kcond = 6e8"

.PP
Definition at line 9 of file lancia_acs\&.m\&.
.SS "lancia_acs m clear all close all parametri kdiss = 0"

.PP
Definition at line 7 of file lancia_acs\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
