.TH "lib.IO.readfiles" 3 "Tue Dec 10 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.IO.readfiles \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBreadConfFile\fP"
.br
.ti -1c
.RI "def \fBreadInitConfFile\fP"
.br
.ti -1c
.RI "def \fBreadBufferedID\fP"
.br
.ti -1c
.RI "def \fBreadCSTRflux\fP"
.br
.ti -1c
.RI "def \fBloadAllData\fP"
.br
.ti -1c
.RI "def \fBzeroBeforeStrNum\fP"
.br
.ti -1c
.RI "def \fBsplitRctParsLine\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lib\&.IO\&.readfiles\&.loadAllData (tmpPath, tmpFname)"

.PP
Definition at line 120 of file readfiles\&.py\&.
.SS "def lib\&.IO\&.readfiles\&.readBufferedID (tmpPath)"

.PP
Definition at line 89 of file readfiles\&.py\&.
.SS "def lib\&.IO\&.readfiles\&.readConfFile (tmpPath)"

.PP
Definition at line 14 of file readfiles\&.py\&.
.SS "def lib\&.IO\&.readfiles\&.readCSTRflux (tmpPath)"

.PP
Definition at line 105 of file readfiles\&.py\&.
.SS "def lib\&.IO\&.readfiles\&.readInitConfFile (tmpPath)"

.PP
Definition at line 52 of file readfiles\&.py\&.
.SS "def lib\&.IO\&.readfiles\&.splitRctParsLine (tmpLine)"

.PP
Definition at line 135 of file readfiles\&.py\&.
.SS "def lib\&.IO\&.readfiles\&.zeroBeforeStrNum (tmpl, tmpL)"

.PP
Definition at line 127 of file readfiles\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
