.TH "lib.IO.writefiles" 3 "Tue Dec 10 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.IO.writefiles \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwrite_init_raf_list\fP"
.br
.ti -1c
.RI "def \fBwrite_init_raf_all\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lib\&.IO\&.writefiles\&.write_init_raf_all (fid, rafinfo, folder, rcts, cats)"

.PP
Definition at line 23 of file writefiles\&.py\&.
.SS "def lib\&.IO\&.writefiles\&.write_init_raf_list (fid, rafinfo, folder)"

.PP
Definition at line 14 of file writefiles\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
