.TH "lib.graph.raf" 3 "Thu Dec 12 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.graph.raf \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgenerateClosure\fP"
.br
.ti -1c
.RI "def \fBRAcondition\fP"
.br
.ti -1c
.RI "def \fBFcondition\fP"
.br
.ti -1c
.RI "def \fBfindCatforRAF\fP"
.br
.ti -1c
.RI "def \fBrafsearch\fP"
.br
.ti -1c
.RI "def \fBrafComputation\fP"
.br
.ti -1c
.RI "def \fBrafDynamicComputation\fP"
.br
.ti -1c
.RI "def \fBfindRAFrcts\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lib\&.graph\&.raf\&.Fcondition (tmpCL, tmpRA, rcts, debug = \fCFalse\fP)"

.PP
Definition at line 60 of file raf\&.py\&.
.SS "def lib\&.graph\&.raf\&.findCatforRAF (tmpCat, tmpRAF, tmpClosure, debug = \fCFalse\fP)"

.PP
Definition at line 82 of file raf\&.py\&.
.SS "def lib\&.graph\&.raf\&.findRAFrcts (RAF, rcts, actrcts)"

.PP
Definition at line 160 of file raf\&.py\&.
.SS "def lib\&.graph\&.raf\&.generateClosure (tmpF, rcts, debug = \fCFalse\fP)"

.PP
Definition at line 20 of file raf\&.py\&.
.SS "def lib\&.graph\&.raf\&.RAcondition (tmpCL, rcts, cats, debug = \fCFalse\fP)"

.PP
Definition at line 46 of file raf\&.py\&.
.SS "def lib\&.graph\&.raf\&.rafComputation (fid_initRafRes, fid_initRafResALL, fid_initRafResLIST, tmpDir, rctProb, avgCon, rcts, cats, foodList, maxDim, debug = \fCFalse\fP)"

.PP
Definition at line 134 of file raf\&.py\&.
.SS "def lib\&.graph\&.raf\&.rafDynamicComputation (fid_dynRafRes, tmpTime, rcts, cats, foodList, growth = \fCFalse\fP, rctsALL = \fCNone\fP, catsALL = \fCNone\fP, completeRCTS = \fCNone\fP, debug = \fCFalse\fP)"

.PP
Definition at line 144 of file raf\&.py\&.
.SS "def lib\&.graph\&.raf\&.rafsearch (rcts, cats, closure, debug = \fCFalse\fP)"

.PP
Definition at line 91 of file raf\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
