.TH "/Users/alessandrofilisetti/Documents/GIT/carness/main.cpp" 3 "Sat Oct 26 2013" "Version 4.8 (20131026.60)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'acs_headers\&.h'\fP
.br
\fC#include 'environment\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsaveToFile\fP (string tmpSavingPath, \fBenvironment\fP *tmpEnvironment, \fBacs_int\fP tmpGen, \fBacs_int\fP tmpSim, \fBacs_int\fP tmpStep)"
.br
.ti -1c
.RI "void \fBsaveTimesToFile\fP (string tmpSavingPath, \fBenvironment\fP *tmpEnvironment, \fBacs_int\fP tmpGen, \fBacs_int\fP tmpSim, \fBacs_int\fP tmpStep)"
.br
.ti -1c
.RI "void \fBsaveInitialConditionsToFile\fP (string tmpSavingPath, \fBenvironment\fP *tmpEnvironment, \fBacs_int\fP tmpGen, \fBacs_int\fP tmpSim, \fBacs_int\fP tmpStep)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"
double random number generator 
.PP
Definition at line 353 of file main\&.cpp\&.
.SS "void saveInitialConditionsToFile (stringtmpSavingPath, \fBenvironment\fP *tmpEnvironment, \fBacs_int\fPtmpGen, \fBacs_int\fPtmpSim, \fBacs_int\fPtmpStep)"
Save to file all the INITIAL structures 
.PP
\fBVersion:\fP
.RS 4
2\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpSavingPath Saving files path 
.br
\fIenvironment\fP *tmpEnvironment environment instance reference 
.br
\fItmpSim\fP Current simulation 
.br
\fIacs_int\fP Current step 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 661 of file main\&.cpp\&.
.SS "void saveTimesToFile (stringtmpSavingPath, \fBenvironment\fP *tmpEnvironment, \fBacs_int\fPtmpGen, \fBacs_int\fPtmpSim, \fBacs_int\fPtmpStep)"
Save TIMES to file 
.PP
\fBVersion:\fP
.RS 4
2\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpSavingPath Saving files path 
.br
\fIenvironment\fP *tmpEnvironment environment instance reference 
.br
\fItmpSim\fP Current simulation 
.br
\fIacs_int\fP Current step 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/03 
.RE
.PP

.PP
Definition at line 645 of file main\&.cpp\&.
.SS "void saveToFile (stringtmpSavingPath, \fBenvironment\fP *tmpEnvironment, \fBacs_int\fPtmpGen, \fBacs_int\fPtmpSim, \fBacs_int\fPtmpStep)"
Save to file structures at step tmpStep 
.PP
\fBVersion:\fP
.RS 4
2\&.0 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP tmpSavingPath Saving files path 
.br
\fIenvironment\fP *tmpEnvironment environment instance reference 
.br
\fItmpSim\fP Current simulation 
.br
\fIacs_int\fP Current step 
.RE
.PP
\fBDate:\fP
.RS 4
2013/07/13 
.RE
.PP

.PP
Definition at line 625 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
