.TH "MTRand_open" 3 "Wed Apr 3 2013" "Version 3.2 (20130403.51)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MTRand_open \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtrand\&.h>\fP
.PP
Inherits \fBMTRand_int32\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMTRand_open\fP ()"
.br
.ti -1c
.RI "\fBMTRand_open\fP (unsigned long \fBseed\fP)"
.br
.ti -1c
.RI "\fBMTRand_open\fP (const unsigned long *\fBseed\fP, int \fBsize\fP)"
.br
.ti -1c
.RI "\fB~MTRand_open\fP ()"
.br
.ti -1c
.RI "double \fBoperator()\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 125 of file mtrand\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MTRand_open::MTRand_open ()\fC [inline]\fP"

.PP
Definition at line 127 of file mtrand\&.h\&.
.SS "MTRand_open::MTRand_open (unsigned longseed)\fC [inline]\fP"

.PP
Definition at line 128 of file mtrand\&.h\&.
.SS "MTRand_open::MTRand_open (const unsigned long *seed, intsize)\fC [inline]\fP"

.PP
Definition at line 129 of file mtrand\&.h\&.
.SS "MTRand_open::~MTRand_open ()\fC [inline]\fP"

.PP
Definition at line 130 of file mtrand\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double MTRand_open::operator() ()\fC [inline]\fP"

.PP
Definition at line 131 of file mtrand\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
