.TH "MTRand_closed" 3 "Sat Oct 26 2013" "Version 4.8 (20131026.60)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MTRand_closed \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtrand\&.h>\fP
.PP
Inherits \fBMTRand_int32\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMTRand_closed\fP ()"
.br
.ti -1c
.RI "\fBMTRand_closed\fP (unsigned long \fBseed\fP)"
.br
.ti -1c
.RI "\fBMTRand_closed\fP (const unsigned long *\fBseed\fP, int \fBsize\fP)"
.br
.ti -1c
.RI "\fB~MTRand_closed\fP ()"
.br
.ti -1c
.RI "double \fBoperator()\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 111 of file mtrand\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MTRand_closed::MTRand_closed ()\fC [inline]\fP"

.PP
Definition at line 113 of file mtrand\&.h\&.
.SS "MTRand_closed::MTRand_closed (unsigned longseed)\fC [inline]\fP"

.PP
Definition at line 114 of file mtrand\&.h\&.
.SS "MTRand_closed::MTRand_closed (const unsigned long *seed, intsize)\fC [inline]\fP"

.PP
Definition at line 115 of file mtrand\&.h\&.
.SS "MTRand_closed::~MTRand_closed ()\fC [inline]\fP"

.PP
Definition at line 116 of file mtrand\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double MTRand_closed::operator() ()\fC [inline]\fP"

.PP
Definition at line 117 of file mtrand\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
