.TH "page_init_str" 3 "Tue Dec 10 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page_init_str \- Initial Data Structures 
In order to proceed with the simulation the system needs from \fB4\fP to \fB6 (open system and energy on)\fP initial data structures files (an example for each file is located into the source code folder): 
.PP
.nf
 - \c acsm2s.conf (described in the \ref parameters section)
 - \c _acsspecies.csv - This file contains all the initial <b>species</b> with their proprieties
 - \c _acsreactions.csv - This file contains all the initial <b>reactions</b> with their proprieties
 - \c _acscatalysis.csv - This file contains all the <b>correspondances between species and reactions</b> with their proprieties

.fi
.PP
.PP
and, if the system is open 
.PP
.nf
 - \c _acsinflux.csv - This file contains all the species belonging to the incoming flux

.fi
.PP
.PP
and\&. if the system is energy based 
.PP
.nf
          - \c _acsnrgbooleanfunctions.csv - This file contains all the possible boolean functions associated with the reactions

.fi
.PP
.PP

.br
 
.SH "_acsspecies\&.csv"
.PP
Columns description (each field is delimited using '\\t'): Identificator(ID)SequenceConcentrationDiffusion enhancementPrecipitation flagComplex Dissociation Kinetic ConstantComplex Binding Point Already evaluated flagSpecies AgeNumber of rebornsCatalyst IDComplex IDPhosphorilation Kinetic constantCharged Molecules ConcentrationConcentration locked  
.IP "\(bu" 2
\fIID\fP: Species Index
.IP "\(bu" 2
\fISequence\fP: Species sequence
.IP "\(bu" 2
\fIConcentration\fP: Total concentration of the species
.IP "\(bu" 2
\fIDiffusion enhancement\fP: Diffusion enhancement
.IP "\(bu" 2
\fIPrecipitation flag\fP: If 0 species is precipited and each new molecules of this species will be precipited
.IP "\(bu" 2
\fIDissociation Kinetic Constant\fP: Complex dissociation kinetic constant
.IP "\(bu" 2
\fIBinding point\fP: If the species is a complex this field indicates the division point between catalyst and substrate
.IP "\(bu" 2
\fIEvaluated\fP: If 1 the species is not virtual and all the reactions it catalyzes are created, if 0 the species is only potentially created
.IP "\(bu" 2
\fISpecies Age\fP: Age (in seconds) of the species since its last cretion, each time that a species amount pass from 0 to > 1 the counter is resetted
.IP "\(bu" 2
\fINumber of reborns\fP: Number of times that a species amount pass from 0 to > 0
.IP "\(bu" 2
\fICatalyst ID\fP: If the species is a complex (e\&.g\&. catalyst C forming a complex C\&.A with the substrate A) this is the CATALYST ID
.IP "\(bu" 2
\fISubstrate ID\fP: If the species is a complex (e\&.g\&. catalyst C forming a complex C\&.A with the substrate A) this is the SUBSTATE ID
.IP "\(bu" 2
\fIPhosphorilation Kinetic constant\fP: NOT USED NOW!!!
.IP "\(bu" 2
\fICharged Molecules Concentration\fP: Concentration of the charged molecules belonging to the species\&.
.IP "\(bu" 2
\fIConcentration locked\fP: 0 -> Concentration of the species changes according to the reactions affecting it, 1 -> The concentration of the species is locked (permeable species, the concentration of the species is assumed to be constant within the cell and in the environment) 
.br
 
.PP
.SH "_acsreactions\&.csv"
.PP
Columns description (each field is delimited using '\\t'): IdentificatorReaction typeSpecies 1Species 2Species 3 Reaction counterEnergy typek spont  
.IP "\(bu" 2
\fIIdentificator\fP: Reaction ID
.IP "\(bu" 2
\fIReaction type\fP: 0 Condensation, 1 Cleavage
.IP "\(bu" 2
\fISpecies 1\fP: Product ID if reaction type = 1, Substrate ID reaction type = 0
.IP "\(bu" 2
\fISpecies 2\fP: Product ID if reaction type = 0, Substrate ID reaction type = 1
.IP "\(bu" 2
\fISpecies 3\fP: Product ID if reaction type = 0, Substrate ID reaction type = 1
.IP "\(bu" 2
\fIReaction counter\fP: Reaction occurrance counter
.IP "\(bu" 2
\fIEnergy Type\fP: The reaction energetic configuration, 1 for endoergonic 0 for esoergonic
.IP "\(bu" 2
\fISpontaneous Constant\fP: Spontaneous reaction constant 
.br
 
.PP
.SH "_acscatalysis\&.csv"
.PP
Columns description (each field is delimited using '\\t'): IdentificatorCatalyst IDReaction IDCatalysis counterK condensationK cleavageK Complex AssociationComplex creation substrate target  
.IP "\(bu" 2
\fIIdentificator\fP: Catalysis ID
.IP "\(bu" 2
\fICatalyst ID\fP: species (as catalyst) ID
.IP "\(bu" 2
\fIReaction ID\fP: Reaction ID
.IP "\(bu" 2
\fICatalysis counter\fP: Catalysis counter
.IP "\(bu" 2
\fIK final step end condensation kinetic constant\fP: Final step end condensation kinetic constant
.IP "\(bu" 2
\fIK Cleavage\fP: Cleavage Kinetic constant
.IP "\(bu" 2
\fIK complex association\fP: Complex association kinetic constant
.IP "\(bu" 2
\fIComplex creation substrate target\fP: Which substrate will be involved in complex creation, 1 or 2 
.br
 
.PP
.SH "_acsinflux\&.csv"
.PP
Columns description (each field is delimited using '\\t'): IdentificatorProbabilitity  
.IP "\(bu" 2
\fIIdentificator\fP: Species ID
.IP "\(bu" 2
\fIProbabilitity\fP: Probability to be selected when a species has to be inserted into the system 
.br
 
.PP
.SH "_acsnrgbooleanfunctions\&.csv"
.PP
Columns description (each field is delimited using '\\t'): Energetic Boolean Function (decimal form)Probabilitity  
.IP "\(bu" 2
\fIEnergetic Boolean Function (decimal form)\fP: Energetic Boolean Function decimal form, e\&.g\&. 1001011010100 = 4820
.IP "\(bu" 2
\fIProbabilitity\fP: Probability to be selected when a new reaction has to be created 
.PP

