.TH "page_gillespie" 3 "Sat Oct 26 2013" "Version 4.8 (20131026.60)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page_gillespie \- Gillespie Class 
The Gillespie class contains the information concerning the Gillespie algorithm propensity with other useful information\&. In particular it has 4 properties, namely mol_I, mol_II, mol_III, mol_IV containing the species ID's related to different species type according to the different admitted reactions\&. In the following a table summarizing the different meanings for the different reactions is reported\&. Reaction TypeReaction Type CodeMOL 1MOL 2MOL 3MOL 4  Complex Formation2CatalystFirst SubstrateCatalysis IDSecond Substrate  Final Condensation0CatalystSubstrateProductComplex  Cleavage1SubstrateProduct 1Product 2Catalyst  Spontaneous Cleavage11SubstrateProduct 1Product 2//  Spontaneous Condensation10ProductSubstrate 1Substrate 2//  
