.TH "pageoutcomes" 3 "Tue Dec 10 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pageoutcomes \- Outcomes 
During the simulation \fB8\fP different files concerning species, reactions and catalysis tables, times, reactions parameters, living species, living species amounts and concentration are produced\&. In the following you find a brief description of all files and some indications about the different time storage\&. 
.SH "Species"
.PP
Every environment::timeStructuresSavingInterval seconds species structures will be saved in files called species_<generationNumber>_<simulationNumber>_<reactionNumber>\&.csv (e\&.g\&. \fBspecies_1_06_0016933\&.csv\fP means species structure, generation number 1, simulation number 6, reaction number 16933)\&.
.br
Columns description (each field is delimited using '\\t') is the same described above, section \fB_acsspecies\&.csv\fP \&.
.SH "Reactions"
.PP
Every environment::timeStructuresSavingInterval seconds reactions structures will be saved in files called reactions_<generationNumber>_<simulationNumber>_<reactionNumber>\&.csv (e\&.g\&. \fBreactions_1_06_0016933\&.csv\fP means reactions structure, generation number 1, simulation number 6, reaction number 16933)\&. 
.br
Columns description (each field is delimited using '\\t') is the same described above, section \fB_acsreactions\&.csv\fP \&.
.SH "Catalysis"
.PP
Every environment::timeStructuresSavingInterval seconds catalysis structures will be saved in files called catalysis_<generationNumber>_<simulationNumber>_<reactionNumber>\&.csv (e\&.g\&. \fBcatalysis_1_06_0016933\&.csv\fP means catalysis structure, generation number 1, simulation number 6, reaction number 16933)\&. 
.br
Columns description (each field is delimited using '\\t')is the same described above, section \fB_acscatalysis\&.csv\fP :
.SH "Times"
.PP
Every simulation generates a times file called times_<generationNumber>_<simulationNumber>\&.csv (e\&.g\&. \fBtimes_1_03\&.csv\fP means times file, generation 1, simulation 3) containing values concerning \fBeach events\fP occurred during the simulation\&. This file is \fBcreated at the beginning of the simulation\fP and it is \fBupdated after each event\fP, hence this file will contain a number of rows equal to the number of reaction (of any type) occurred during the simulation\&. 
.br
Columns description (each field is delimited using '\\t'): Identificator (reaction)Reaction TimeGillespie ID selectedReaction TypeNumber of possible reactionsComputational Time (sec) Number of SpeciesNumber of MoleculesNumber of complex speciesNumber of complexes Number of bricksGillespie Computational TimeReaction Process Computational TimeVarious Processes Computational TimeNew species creation probability  
.IP "\(bu" 2
\fIIdentificator (reaction)\fP: Number of the reaction (STEP)
.IP "\(bu" 2
\fIReaction Time\fP: Time of the reaction
.IP "\(bu" 2
\fIGillespie ID selected\fP: Gillespie structure reaction ID
.IP "\(bu" 2
\fIReaction Type\fP: 0 condensation, 1 cleavage, 2 complex formation, 3 complex degradation, 4 species efflux, 6 endergonic cleavage, 7 endoergonic condensation, 8 endoergonic complex creation
.IP "\(bu" 2
\fINumber of possible reactions\fP: Total number of possible reactions according to the Gillespie algorithm computation
.IP "\(bu" 2
\fIComputational Time (ms)\fP: Computational time between two successive reactions
.IP "\(bu" 2
\fINumber of Species\fP: Number of species with at least one molecule
.IP "\(bu" 2
\fINumber of Molecules\fP: Number of molecules
.IP "\(bu" 2
\fINumber of complex species\fP: Number of complex species with at least one molecule
.IP "\(bu" 2
\fINumber of complexes\fP: Number of complex molecules
.IP "\(bu" 2
\fINumber of bricks\fP: Number of single bricks (monomers) present in the system
.IP "\(bu" 2
\fIGillespie Computational Time\fP: Number of milliseconds necessary to complete the Gillespie task
.IP "\(bu" 2
\fIReaction Process Computational Time\fP: Number of milliseconds necessary to perform a reaction (and evaluate products) once that the Gillespie algorithm has selected the reaction
.IP "\(bu" 2
\fIVarious Processes Computational Time\fP: Number of milliseconds necessary to perform several tasks not correlated with the simulation of the phenomena
.IP "\(bu" 2
\fINew species creation probability\fP: Given the state of the system, probability to create a new species
.IP "\(bu" 2
\fIReverse Reaction Probability\fP: Given the state of the system, probability for a reverse reaction to occur
.PP
.SH "Reactions_parameters"
.PP
Every simulation generates a reactions parameters file called reactions_parameters_<generationNumber>_<simulationNumber>\&.csv (e\&.g\&. \fBreactions_parameters_1_07\&.csv\fP means reactions parameters file, generation 1 simulation number 7) containing informations on \fBcleavage and condensation\fP reactions\&. This file is \fBgenerated at the beginning of each simulation\fP and it is \fBupdated each time that a cleavage or a condensation occur\fP\&. 
.br
Columns description (each field is delimited using '\\t'): Reaction IDReaction TimeReaction TypeCatalyst IDSpecies 1 IDSpecies 2 IDSpecies 3 ID Charged MoleculesCharged ConcentrationGillespie Score AverageGillespie Score Standard DeviationEntropyNew species creation probability  
.IP "\(bu" 2
\fIReaction ID\fP: This ID referes to the reaction number (step)
.IP "\(bu" 2
\fIReaction Time\fP: Time of the reaction
.IP "\(bu" 2
\fIReaction Type ID\fP: 0 condensation, 1 cleavage, 6 endoergonic cleavage, 7 endoergonic condensation
.IP "\(bu" 2
\fICatalyst ID\fP: Catalyst ID into the species table
.IP "\(bu" 2
\fISpecies 1 ID\fP: product ID in case of condensation, substrate in case of cleavage
.IP "\(bu" 2
\fISpecies 2 ID\fP: substrate ID in case of condensation, product in case of cleavage
.IP "\(bu" 2
\fISpecies 3 ID\fP: substrate ID in case of condensation, product in case of cleavage
.IP "\(bu" 2
\fICharged Molecules\fP: Number of charged molecules
.IP "\(bu" 2
\fICharged Concentration\fP: Concentration of the charged molecules
.IP "\(bu" 2
\fIGillespie Score Average\fP: Average of the all gillespie algorithm scores
.IP "\(bu" 2
\fIGillespie Score Standard Deviation\fP: Standard Deviation of the all gillespie algorithm scores
.IP "\(bu" 2
\fIEntropy\fP: Entropy Misure (test) based on the probabilities that reactions occur
.IP "\(bu" 2
\fINew species creation probability\fP: Given the state of the system, probability to create a new species
.PP
.SH "Living_species"
.PP
Each simulation generates a living species file called livingSpecies_<generationNumber>_<simulationNumber>\&.csv (e\&.g\&. \fBlivingSpecies_1_07\&.csv\fP means living species file, generation 1 simulation number 7) containing all the living species IDs (living species are those species with concentration greater than 0) for each reaction in each raw\&. This file is \fBgenerated at the beginning of each simulation\fP and it is \fBupdated each time that a cleavage or a condensation occur\fP\&. This file has a variable number of columns equal to the number of living species plus 2 (Reaction ID and time of the reaction) 
.br
Columns description (each field is delimited using '\\t'): Reaction IDReaction Timeliving species IDs\&.\&.\&., one for column  
.IP "\(bu" 2
\fIReaction ID\fP: This ID referes to the reaction number (step)
.IP "\(bu" 2
\fIReaction Time\fP: Time of the reaction
.IP "\(bu" 2
\fILiving Species IDs\&.\&.\&., one for column\fP: Each column from the thirth to the last one contains living species ID
.PP
.SH "Living_species_amounts"
.PP
Each simulation generates a living species amount file called livingAmount_<generationNumber>_<simulationNumber>\&.csv (e\&.g\&. \fBlivingAmount_1_07\&.csv\fP means living species amount file, generation 1, simulation number 7) containing all the living species amount (living species are those species with concentration greater than 0) for each reaction in each raw\&. \fBThis file is tightly correlated with the \fILiving_species\fP file\fP\&. Each row contains the total amount of molecules belonging to the species indicated by its ID in the livingSpecies file\&. This file is \fBcreated at the beginning of each simulation\fP and it is \fBupdated each time that a cleavage or a condensation occur\fP\&. This file has a variable number of columns equals to the number of living species at time t 
.br
Columns description (each field is delimited using '\\t'): living species amounts\&.\&.\&., one for column  
.IP "\(bu" 2
\fILiving Species amounts\&.\&.\&., one for column\fP: Each values is related to the species indicated in the livingSpecies file\&. Reaction ID and time is that of the livingSpecies file
.PP
.SH "Living_species_concentration"
.PP
Each simulation generates a living species amount file called livingConcentration_<generationNumber>_<simulationNumber>\&.csv (e\&.g\&. \fBlivingConcentration_1_07\&.csv\fP means living species amount file, generation 1, simulation number 7) containing all the living species amount (living species are those species with concentration greater than 0) for each reaction in each raw\&. \fBThis file is tightly correlated with the \fILiving_species\fP file\fP\&. Each row contains the total amount of molecules belonging to the species indicated by its ID in the livingSpecies file\&. This file is \fBcreated at the beginning of each simulation\fP and it is \fBupdated each time that a cleavage or a condensation occur\fP\&. This file has a variable number of columns equals to the number of living species at time t 
.br
Columns description (each field is delimited using '\\t'): living species amounts\&.\&.\&., one for column  
.IP "\(bu" 2
\fILiving Species amounts\&.\&.\&., one for column\fP: Each values is related to the species indicated in the livingSpecies file\&. Reaction ID and time is that of the livingSpecies file 
.PP

