.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/underDevelopment/prepareNewSim.py" 3 "Thu Dec 12 2013" "Version 4.8 (20131210.63)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/underDevelopment/prepareNewSim.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBprepareNewSim\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBprepareNewSim\&.zeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBprepareNewSim\&.parser\fP"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.args\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.StrFrom\fP = os\&.path\&.abspath(args\&.StrFrom)"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.StrTo\fP = os\&.path\&.abspath(args\&.StrTo)"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.StrFileSpeciesToGetConc\fP = os\&.path\&.abspath(args\&.FileSpeciesToGetConc)"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.origin\fP = os\&.getcwd()"
.br
.ti -1c
.RI "int \fBprepareNewSim\&._LASTSPECIES_\fP = 29"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&._REVRCTS_\fP = int(args\&.revRct)"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&._RATIOREV_\fP = int(args\&.k_revRct)"
.br
.ti -1c
.RI "float \fBprepareNewSim\&._CLEAVAGE_\fP = 25\&.0"
.br
.ti -1c
.RI "float \fBprepareNewSim\&._CONDENSATION_\fP = 50\&.0"
.br
.ti -1c
.RI "float \fBprepareNewSim\&._COMPLEXFORM_\fP = 50\&.0"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&._COMPLEXDISS_\fP = float(args\&.kDiss)"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&._INITSPECIESCONC_\fP = float(args\&.singleInitConc)"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.fileDest\fP = os\&.path\&.join(StrTo,'_acsinflux\&.csv')"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.sourceResFolder\fP = os\&.path\&.join(StrFrom,'res')"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.lastSpeciesFile\fP = sorted(glob\&.glob('species_*'))"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.lastReactionsFile\fP = sorted(glob\&.glob('reactions_1*'))"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.lastCatalysisFile\fP = sorted(glob\&.glob('catalysis_*'))"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.mod\fP = open('acsm2s\&.conf')"
.br
.ti -1c
.RI "int \fBprepareNewSim\&.id\fP = 0"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.linesplitted\fP = \fBline\&.split\fP('=')"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.file\fP = open('acsm2s\&.conf', 'w')"
.br
.ti -1c
.RI "list \fBprepareNewSim\&.concs\fP = []"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.specFileLines\fP = open(StrFileSpeciesToGetConc)"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.mod_rct\fP = open('_acsreactions\&.csv')"
.br
.ti -1c
.RI "int \fBprepareNewSim\&.flag\fP = 0"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.catRct\fP = linecache\&.getline('_acsreactions\&.csv', int(linesplitted[2])+1)"
.br
.ti -1c
.RI "tuple \fBprepareNewSim\&.carRctSplit\fP = \fBcatRct\&.split\fP('\\t')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
