.TH "reactions" 3 "Thu Jul 4 2013" "Version 4.0 (20130705.52)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reactions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reactions\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreactions\fP (\fBacs_longInt\fP tmpID, \fBacs_int\fP tmpType, \fBacs_longInt\fP tmpM_I, \fBacs_longInt\fP tmpM_II, \fBacs_longInt\fP tmpM_III, \fBacs_int\fP tmpEvents, \fBacs_int\fP tmpEnergyType)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fB~reactions\fP ()"
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetID\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetType\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetSpecies_I\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetSpecies_II\fP () const "
.br
.ti -1c
.RI "\fBacs_longInt\fP \fBgetSpecies_III\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetEvents\fP () const "
.br
.ti -1c
.RI "\fBacs_int\fP \fBgetEnergyType\fP () const "
.br
.ti -1c
.RI "void \fBupdateTotEvents\fP ()"
.br
.ti -1c
.RI "void \fBresetEventsCounter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file reactions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "reactions::reactions (\fBacs_longInt\fPtmpID, \fBacs_int\fPtmpType, \fBacs_longInt\fPtmpM_I, \fBacs_longInt\fPtmpM_II, \fBacs_longInt\fPtmpM_III, \fBacs_int\fPtmpEvents, \fBacs_int\fPtmpEnergyType)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fItmpID\fP reaction identificator 
.br
\fItmpType\fP condensation or cleavage 
.br
\fItmpM_I\fP product (if condensation) or substrates (if cleavage) 
.br
\fItmpM_II\fP product (if cleavage) or substrates (if condensation) 
.br
\fItmpM_III\fP product (if cleavage) or substrates (if condensation) 
.br
\fItmpKeq\fP equilibrium constant 
.RE
.PP

.PP
Definition at line 20 of file reactions\&.cpp\&.
.SS "reactions::~reactions ()\fC [inline]\fP"

.PP
Definition at line 32 of file reactions\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBacs_int\fP reactions::getEnergyType () const\fC [inline]\fP"

.PP
Definition at line 41 of file reactions\&.h\&.
.SS "\fBacs_int\fP reactions::getEvents () const\fC [inline]\fP"

.PP
Definition at line 40 of file reactions\&.h\&.
.SS "\fBacs_longInt\fP reactions::getID () const\fC [inline]\fP"

.PP
Definition at line 35 of file reactions\&.h\&.
.SS "\fBacs_longInt\fP reactions::getSpecies_I () const\fC [inline]\fP"

.PP
Definition at line 37 of file reactions\&.h\&.
.SS "\fBacs_longInt\fP reactions::getSpecies_II () const\fC [inline]\fP"

.PP
Definition at line 38 of file reactions\&.h\&.
.SS "\fBacs_longInt\fP reactions::getSpecies_III () const\fC [inline]\fP"

.PP
Definition at line 39 of file reactions\&.h\&.
.SS "\fBacs_int\fP reactions::getType () const\fC [inline]\fP"

.PP
Definition at line 36 of file reactions\&.h\&.
.SS "void reactions::resetEventsCounter ()\fC [inline]\fP"

.PP
Definition at line 45 of file reactions\&.h\&.
.SS "void reactions::updateTotEvents ()\fC [inline]\fP"

.PP
Definition at line 44 of file reactions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
