.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/readParameters.m" 3 "Wed Jul 24 2013" "Version 4.3 (20130719.55)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/readParameters.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "while \fBischar\fP (\fBtline\fP) \fBtline\fP"
.br
.ti -1c
.RI "\fBif\fP \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBnSeconds\fP') \fBconfparams\&.nSeconds\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBnGEN\fP') \fBconfparams\&.nGEN\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBnSIM\fP') \fBconfparams\&.nSIM\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBnReactions\fP') \fBconfparams\&.nReactions\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBtimeStructuresSavingInterval\fP') \fBconfparams\&.timeStructuresSavingInterval\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBfileTimesSaveInterval\fP') \fBconfparams\&.fileTimesSaveInterval\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBreactionProbability\fP') \fBconfparams\&.reactionProbability\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBenergy\fP') \fBconfparams\&.energy\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'ECConcentration') confparams\&.ECConcentration"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBinflux_rate\fP') \fBconfparams\&.influx_rate\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBmaxLOut\fP') \fBconfparams\&.maxLOut\fP"
.br
.ti -1c
.RI "elseif \fBisequal\fP (\fBtline\fP(1:\fBparam\fP-1),'\fBvolume\fP') \fBconfparams\&.volume\fP"
.br
.ti -1c
.RI "\fBend\fP \fBend\fP \fBfclose\fP (fidConf)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBconfparams\fP"
.br
.ti -1c
.RI "\fBtline\fP = fgets(fidConf)"
.br
.ti -1c
.RI "\fBparam\fP = findstr(\fBtline\fP,'=')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBend\fP \fBend\fP fclose (fidConf)"

.SS "while ischar (\fBtline\fP)"

.SS "\fBif\fP isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBnSeconds\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBnGEN\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBnSIM\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBnReactions\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBtimeStructuresSavingInterval\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBfileTimesSaveInterval\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBreactionProbability\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBenergy\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), 'ECConcentration')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBinflux_rate\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBmaxLOut\fP')"

.SS "elseif isequal (\fBtline\fP(1:\fBparam\fP-1), '\fBvolume\fP')"

.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP confparams"
\fBInitial value:\fP
.PP
.nf
= readParameters()

    fidConf=fopen('acsm2s\&.conf','r')
.fi
.PP
Definition at line 1 of file readParameters\&.m\&.
.SS "param = findstr(\fBtline\fP,'=')"

.PP
Definition at line 9 of file readParameters\&.m\&.
.SS "tline = fgets(fidConf)"

.PP
Definition at line 5 of file readParameters\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
