.TH "resetForNewSimulations" 3 "Mon Jul 8 2013" "Version 4.1 (20130708.53)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
resetForNewSimulations \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBfoldersSIMS\fP = 10"
.br
.ti -1c
.RI "int \fBfoldersREP\fP = 10"
.br
.ti -1c
.RI "tuple \fBzerosSIMS\fP = \fBzeroBeforeStrNum\fP(\fBi\fP,\fBfoldersSIMS\fP)"
.br
.ti -1c
.RI "tuple \fBzerosREPS\fP = \fBzeroBeforeStrNum\fP(\fBj\fP,\fBfoldersREP\fP)"
.br
.ti -1c
.RI "string \fBfolderName\fP = 's_inv_1e-2_'"
.br
.ti -1c
.RI "string \fBfolderNew\fP = 's_inv_1e-1_'"
.br
.ti -1c
.RI "tuple \fBresdir\fP = os\&.path\&.join(os\&.curdir, 'res')"
.br
.ti -1c
.RI "tuple \fBcrtSimFolder\fP = os\&.path\&.join(StrTo,\fBfolderName\fP)"
.br
.ti -1c
.RI "tuple \fBfileDest\fP = os\&.path\&.join(StrTo,\fBfolderNew\fP,'_acsinflux\&.csv')"
.br
.ti -1c
.RI "tuple \fBspeciesFiles\fP = sorted(glob\&.glob('species_1_*'))"
.br
.ti -1c
.RI "tuple \fBmod\fP = open('_acsspecies\&.csv')"
.br
.ti -1c
.RI "int \fBid\fP = 0"
.br
.ti -1c
.RI "tuple \fBlinesplitted\fP = \fBline\&.split\fP('\\t')"
.br
.ti -1c
.RI "tuple \fBfile\fP = open('_acsspecies\&.csv', 'w')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def resetForNewSimulations\&.zeroBeforeStrNum (tmpl, tmpL)"

.PP
Definition at line 5 of file resetForNewSimulations\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple resetForNewSimulations\&.crtSimFolder = os\&.path\&.join(StrTo,\fBfolderName\fP)"

.PP
Definition at line 51 of file resetForNewSimulations\&.py\&.
.SS "tuple resetForNewSimulations\&.file = open('_acsspecies\&.csv', 'w')"

.PP
Definition at line 99 of file resetForNewSimulations\&.py\&.
.SS "tuple resetForNewSimulations\&.fileDest = os\&.path\&.join(StrTo,\fBfolderNew\fP,'_acsinflux\&.csv')"

.PP
Definition at line 57 of file resetForNewSimulations\&.py\&.
.SS "string resetForNewSimulations\&.folderName = 's_inv_1e-2_'"

.PP
Definition at line 31 of file resetForNewSimulations\&.py\&.
.SS "string resetForNewSimulations\&.folderNew = 's_inv_1e-1_'"

.PP
Definition at line 32 of file resetForNewSimulations\&.py\&.
.SS "int resetForNewSimulations\&.foldersREP = 10"

.PP
Definition at line 22 of file resetForNewSimulations\&.py\&.
.SS "int resetForNewSimulations\&.foldersSIMS = 10"

.PP
Definition at line 21 of file resetForNewSimulations\&.py\&.
.SS "int resetForNewSimulations\&.id = 0"

.PP
Definition at line 83 of file resetForNewSimulations\&.py\&.
.SS "tuple resetForNewSimulations\&.linesplitted = \fBline\&.split\fP('\\t')"

.PP
Definition at line 85 of file resetForNewSimulations\&.py\&.
.SS "tuple resetForNewSimulations\&.mod = open('_acsspecies\&.csv')"

.PP
Definition at line 82 of file resetForNewSimulations\&.py\&.
.SS "tuple resetForNewSimulations\&.resdir = os\&.path\&.join(os\&.curdir, 'res')"

.PP
Definition at line 42 of file resetForNewSimulations\&.py\&.
.SS "tuple resetForNewSimulations\&.speciesFiles = sorted(glob\&.glob('species_1_*'))"

.PP
Definition at line 66 of file resetForNewSimulations\&.py\&.
.SS "tuple resetForNewSimulations\&.zerosREPS = \fBzeroBeforeStrNum\fP(\fBj\fP,\fBfoldersREP\fP)"

.PP
Definition at line 29 of file resetForNewSimulations\&.py\&.
.SS "tuple resetForNewSimulations\&.zerosSIMS = \fBzeroBeforeStrNum\fP(\fBi\fP,\fBfoldersSIMS\fP)"

.PP
Definition at line 28 of file resetForNewSimulations\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
