.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/resetForNewSimulations.py" 3 "Wed Jul 24 2013" "Version 4.3 (20130719.55)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/resetForNewSimulations.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBresetForNewSimulations\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBresetForNewSimulations\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBresetForNewSimulations\&.zeroBeforeStrNum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBresetForNewSimulations\&.foldersSIMS\fP = 10"
.br
.ti -1c
.RI "int \fBresetForNewSimulations\&.foldersREP\fP = 10"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.zerosSIMS\fP = zeroBeforeStrNum(\fBi\fP,foldersSIMS)"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.zerosREPS\fP = zeroBeforeStrNum(\fBj\fP,foldersREP)"
.br
.ti -1c
.RI "string \fBresetForNewSimulations\&.folderName\fP = 's_inv_1e-2_'"
.br
.ti -1c
.RI "string \fBresetForNewSimulations\&.folderNew\fP = 's_inv_1e-1_'"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.resdir\fP = os\&.path\&.join(os\&.curdir, 'res')"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.crtSimFolder\fP = os\&.path\&.join(StrTo,folderName)"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.fileDest\fP = os\&.path\&.join(StrTo,folderNew,'_acsinflux\&.csv')"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.speciesFiles\fP = sorted(glob\&.glob('species_1_*'))"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.mod\fP = open('_acsspecies\&.csv')"
.br
.ti -1c
.RI "int \fBresetForNewSimulations\&.id\fP = 0"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.linesplitted\fP = \fBline\&.split\fP('\\t')"
.br
.ti -1c
.RI "tuple \fBresetForNewSimulations\&.file\fP = open('_acsspecies\&.csv', 'w')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
