.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/somma.m" 3 "Thu Sep 19 2013" "Version 4.5 (20130919.57)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/somma.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBsomma\fP (N) close all \fBa\fP"
.br
.ti -1c
.RI "\fBa\fP (\fBi\fP)"
.br
.ti -1c
.RI "\fBif\fP \fBr\fP \fBb\fP (\fBi\fP)"
.br
.ti -1c
.RI "\fBend\fP \fBc\fP (\fBi\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBb\fP = zeros(1,N)"
.br
.ti -1c
.RI "\fBc\fP = zeros(1,N)"
.br
.ti -1c
.RI "for \fBi\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "a (\fBi\fP)"

.SS "\fBif\fP \fBr\fP b (\fBi\fP)"

.SS "\fBend\fP c (\fBi\fP)"

.SS "\fBfunction\fP somma (N)"

.SH "Variable Documentation"
.PP 
.SS "b = zeros(1,N)"

.PP
Definition at line 7 of file somma\&.m\&.
.SS "c = zeros(1,N)"

.PP
Definition at line 8 of file somma\&.m\&.
.SS "for i"
\fBInitial value:\fP
.PP
.nf
= 1 : N
    r = rand()
.fi
.PP
Definition at line 10 of file somma\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
