.TH "/home/ale/Documents/GIT/carness/_analysis/old/stats.m" 3 "Fri Mar 28 2014" "Version 4.8 (20140327.66)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ale/Documents/GIT/carness/_analysis/old/stats.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBstats\fP ()%clear all%close all%%\fBparams\&.path\fP"
.br
.ti -1c
.RI "\fBconcAnalysis\fP (params)%clear all%close all%%\fBparams\&.path\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "params \fBdeltaT\fP = 10"
.br
.ti -1c
.RI "params \fBtotT\fP = 1000"
.br
.ti -1c
.RI "params \fBshowFig\fP = 0"
.br
.ti -1c
.RI "params \fBfigureVisible\fP = 0"
.br
.ti -1c
.RI "params \fBthreshold\fP = 0"
.br
.ti -1c
.RI "params \fBdecayTime\fP = 10"
.br
.ti -1c
.RI "params \fBtmpResFold\fP = 'res'"
.br
.ti -1c
.RI "params \fBdistinctiveSubStr\fP = 'sim'"
.br
.ti -1c
.RI "params \fBtmpIDsim\fP = '5'"
.br
.ti -1c
.RI "params \fBtmpRctFileToLoad\fP = ''"
.br
.ti -1c
.RI "params \fBtmpRctSUBFileToLoad\fP = ''"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "concAnalysis (params)"

.SS "\fBfunction\fP stats ()"

.SH "Variable Documentation"
.PP 
.SS "params decayTime = 10"

.PP
Definition at line 84 of file stats\&.m\&.
.SS "params deltaT = 10"

.PP
Definition at line 7 of file stats\&.m\&.
.SS "params distinctiveSubStr = 'sim'"

.PP
Definition at line 86 of file stats\&.m\&.
.SS "params figureVisible = 0"

.PP
Definition at line 57 of file stats\&.m\&.
.SS "params showFig = 0"

.PP
Definition at line 9 of file stats\&.m\&.
.SS "params threshold = 0"

.PP
Definition at line 83 of file stats\&.m\&.
.SS "params tmpIDsim = '5'"

.PP
Definition at line 87 of file stats\&.m\&.
.SS "params tmpRctFileToLoad = ''"

.PP
Definition at line 88 of file stats\&.m\&.
.SS "params tmpRctSUBFileToLoad = ''"

.PP
Definition at line 89 of file stats\&.m\&.
.SS "params tmpResFold = 'res'"

.PP
Definition at line 85 of file stats\&.m\&.
.SS "params totT = 1000"

.PP
Definition at line 8 of file stats\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
