.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/timesAnalysis.m" 3 "Thu Sep 19 2013" "Version 4.5 (20130919.57)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/timesAnalysis.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBout\fP]"
.br
.ti -1c
.RI "hence different scatterplot 
.br
between different dimensions 
.br
are performed Output \fBout\fP is \fBa\fP 
.br
structure containing two \fBvariables\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "function[\fBout\fP]"
\fBInitial value:\fP
.PP
.nf
= timesAnalysis(param)
% function [out] = timesAnalysis(tmpPath)
%
% This function collects all the last reactions contained in both the times and
% reactions_parameter files
.fi
.PP
Definition at line 1 of file timesAnalysis\&.m\&.
.SS "hence different scatterplot between different dimensions are performed Output \fBout\fP is \fBa\fP structure containing two variables"

.PP
Definition at line 1 of file timesAnalysis\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
