.TH "/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/timesAnalysis_PANINI.m" 3 "Mon Jul 8 2013" "Version 4.1 (20130708.53)" "CaRNeSS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/alessandrofilisetti/Documents/GIT/carness/_analysis/timesAnalysis_PANINI.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBout\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "function[\fBout\fP]"
\fBInitial value:\fP
.PP
.nf
= timesAnalysis(tmpPath)
% function [out] = timesAnalysis(tmpPath)
%
% This function collects all the last reactions contained in the times and
% reactions_parameter files and performs different scatterplot between different dimensions\&.
% Output out is a structure containing two variables:
% out\&.timesMatrix = all the last row of the times files
% out\&.cct = the correlation coefficients of the out\&.timesMatrix matrix
%
% INPUT
% tmpPath = path of the simulations root 

currentDir = cd()
.fi
.PP
Definition at line 1 of file timesAnalysis_PANINI\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CaRNeSS from the source code\&.
